let questions = [
  {
    numb: 0,
    question: "Karcinoembryonálny antigén (CEA) sa používa",
    answer: [" na monitorovanie liečby pacientov s kolorektálnym karcinómom", " na včasnú diagnostiku recidívy kolorektálneho karcinómu "],
    options: ["na plošný skríning gastrointestinálnych nádorov"," na monitorovanie liečby pacientov s kolorektálnym karcinómom"," na včasnú diagnostiku kolorektálneho karcinómu", " na včasnú diagnostiku recidívy kolorektálneho karcinómu "],
 },
 {
    numb: 1,
    question: "Karcinoembryonálny antigén (CEA) sa používa",
    answer: [" na skríning kolorektálneho karcinómu v rizikových skupinách ","u pacientov s adenokarcinómom pľúc"],
    options: [" na skríning kolorektálneho karcinómu v rizikových skupinách ", "na skríning nádorov pankreasu", "na sledovanie pacientov s malobunkovým karcinómom pľúc", "u pacientov s adenokarcinómom pľúc"],
 },
 {
    numb: 2,
    question: "Karcinoembryonálny antogén (CEA)",
    answer: ["býva zvýšený u fajčiarov", "môže byť zvýšený pri divertikulitíde čreva","hodnoty do 10 µg/l nemusia znamenať prítomnosť nádoru"],
    options: ["používa sa aj v prenatálnej diagnostike", "býva zvýšený u fajčiarov", "môže byť zvýšený pri divertikulitíde čreva","hodnoty do 10 µg/l nemusia znamenať prítomnosť nádoru"],
 },
 {
    numb: 3,
    question: ".Karcinoembryonálny antogén (CEA)",
    answer: ["môže mať prognostický význam pri kolorektálnom karcinóme","fyziologicky je produkovaný bunkami GIT-u vo fetálnom období"],
    options: ["hodnoty do 10 µg/l sú podozrivé z prítomnosti metastáz","môže mať prognostický význam pri kolorektálnom karcinóme","fyziologicky je produkovaný bunkami GIT-u vo fetálnom období","je to látka hormonálnej povahy "],
 },
 {
    numb: 4,
    question: "Karcinoembryonálny antigén (CEA)",
    answer: ["môže byť zvýšený aj pri benigných chorobách", "môže byť zvýšený pri zápaloch čreva" ," môže byť zvýšený pri niektorých nádoroch pľúc "],
    options: ["môže byť zvýšený aj pri benigných chorobách", "môže byť zvýšený pri zápaloch čreva"," býva pravidelne zvýšený u pacientov s nádorom pankreasu" ," môže byť zvýšený pri niektorých nádoroch pľúc "],
 },
 {
    numb: 5,
    question: "Karcinoembryonálny antogén (CEA)",
    answer: ["môže byť zvýšený u pacientov s cirhózou pečene"],
    options: ["býva zvýšený pri nádoroch pľúc z dlaždicového epitelu","môže byť zvýšený u pacientov s cirhózou pečene","používa sa ako marker pri cervikálnom karcinóme","používa sa pri seróznom type cystadenokarcinómu vaječníkov", ],
 },
 {
    numb: 6,
    question: "Karcinoembryonálny antigén (CEA)",
    answer: ["fyziologicky sa syntetizuje v bunkách fetálneho čreva"],
    options: ["fyziologicky sa syntetizuje v bunkách fetálnej pečene","fyziologicky sa syntetizuje v bunkách fetálneho čreva", " býva zvýšený pri hepatocelulárnom karcinóme"," býva zvýšený pri malobunkovom karcinóme pľúc"],
 },
 {
    numb: 7,
    question: "Vyšetrenie hladiny karcinoembryonálneho antigénu sa používa pri",
    answer: ["pri monitorovaní liečby u pacienta s kolorektálnym karcinómom","pri skríningu nádoru hrubého čreva u pacientov s polypózou čreva"],
    options: ["diferenciálnej diagnostike hepatocelulárneho a cholangiocelulárneho karcinómu","diagnostike cirhózy pečene","pri monitorovaní liečby u pacienta s kolorektálnym karcinómom","pri skríningu nádoru hrubého čreva u pacientov s polypózou čreva"],
 },
 {
    numb: 8,
    question: "Karcinoembryonálny antigén (CEA)",
    answer: ["je onkofetálny antigén","býva zvýšený pri adenokarcinóme prsníka"],
    options: ["je onkofetálny antigén","je onkoplacentárny antigén","býva zvýšený pri adenokarcinóme prsníka","býva zvýšený pri nádoroch z plochého dlaždicového epitelu"],
 },
 {
    numb: 9,
    question: "Alfa-fetoproteín",
    answer: ["fyziologickly je produkovaný bunkami fetálnej pečene","fyziologicky je produkovaný bunkami žltkového vaku", "fyziologicky býva zvýšený v sére gravidných žien"],
    options: ["fyziologickly je produkovaný bunkami fetálnej pečene","fyziologicky je produkovaný bunkami žltkového vaku","v plodovej vode sa používa na posúdenie zrelosti pľúc plodu", "fyziologicky býva zvýšený v sére gravidných žien"],
 },
 {
    numb: 10,
    question: "Alfa-fetoproteín",
    answer: ["jeho vyšetrenie v krvi sa používa pri skríningu razštepov neurálnej trubice","sa svojimi vlastnosťami a funkciou podobá albumínu"],
    options: ["jeho vyšetrenie v krvi sa používa pri skríningu razštepov neurálnej trubice","sa svojimi vlastnosťami a funkciou podobá albumínu","používa sa na dôkaz gravidity","býva zvýšený pri metastatickom postihnutí pečene"],
 },
 {
    numb: 11,
    question: "Zvýšené hladiny alfa-fetoproteínu bývajú pravidelne pri",
    answer: ["primárnom hepatocelulárnom karcinóme","niektorých nádoroch semenníkov"],
    options: ["primárnom hepatocelulárnom karcinóme","niektorých nádoroch semenníkov","pri metastáze nádorov čreva do pečene","pokročilom mnohopočetnom myelóme" ],
 },
 {
    numb: 12,
    question: "Zvýšené hladiny AFP bývajú pravidelne pri",
    answer: ["v priebehu gravidity"],
    options: ["nádoroch vaječníkov","nádoroch pľúc","malobunkovom karcinóme pľúc","v priebehu gravidity"],
 },
 {
    numb: 13,
    question: "AFP",
    answer: ["možno použiť pri odlíšení hepatocelulárneho karcinómu od metastáz do pečene","možno použiť pri rozlíšení hepatocelulárneho karcinómu a cholangiocelulárneho karcinómu"," je onkofetálny antigén"],
    options: ["možno použiť pri odlíšení hepatocelulárneho karcinómu od metastáz do pečene","možno použiť pri rozlíšení hepatocelulárneho karcinómu a cholangiocelulárneho karcinómu","býva zvýšený u pacientov s adenómom pečene"," je onkofetálny antigén"],
 },
 {
    numb: 14,
    question: "Hladiny AFP bývajú zvýšené",
    answer: ["pri cirhóze pečene","pri regenerácii pečene","v gravidite"],
    options: ["pri cirhóze pečene","pri regenerácii pečene","v gravidite","pri Downovom syndróme"],
 },
 {
    numb: 15,
    question: "Alfa-fetoproteín",
    answer: ["používa sa pri diagnostike germinatívnych nádorov testes","používa sa na sledovanie pacientov s maldescensusu testes"],
    options: ["používa sa pri diagnostike germinatívnych nádorov testes","je vyšetrením 1.voľby pri podozerní na nádor pankreasu","používa sa na sledovanie pacientov s maldescensusu testes","používa sa v diagnostike nádorov prostaty"],
 },
 {
    numb: 16,
    question: "Hladiny hCG bývajú zvýšené pri",
    answer: ["choriokarcinóme","mola hydatidosa","aj pri niektorých netrofoblastových nádoroch"],
    options: ["choriokarcinóme","mola hydatidosa","aj pri niektorých netrofoblastových nádoroch","len pri nádoroch z trofoblastu" ],
 },
 {
    numb: 17,
    question: "Hladiny hCG bývajú zvýšené pri",
    answer: ["gravidite","aj pri extrauterinnej gravidite "],
    options: ["malobunkovom karcinóme pľúc","pri ovariálnom karcinóme","gravidite","aj pri extrauterinnej gravidite "],
 },
 {
    numb: 18,
    question: "O hCG môžeme povedať",
    answer: ["vyšetrujeme ho v rámci skríningu u gravidných žien"],
    options: ["býva zvýšený pri pravých seminómoch","býva zvýšený pri nádoroch semenníkov obsahujúcich štruktúry žltkového vaku","vyšetrujeme ho v rámci skríningu u gravidných žien"," býva zvýšený u plodov s anencefaliou" ],
 },
 {
    numb: 19,
    question: "O hCG môžeme povedať",
    answer: ["používa sa pri skríningu Downovej choroby","býva zvýšený pri invazívnej mole","vyšetruje sa aj voľná beta-podjednotka"],
    options: ["používa sa pri skríningu Downovej choroby","býva zvýšený pri invazívnej mole","vyšetruje sa aj voľná alfa-podjednotka","vyšetruje sa aj voľná beta-podjednotka"],
 },
 {
    numb: 20,
    question: "O testikulárnych nádoroch možno povedať",
    answer: ["čistý seminóm má obvykle normálny AFP"," zrelé teratómy mávajú obvykle negatívny AFP aj hCG","choriokarcinómy majú zvýšené hCG a negatívne AFP",],
    options: ["čistý seminóm má obvykle normálny AFP"," zrelé teratómy mávajú obvykle negatívny AFP aj hCG","choriokarcinómy majú zvýšené hCG a negatívne AFP","nádory obsahujúce štruktúry žltkového vaku majú zvýšený hCG" ],
 },
 {
    numb: 21,
    question: "O testikulárnych nádoroch možno povedať",
    answer: [ "čistý seminóm má obvykle normálny hCG", "embryonálny karcinóm má zvýšené AFP aj hCG "],
    options: ["choriokarcinómy majú zvýšený AFP a negatívny hCG", "embryonálne karcinómy majú negatívny AFP aj hCG", "čistý seminóm má obvykle normálny hCG", "embryonálny karcinóm má zvýšené AFP aj hCG "],
 },
 {
    numb: 22,
    question: "O nádoroch pľúc možno povedať ",
    answer: ["markerom adenokarcinómu pľúc je CEA","nádor z viacvrstvového dlaždicového epitelu má zvýšené hladiny SCC "],
    options: ["markerom pre malobunkový karcinóm pľúc je CYFRA 21-1","markerom adenokarcinómu pľúc je CEA","markerom veľkobunkového karcinómu pľúc je NSE","nádor z viacvrstvového dlaždicového epitelu má zvýšené hladiny SCC "],
 },
 {
    numb: 23,
    question: ".O nádoroch pľúc možno povedať",
    answer: [],
    options: ["malobunkový karcinóm je častejší ako nemalobunkový karcinóm", "markerom typickým pre malobunkový karcinóm pľuc je SCC", "nádor z viacvrstvového dlaždicového epitelu má zvýšené hladiny NSE"," pre nádory pľúc je charakteristické zvýšenie CA 15-3" ],
 },
 {
    numb: 24,
    question: "Neurošpecifická enoláza býva zvýšená u pacientov",
    answer: ["s neuroblastómom","s malobunkovým karcinómom pľúc" ],
    options: ["s meduloblastómom", "s myelómom", "s neuroblastómom","s malobunkovým karcinómom pľúc" ],
 },
 {
    numb: 25,
    question: "Pri stanovení prognózy u pacienta s myelómom sa používa vyšetrenie",
    answer: ["beta-2-mikroglobulínu"],
    options: ["NSE","beta-2-mikroglobulínu"," hCG","transferínu"],
 },
 {
    numb: 26,
    question: "Pre monitorovanie priebehu ochorenia u pacientov s melanómom sa používa",
    answer: [
      "S100B proteín",],
    options: ["chromogranín",
      "SCC-antigén",
      "S100B proteín",
      "tkanivový polypeptidový antigén (TPA)"],
 },
 {
    numb: 27,
    question: "SCC-antigén je",
    answer: ["zvýšený pri nádoroch pažeráka","zvýšený pri adenokarcinóme cervixu "],
    options: ["zvýšený pri nádoroch pažeráka",
      " produkovaný bunkami fetálneho GIT-u",
       "zvýšený pri hematologických malignitách",
       "zvýšený pri adenokarcinóme cervixu "],
 },
 {
    numb: 28,
    question: "SCC-antigén je",
    answer: ["zvýšený pri niektorých nádoroch pľúc",
    "zvýšený pri nádoroch ústnej dutiny"],
    options: ["zvýšený pri pankreatických nádoroch",
      "zvýšený pri niektorých nádoroch pľúc",
    "zvýšený pri nádoroch ústnej dutiny",
      "zvýšený pri adenokarcinóme žalúdka "],
 },
 {
    numb: 29,
    question: "O gynekologických nádoroch možno povedať ",
    answer: [
      "mucinózne karcinómy ovárií mávajú zvýšené hodnoty CA 72-4",
      "pri nádoroch cervixu býva zvýšený SCC-antigén"],
    options: ["mucinózne karcinómy ovárií majú zvýšené hodnoty hCG",
       "mucinózne karcinómy ovárií mávajú zvýšené hodnoty CA 72-4",
       "pri nádoroch cervixu býva zvýšený SCC-antigén",
       "pri nádoroch vagíny býva zvýšený CA 15-3 "],
 },
 {
    numb: 30,
    question: "O gynekologických nádoroch možno povedať",
    answer: ["pri nádoroch prsníka môže byť zvýšený CEA",
      "serózne karcinómy ovárií mávajú zvýšené hodnoty CA 125"],
    options: ["pri nádoroch prsníka môže byť zvýšený CEA",
      " pri nádoroch prsníka býva zvýšený AFP",
      "serózne karcinómy ovárií mávajú zvýšené hodnoty CA 125",
       "nádory maternice mávajú zvýšené hodnoty NSE "],
 },
 {
    numb: 31,
    question: "Pre nádory z viacvrstvového dlaždicového epitelu platí",
    answer: [
      "bývajú zvýšené hladiny CYFRA 21-1",
      "bývajú zvýšené hladiny SCC-antigénu"],
    options: [ "bývajú zvýšené hladiny CEA",
       "bývajú zvýšené hladiny CYFRA 21-1",
       "bývajú zvýšené hladiny CA 125",
       "bývajú zvýšené hladiny SCC-antigénu"],
 },
 {
    numb: 32,
    question: "Pre nádory z viacvrstvového dlaždicového epitelu platí",
    answer: [ "hladiny CEA sú obvykle nezmenené",
      "hladiny CA 72-4 sú obvykle nezmenené",
      "nemáva zvýšené hodnoty hCG"],
    options: [ "hladiny CEA sú obvykle nezmenené",
       "hladiny CA 72-4 sú obvykle nezmenené",
       "nemáva zvýšené hodnoty hCG",
       "bývajú zvýšené hodnoty voľnej frakcie PSA"],
 },
 {
    numb: 33,
    question: "Pri neuroblastómoch bývajú zvýšené hladiny",
    answer: ["NSE"],
    options: ["CA 72-4",
       "NSE",
       "AFP",
       "CA 15-3"],
 },
 {
    numb: 34,
    question: " Pri neuroblastómoch bývajú zvýšené hladiny",
    answer: [" alkalická peptónová voda"," selenitový bujón "," Kauffrnannova pôda"],
    options: ["CEA",
       "beta-2-mikroglobulínu",
       "PSA",
       "SCC-antigénu"],
 },
 {
    numb: 35,
    question: ".Beta-2-mikroglobulín býva zvýšený v sére pacientov s",
    answer: ["hematologickými malignitami",
       "chronickou lymfatickou leukémiou"],
    options: ["hematologickými malignitami",
       "epitelovými nádormi",
       "nádormi pankreasu",
       "chronickou lymfatickou leukémiou"],
 },
 {
    numb: 36,
    question: "Beta-2-mikroglobulín býva zvýšený v sére pacientov s",
    answer: [
      "mnohopočetným myelómom",
      "lymfómom"],
    options: [ "mucinóznym nádorom vaječníkov",
       "mnohopočetným myelómom",
       "lymfómom",
       "neuroblastómom" ],
 },
 {
    numb: 37,
    question: ".Onkomarker CA 15-3 je vyšetrením 1.voľby u pacientov s",
    answer: [
      "karcinómom prsníka"],
    options: ["karcinómom hrubého čreva",
       "karcinómom prsníka",
       "myelómom",
       "neuroblastómom" ],
 },
 {
    numb: 38,
    question: "Onkomarker CA 72-4",
    answer: ["býva zvýšený aj pri mucinóznom cystadenokarcinóme vaječníkov",
      "používa sa hlavne pri karcinómoch žalúdka",
      "môže byť zvýšený u pacientov s pankreatitídou" ],
    options: ["býva zvýšený aj pri mucinóznom cystadenokarcinóme vaječníkov",
      "býva zvýšený aj pri seróznom cystadenokarcinóme vaječkíkov",
      "používa sa hlavne pri karcinómoch žalúdka",
      "môže byť zvýšený u pacientov s pankreatitídou" ],
 },
 {
    numb: 39,
    question: "Onkomarker CA 72-4",
    answer: ["býva zvýšený pri nádoroch GIT-u",
       "môže byť zvýšený u pacientov s benignými ochoreniami žalúdka"],
    options: ["býva zvýšený pri nádoroch GIT-u",
       "býva pravidelne negatívny pri nádoroch prsníka",
       "môže byť zvýšený u pacientov s benignými ochoreniami žalúdka",
       "býva zvýšený u pacientov s testikulárnymi nádormi "],
 },
 {
    numb: 40,
    question: "Pri hepatocelulárnom karcinóme nachádzame",
    answer: [
      "zvýšenú hladinu AFP"],
    options: ["zvýšenú hladinu hCG",
       "zvýšenú hladinu AFP",
       "zvýšené aktivity ALP",
       "zvýšené aktivity CK-BB"],
 },
 {
    numb: 41,
    question: "Onkomarker CA125 sa používa ",
    answer: ["pri diagnostike gynekologických nádorov",
       "pri diagnostike karcinómov ovárií",],
    options: ["pri diagnostike gynekologických nádorov",
       "pri diagnostike karcinómov ovárií",
       "ako marker 1.voľby pri nádoroch prsníka",
       "najčastejšie pri nádoroch pľúc "],
 },
 {
    numb: 42,
    question: "Vyšetrenie onkomarkeru CA125  ",
    answer: [
      "je pri mucinóznych karcinómoch ovárií menej citlivé",
      "sa používa aj u pacientov s karcinómom pankreasu"],
    options: ["je pri seróznych karcinómoch ovárií menej citlivé",
      "je pri mucinóznych karcinómoch ovárií menej citlivé",
      "sa používa aj u pacientov s karcinómom pankreasu",
      "sa používa aj u pacientov s karcinómom žalúdka"],
 },
 {
    numb: 43,
    question: "Pri nádoroch žalúdka sa využíva hlavne vyšetrenie",
    answer: [
      "CA 72-4 "],
    options: ["CA19-9",
       "CA125",
       "CA549",
      "CA 72-4 "],
 },
 {
    numb: 44,
    question: "Pri nádoroch pankreasu sa používa ",
    answer: ["ako onkomarker 1.voľby vyšetrenie CA19-9",
       "ako marker 2.voľby vyšetrenie CA125 "],
    options: [ "hlavne vyšetrenie CA72-4",
       "ako onkomarker 1.voľby vyšetrenie CA19-9",
       "ako marker 2.voby vyšetrenie CA15-3",
       "ako marker 2.voľby vyšetrenie CA125 "],
 },
 {
    numb: 45,
    question: "Pri nádoroch cervixu maternice sa využíva vyšetrenie",
    answer: [
      "SCC-antigén"],
    options: [ "CA125",
       "CA19-9",
       "SCC-antigén",
       "NSE" ],
 },
 {
    numb: 46,
    question: "Pre vyšetrenie CA19-9 ako onkomarkera je hlavnou indikáciou",
    answer: [
      "nádor exokrinného pankreasu"],
    options: ["nádor žalúdka",
       "nádory pečene",
       "nádor exokrinného pankreasu",
       "nádory semenníkov"],
 },
 {
    numb: 47,
    question: "Pri nádoroch pľúc sa využíva vyšetrenie",
    answer: ["CYFRA21-1",
       "NSE",
       "CEA"],
    options: ["CYFRA21-1",
       "NSE",
       "CEA",
       "CA15-3 "],
 },
 {
    numb: 48,
    question: "Pri adenokarcinóme pľúc sa uplatňuje vyšetrenie",
    answer: ["CEA"],
    options: ["CYFRA21-1",
      "NSE",
      "CEA",
      "AFP"],
 },
 {
    numb: 49,
    question: "Pri metastatickom postihnutí pečene býva",
    answer: ["zvýšená aktivita GMT",
       "zvýšená hladina CEA",
       "zvýšená aktivita ALP"],
    options: ["zvýšená aktivita GMT",
       "zvýšená hladina CEA",
       "zvýšená aktivita ALP",
       "zvýšená hladina AFP "],
 },
 {
    numb: 50,
    question: "Laktátdehydrogenáza",
    answer: ["je ubikvitárny enzým",
       "je bohato zastúpená v erytrocytoch",
       "býva v sére zvýšená pri poškodeniach pečene"],
    options: ["je ubikvitárny enzým",
       "je bohato zastúpená v erytrocytoch",
       "býva v sére zvýšená pri poškodeniach pečene",
       "má štyri izoenzýmy"],
 },
 {
    numb: 51,
    question: "Laktátdehydrogenáza",
    answer: ["býva zvýšená u pacientov s nádorovým ochorením",
       "býva zvýšená pri hemolýze",
       "môže byť zvýšená po väčšej fyzickej záťaži "],
    options: ["je lokalizovaná v mitochondriach",
       "býva zvýšená u pacientov s nádorovým ochorením",
       "býva zvýšená pri hemolýze",
       "môže byť zvýšená po väčšej fyzickej záťaži "],
 },
 {
    numb: 52,
    question: "O laktátdehydrogenáze môžeme povedať",
    answer: ["v sére je najviac zastúpený izoenzým LD-2",
       "z kardiálnych enzýmov sa zvyšuje ako posledná "],
    options: ["v sére je fyziologicky najviac zastúpený izoenzým LD-5",
       "v sére je najviac zastúpený izoenzým LD-2",
      " hemolýza znižuje jej aktivitu",
       "z kardiálnych enzýmov sa zvyšuje ako posledná "],
 },
 {
    numb: 53,
    question: "O laktátdehydrogenáze môžeme povedať",
    answer: [ "izoenzým LD-1 býva zvýšený pri poškodení myokardu",
      "jej vyšetrenie nemá praktický význam u pacientov s ochorením pankreasu"],
    options: ["izoenzým LD-1 býva zvýšený pri pečeňových ochoreniach",
       "izoenzým LD-1 býva zvýšený pri poškodení myokardu",
       "jej koenzýmom je FAD",
       "jej vyšetrenie nemá praktický význam u pacientov s ochorením pankreasu"],
 },
 {
    numb: 54,
    question: "Laktátdehydrogenáza",
    answer: [
      " v hepatologii sa využíva vyšetrenie izoenzýmu LD5",
       "pri onkologických ochoreniach sa jej aktivita zvyšuje"],
    options: ["v kardiologii sa využíva vyšetrenie izoenzýmu LD2",
      " v hepatologii sa využíva vyšetrenie izoenzýmu LD5",
       "pri onkologických ochoreniach sa jej aktivita zvyšuje",
      "izoenzým LD1 označujeme ako alfa-butyrátdehyydrogenázu "],
 },
 {
    numb: 55,
    question: "Laktátdehydrogenáza",
    answer: [
      "je markerom intravaskulárnej hemolýzy",
      "jej aktivita býva zvýšená pri pernicioznej anémii "],
    options: [ "u pacientov s akútnym infarktom myokardu sa normalizuje za 3 dni",
       "u pacientov s akútnym infarktom myokardu sa normalizuje za 24 hodín",
       "je markerom intravaskulárnej hemolýzy",
       "jej aktivita býva zvýšená pri pernicioznej anémii "],
 },
 {
    numb: 56,
    question: "Pre laktátdehydrogenázu platí",
    answer: [
      "jej aktivita sa pri infarkte myokardu zvyšuje 6-12 hodín po vzniku ischémie",
      "pri akútnom infarkte myokardu sa zvyšuje predovšetkým izoenzým LD1",
      "najviac zastúpeným izoenzýmom v erytrocytoch je LD2 "],
    options: ["jej aktivita sa pri infarkte myokardu zvyšuje 1-2 hodiny po vzniku ischémi",
       "jej aktivita sa pri infarkte myokardu zvyšuje 6-12 hodín po vzniku ischémie",
       "pri akútnom infarkte myokardu sa zvyšuje predovšetkým izoenzým LD1",
       "najviac zastúpeným izoenzýmom v erytrocytoch je LD2 "],
 },
 {
    numb: 57,
    question: "Výrazné zvýšenie aktivity laktátdehydrogenázy nachádzame pri",
    answer: ["poruchách pečene",
       "hemolytických stavoch",
       "maligných nádoroch "],
    options: [ "poruchách pečene",
       "hemolytických stavoch",
       "chronickej pankreatitíde",
       "maligných nádoroch "],
 },
 {
    numb: 58,
    question: "O laktátdehydrogenáze platí",
    answer: [
      "pre ochorenie pečene je typické zvýšenie aktivity LD5",
      "pri malígnych ochoreniach sa zvyšuje hlavne aktivita LD3 - LD5"],
    options: [ "pre ochorenie myokardu je typické zvýšenie aktivity LD2",
       "pre ochorenie pečene je typické zvýšenie aktivity LD5",
       "pre myopatie je charakteristické zvýšenie aktivity LD5",
       "pri malígnych ochoreniach sa zvyšuje hlavne aktivita LD3 - LD5"],
 },
 {
    numb: 59,
    question: "Gama-glutamyltransferáza",
    answer: [
      "patrí medzi tzv. cholestatické enzýmy",
      "je membránovo-viazaný enzým"],
    options: ["jej prevažná časť sa nachádza v mitochondriach",
       "patrí medzi tzv. cholestatické enzýmy",
       "je membránovo-viazaný enzým",
       "je cytosolový enzým "],
 },
 {
    numb: 60,
    question: "Gama-glutamyltransferáza",
    answer: ["je induktívny enzým",
       "býva zvýšená pri alkoholizme",],
    options: ["je induktívny enzým",
       "býva zvýšená u pacientov s akútnym infarktom myokardu",
       "býva zvýšená pri alkoholizme",
       "je ukazovateľom proteosyntetickej funkcie pečene "],
 },
 {
    numb: 61,
    question: "O gama-glutamyltransferáze možno povedať",
    answer: ["býva zvýšená pri užívaní barbiturátov",
       "býva zvýšená pri cholestáze"],
    options: [ "býva zvýšená pri užívaní barbiturátov",
       "býva zvýšená pri užívaní beta-blokátorov",
       "býva zvýšená hlavne pri hepatitíde A",
       "býva zvýšená pri cholestáze"],
 },
 {
    numb: 62,
    question: "O gama-glutamyltransferáze možno povedať",
    answer: [ "býva zvýšená pri alkohol-toxickej hepatitíde",
      "ak je zvýšená a zvýšená je aj ALP, tak ide o cholestázu",
      "jej zvýšené hodnoty v sére pochádzajú len z pečene"],
    options: [ "býva zvýšená pri alkohol-toxickej hepatitíde",
       "ak je zvýšená a zvýšená je aj ALP, tak ide o cholestázu",
       "jej zvýšené hodnoty v sére pochádzajú len z pečene",
       "býva zvýšená pri intoxikácii organofosfátmi "],
 },
 {
    numb: 63,
    question: "O gama-glutamyltransferáze možno povedať",
    answer: ["zdrojom jej zvýšených aktivít v sére je len pečeň"],
    options: ["zdrojom zvýšených aktivít v sére môžu byť erytrocyty",
       "zdrojom jej zvýšených aktivít v sére je len pečeň",
       "zdrojom jej zvýšených aktivít v sére môžu byť obličky",
       "zvýšenie jej aktivity v sére podmieňuje hypercholesterolémia "],
 },
 {
    numb: 64,
    question: "Zvýšená aktivita GMT v sére býva prítomná pri ",
    answer: ["konzumácii alkoholu",
       "pri cholestatických hepatopatiach"],
    options: ["užívaní acylpyrínu",
       "konzumácii alkoholu",
       "pri cholestatických hepatopatiach",
       "zvýšení fibrogenézy v pečeni "],
 },
 {
    numb: 65,
    question: "Zvýšená aktivita GMT v sére môže byť u pacientov",
    answer: ["s obštrukčným ikterom",
       "s primárnou biliárnou cirhózou",
       "s nádorovým postihnutím pečene "],
    options: ["s obštrukčným ikterom",
       "s prehepatálnym ikterom",
       "s primárnou biliárnou cirhózou",
       "s nádorovým postihnutím pečene "],
 },
 {
    numb: 66,
    question: "Pre GMT platí",
    answer: ["aktivita GMT býva zvýšená u pacientov užívajúcich barbituráty",
       "pri alkoholových hepatopatiach",
       "pri cholestatických hepatopatiach "],
    options: ["pri diagnostike sa využíva aj vyšetrenie izoenzýmov GMT",
       "aktivita GMT býva zvýšená u pacientov užívajúcich barbituráty",
       "pri alkoholových hepatopatiach",
       "pri cholestatických hepatopatiach "],
 },
 {
    numb: 67,
    question: "O aminotransferázach možno povedať",
    answer: ["najvyššia špecifická aktivita AST je v myokarde"],
    options: ["AST je membránovo-viazaný enzým",
       "najvyššia špecifická aktivita AST je v myokarde",
       "ALT je hlavne mitochondriový enzým",
       "AST je hlavne cytosolový enzým "],
 },
 {
    numb: 68,
    question: "O aminotransferázach možno povedať",
    answer: [
      "pomer AST/ALT sa používa v hepatológii",
      "ich aktivita môže byť zvýšená po väčšej fyzickej námahe",
      "AST býva zvýšená pri ochoreniach pečene "],
    options: ["pomer AST/ALT sa používa v kardiológii",
       "pomer AST/ALT sa používa v hepatológii",
       "ich aktivita môže byť zvýšená po väčšej fyzickej námahe",
       "AST býva zvýšená pri ochoreniach pečene "],
 },
 {
    numb: 69,
    question: "ALT",
    answer: ["jej aktivita býva zvýšená u pacientov s hepatitídou typu A",
       "jej aktivita býva zvýšená u pacientov s myozitídou",
      "používa sa ako skríningové vyšetrenie pri podozrení na ochorenie pečene"],
    options: [ "jej aktivita býva zvýšená u pacientov s hepatitídou typu A",
       "jej aktivita býva zvýšená u pacientov s myozitídou",
      "používa sa ako skríningové vyšetrenie pri podozrení na ochorenie pečene",
       "je vhodný parameter pri podozrení na ochorenia srdca "],
 },
 {
    numb: 70,
    question: "ALT",
    answer: ["zvyšuje sa aj pri ľahšom ochorení pečene",
       "má nižšiu aktivitu v erytrocytoch ako AST"],
    options: ["zvyšuje sa aj pri ľahšom ochorení pečene",
       "aj malá hemolýza zvyšuje jej aktivitu v sére",
       "má nižšiu aktivitu v erytrocytoch ako AST",
       "patrí medzi cholestatické enzýmy"],
 },
 {
    numb: 71,
    question: "Výrazné zvýšenie aktivity ALT je charakteristické pre",
    answer: ["akútnu vírusovú hepatitídu"],
    options: ["akútnu vírusovú hepatitídu",
       "cirhózu pečene",
       "extrahepatálnu obštrukciu",
       "hemolýzu" ],
 },
 {
    numb: 72,
    question: "Aktivita AST v sére",
    answer: ["sa výrazne zvyšuje pri akútnych toxických hepatitídach",
       "sa zvyšuje pri myopatiach "],
    options: [ "sa výrazne zvyšuje pri akútnych toxických hepatitídach",
       "sa výrazne zvyšuje pri chronickej hepatitíde",
       "sa zvyšuje výraznejšie ako ALT u pacientov s cirhózou pečene",
       "sa zvyšuje pri myopatiach "],
 },
 {
    numb: 73,
    question: "Pomer aktivity AST+ALT/glutamátdehydrogenáza",
    answer: ["jeho hodnota sa zvyšuje u pacientov s chronickým zlyhávaním pravého srdca"],
    options: ["čím je vyšší, tym je poškodenie pečene závažnejšie",
      " jeho hodnota sa využíva u pacientov s poškodením myokardu",
       "jeho hodnota sa zvyšuje u pacientov s chronickým zlyhávaním pravého srdca",
       "používa sa ako marker intravaskulárnej hemolýzy"],
 },
 {
    numb: 74,
    question: "Cholínesteráza",
    answer: ["používa sa ako ukazovateľ proteosyntetickej funkcie pečene",
       "jej aktivita sa pri poškodení pečene obvykle znižuje"],
    options: ["zvýšenie jej aktivity indukuje alkohol",
       "používa sa ako ukazovateľ proteosyntetickej funkcie pečene",
       "jej aktivita sa pri poškodení pečene obvykle znižuje",
       "jej aktivita sa pri ochoreniach pečene zvyšuje "],
 },
 {
    numb: 75,
    question: "Cholínesteráza",
    answer: ["býva zvýšená pri obezite a hyperlipoproteinémii",
       "býva znížená pri intoxikácii organofosfátmi",],
    options: ["býva zvýšená pri obezite a hyperlipoproteinémii",
       "býva zvýšená pri užívaní barbiturátov",
       "býva znížená pri intoxikácii organofosfátmi",
       "býva zvýšená u pacientov s vírusovou hepatitídou "],
 },
 {
    numb: 76,
    question: "Medzi indikácie vyšetrenia cholínesterázy v sére patrí",
    answer: ["posúdenie funkcie pečene",
       "vyhľadávanie abnormálnych variant cholínesterázy v rámci predoperačného vyšetrenia"],
    options: ["posúdenie funkcie pečene",
       "podozrenie na intoxikáciu barbiturátmi",
       "vyhľadávanie abnormálnych variant cholínesterázy v rámci predoperačného vyšetrenia",
       "podozrenie na diabetes mellitus"],
 },
 {
    numb: 77,
    question: "Cholínesteráza ",
    answer: ["je sekrečný enzým",
      "syntetizuje sa v pečeni "],
    options: ["je indikátorový enzým",
       "je sekrečný enzým",
      " patrí medzi cholestatické enzýmy",
       "syntetizuje sa v pečeni "],
 },
 {
    numb: 78,
    question: "Kyslá fosfatáza",
    answer: ["môže pochádzať z kostného tkaniva",
       "jej aktivitu v sére tvorí viacero izoenzýmov"],
    options: ["môže pochádzať z kostného tkaniva",
       "jej aktivitu v sére tvorí viacero izoenzýmov",
       "je markerom osteoblastov",
       "jej aktivita je vyššia v plazme ako v sére"],
 },
 {
    numb: 79,
    question: "Kyslá fosfatáza",
    answer: ["môže pochádzať z trombocytov",
       "môže pochádzať z prostaty",
       "jej aktivita býva zvýšená pri osteolytických léziach "],
    options: ["môže pochádzať z trombocytov",
       "môže pochádzať z prostaty",
       "je citlivejším ukazovateľom postihnutia prostaty ako PSA",
       "jej aktivita býva zvýšená pri osteolytických léziach "],
 },
 {
    numb: 80,
    question: "Interhumánny kontakt je potrebný pri prenose:",
    answer: [" chlamýdiovej uretritídy"," syfilisu"," kvapavky"," Inäkkého vredu"," šarlachu"],
    options: [" škvrnitého týfusu"," chlamýdiovej uretritídy"," syfilisu"," kvapavky"," Inäkkého vredu","psitakózy"," Q-horúčky","listeriózy"," šarlachu"],
 },
 {
    numb: 81,
    question: "Patogenita predpokladá schopnosť mikroorganizmu:",
    answer: [" množit' sa na povrchu sliznice hostiteľa"," preniknúť do organizmu hostiteľa"," vyvolať ochorenie u vnimavého hostiteľa"," prekonať vrodené obranné mechanizmy hostiteľa"," prenikať do vnímavých buniek hostíteľa a množiť sa v nich "],
    options: [" množit' sa na povrchu sliznice hostiteľa"," preniknúť do organizmu hostiteľa"," vyvolať ochorenie u vnimavého hostiteľa","meniť zioženie normálnej bakteriálnej flóry hostiteľa"," prekonať vrodené obranné mechanizmy hostiteľa"," poškodzovať hostiteľa (štruktúry alebo funkcie organizmu)","vyvolať u hostiteľa špecifickú imunitnú odpoved'"," prenikať do vnímavých buniek hostíteľa a množiť sa v nich ","pretrvávať v organizme aj po navodení špecifickej imunity "],
 },
 {
    numb: 82,
    question: "Vznik ochorenia miiže/môžu podmieňovať:",
    answer: [" imunopatologické mechanizmy vyvolané infikujúcim mikroorganizmom"," bakteriálne exotoxíny"," endotoxíny gramnegatívnych baktérií"," tvorba neuraminidázy a fibrinolyzínu"],
    options: ["lyzozómové enzýmy aeróbnych baktérií"," imunopatologické mechanizmy vyvolané infikujúcim mikroorganizmom"," bakteriálne exotoxíny"," tvorba spór sporulujúcimi mikroorganizmami"," endotoxíny gramnegatívnych baktérií"," tvorba neuraminidázy a fibrinolyzínu"," tvorba bičficov","R-plazmidy baktérií","bakteriocíny baktérií","faktor F baktérií"],
 },
 {
    numb: 83,
    question: "Pre vzťah medzi mikroorganizmom a hostiteľom je charakterlstické:",
    answer: [" pri kolonizácii chýba imunitná odpoved' hostiteľa na mikroorganizmus"," pri infekcii sa u imunokompetentného hostiteľa vytvorí imunitná odpoved' proti mikroorganizmu"," za prejavy ochorenia hostiteľa mďže byt' zodpovedná aj vlastná imunitná odpoved'"," kolonizácia nepatrí medzi formy parazitizmu"," infekcia nemusí byt' sprevádzaná klinickými príznakmi ochorenia "," pň očkovaní vyvoláme infekciu, nie však typické ochorenie "],
    options: [" pri kolonizácii chýba imunitná odpoved' hostiteľa na mikroorganizmus"," pri infekcii musí byt' poškodené tkanivo hostiteľa"," pri infekcii sa u imunokompetentného hostiteľa vytvorí imunitná odpoved' proti mikroorganizmu"," za prejavy ochorenia hostiteľa mďže byt' zodpovedná aj vlastná imunitná odpoved'"," kolonizácia nepatrí medzi formy parazitizmu"," infekcia nemusí byt' sprevádzaná klinickými príznakmi ochorenia ","pri očkovaní využívame kolonizáciu hostiteľa vakcinačným krneň'om"," pň očkovaní vyvoláme infekciu, nie však typické ochorenie "],
 },
 {
    numb: 84,
    question: "Predĺžená kultivácia je potrebná pri dôkaze:",
    answer: [" Mycobacterium tuberculosis"," pôvodcov mykobakterióz"," Brucella spp."," Actinomyces spp."],
    options: ["Sahnonella Typhi"," Mycobacterium tuberculosis"," pôvodcov mykobakterióz"," Brucella spp."," Haemophilus influenzae"," Actinomyces spp.","Streptococcus pyogenes"," Staphylococcus aureus"],
 },
 {
    numb: 85,
    question: "Baktérie identifikujeme na základe:",
    answer: [" tvaru a usporiadania baktérií (koky, paličky, špirály)"," farbiteľnosti podľa Grama"," oxidázového testu"," farbiteľnosti podľa Ziehla-Neelsena"," tvorby spór"," pohyblivosti"],
    options: [" tvaru a usporiadania baktérií (koky, paličky, špirály)"," farbiteľnosti podľa Grama","tvorby a chemického zloženie puzdra"," oxidázového testu","schopnosti rásť na krvnom agare"," farbiteľnosti podľa Ziehla-Neelsena"," tvorby spór"," pohyblivosti"," prítomnosti plazmidov"," tvorby exotoxinov"],
 },
 {
    numb: 86,
    question: "Streptokoky:",
    answer: [" základné delenie je podľa polysacharidovej substancie"," proteín M má antifagocytámu aktivitu"," diagnostickou pôdou je krvný agar"," beta hemolyzíny bežne produkujú streptokoky skupiny A, B, C, F a G"," streptokoky skupiny A sú pravidelne citlivé na penicilín"],
    options: [" všetky streptokoky sa dajú typizovať podľa Lancefieldovej"," základné delenie je podľa polysacharidovej substancie"," proteín M má antifagocytámu aktivitu","proteín M je faktorom virulencie streptokokov skupiny D"," po prekonanom ochorení hladina antistreptolyzínu S stúpa ","pre mikroskopický obraz sú typické zhluky G+ kokov"," diagnostickou pôdou je krvný agar"," beta hemolyzíny bežne produkujú streptokoky skupiny A, B, C, F a G"," streptokoky skupiny A sú pravidelne citlivé na penicilín"],
 },
 {
    numb: 87,
    question: "Medzi faktory virulencie ►treptococcus pyogenes patria:",
    answer: [" hyaluronidáza"," streptokináza"," deoxyribonukleáza B"," erytrogénne toxíny"],
    options: [" hyaluronidáza","zhiukovací faktor"," streptokináza"," deoxyribonukleáza B"," erytrogénne toxíny"," kord faktor","lipopolysacharid","enterotoxin"," pyocyanín"],
 },
 {
    numb: 88,
    question: "Pre hemolytické streptokoky nepatriace do skupiny A platí:",
    answer: [" skupina C nemá proteín M"," enterokoky môžu spôsobovať aj beta hemolýzu"," skupiny C a G môžu produkovať streptolyzín 0"," testom CAMP dokážeme exoprodukt potencujúci hemolyzín (beta toxin) S.aureus"," S. agalactiae môže kolonizovať vaginálnu sliznicu"],
    options: ["S. agalactiae nie je patogénny pre človeka"," skupina C nemá proteín M"," môžu byt' podobne ako skupina A pôvodcami reumatickej horáčky"," enterokoky môžu spôsobovať aj beta hemolýzu"," skupiny C a G môžu produkovať streptolyzín 0"," testom CAMP dokážeme exoprodukt potencujúci hemolyzín (beta toxin) S.aureus"," S. agalactiae môže kolonizovať vaginálnu sliznicu"," infekcia S. agalactiae sa prejaví zvýšením titra ASLO","skupina G je pôvodcom postreptokokovej glomerulonefritídy","faktorom virulencie je proteín A"],
 },
 {
    numb: 89,
    question: "Príčinou opakovaných ochorení vyvolaných Streptococcus pyogenes je: ",
    answer: [" protektívny proteín M má veľa antigénnych typov"," infekcia inýrn typom S.pyogenes, než voči ktorému má hostiteľ protilátky "," pri opakovaní šarlachu antigénna róznorodosť erytrogénneho toxinu"],
    options: [" typicky epidemický výskyt infekcil v populácii"," protektívny antigén nie je dostatočne imunogénny","postinfekčná imunita je krátkodobá"," protektívny proteín M má veľa antigénnych typov","protektívny proteĺn T má viacero antigénnych typov"," infekcia inýrn typom S.pyogenes, než voči ktorému má hostiteľ protilátky ","neschopnosť organizmu vytvoriť protilátky proti hemolyzinu S ","nedostatočná tvorba protilátok proti streptolyzinu 0"," pri opakovaní šarlachu antigénna róznorodosť erytrogénneho toxinu"],
 },
 {
    numb: 90,
    question: "Poststreptokokové ochorenia:",
    answer: [" diagnosticky sa opierame o vyšetrenie hladín ASLO a anti-DNázy"," príčinou sú krížovo reagujúce protilátky, ktoré vznikajú počas infekcie S. pyogenes"," autoĺmúnna reakcia je indukovaná antigénmi S. pyogenes"],
    options: ["sú bezprostredným pokračovaním streptokokovej inťekcie"," reumatická horúčka vzniká po faryngeálnej infekcii S. agalactiae","príčinou je precitlivenosť I. typu na antigény S. pyogenes","vyskytujú sa len po manifestovanej in.fekcii so šarlachovou vyrážlou"," diagnosticky sa opierame o vyšetrenie hladín ASLO a anti-DNázy"," u chorého vyšetríme hladinu antistreptolyzinu S v sére ","postihnuté sú výlučne obličky a srdce"," príčinou sú krížovo reagujúce protilátky, ktoré vznikajú počas infekcie S. pyogenes"," autoĺmúnna reakcia je indukovaná antigénmi S. pyogenes"],
 },
 {
    numb: 91,
    question: "Do ktorej skupiny patrí a ako môžeme určiť Streptococcus agalactiae:",
    answer: [" B, test CAMP je pozitívny "," B, dókaz skupinového antigénu latexovou aglutináciou"," B, bacitracínový test je negatívny"],
    options: [" B, test CAMP je pozitívny ","B, Neufeldovým testom ","A, test CAMP je pozitívny"," B, dókaz skupinového antigénu latexovou aglutináciou"," A, Elekov test je pozitívny"," B, bacitracínový test je negatívny"," A, bacitracinový test je pozitívny"],
 },
 {
    numb: 92,
    question: "Na ziklade pozitivity testu CAMP určujeme:",
    answer: [" Streptococcus agalactiae"," produkciu faktora zosilujikeho hemolýzu Staphylococcus aureus "," beta-hemolytické streptokoky skupiny B"],
    options: [" Arcanobacteruim haemolyficum"," Streptococcus agalactiae"," produkciu faktora zosilujikeho hemolýzu Staphylococcus aureus ","schopnosť kmehov Staphylococcus aureus tvoriť beta-laktamázu"," beta-hemolytické streptokoky skupiny B"," beta-hemolytické streptokoky skupiny D"," Staphylococcus epidermidis"],
 },
 {
    numb: 93,
    question: "Titer antistreptolyzínu 0 využívame pri diagnostike: ",
    answer: [" sterilných následkov streptokokových infekcil"," poststreptokokovej chorey minor"," reumatickej horúčky"," akútnej glomerulonefi-itídy"," poststreptokokovej myokarditítidy"],
    options: ["erysipeloidu"," sterilných následkov streptokokových infekcil"," poststreptokokovej chorey minor"," reumatickej horúčky","záškrtu"," akútnej glomerulonefi-itídy","stafylokokovej enterokolitídy"," poststreptokokovej myokarditítidy","epidemickej meningitídy"],
 },
 {
    numb: 94,
    question: "Poststreptokokové ochorenia diagnostikujeme pomocou:",
    answer: [" stanovenia antistreptolyzínu O"," zisťovanim sedimentácie (pornocné vyšetrenie)"," stanovenia antistreptodornázy (antideoxyribonukleázy B)"," stanovenia hladiny CRP (C-reaktívny proteín, nešpecifický ukazovater zápalu)"],
    options: [" stanovenia antistreptolyzínu O"," stanovenia antistreptolyzinu S"," stanovenia voľnej koagulázy"," zisťovanim sedimentácie (pornocné vyšetrenie)"," stanovenia antistreptodornázy (antideoxyribonukleázy B)"," bacitracínového testu"," stanovenia hladiny CRP (C-reaktívny proteín, nešpecifický ukazovater zápalu)","stanovenia protilátok proti erytrogénnemu toxínu"],
 },
 {
    numb: 95,
    question: "Za ešte normálnu hodnotu ASLO u deti by ste považovali hladinu:",
    answer: [" lOj "," 128j"," 196j"," 160j "],
    options: [" lOj "," 128j"," 196j"," 160j ","900j"," 375j ","600j ","500j ","380j"],
 },
 {
    numb: 96,
    question: "Pri diagnostike reumatickej horúčky odoberáme na vyšetrenie:",
    answer: [" krv na sérologické vyšetrenie antistreptolyzínu O"," krv na sérologické vyšetrenie antistreptodomázy (antideoxyribonukleázy B)"," krv na stanovenie hladiny CRP"],
    options: ["výter z tonzíl na dôkaz prítomnosti Staphylocaccus aureus"," krv na hemokultiváciu"," krv na sérologické vyšetrenie antistreptolyzínu O"," krv na sérologické vyšetrenie antistreptodomázy (antideoxyribonukleázy B)","výter z laryngu na dôkaz Corynebacterium diphtheriae","spútum na kvantitatívne vyšetrenie"," punktáty z postihnutých klbov","stolicu na dôkaz Yersinia enterocolitica"," krv na stanovenie hladiny CRP","krv na stanovenie hladiny antistrepto1yzínu S"],
 },
 {
    numb: 97,
    question: "Streptococcus pneumoniae:",
    answer: [" popri pneumónii spôsobuje otitídy a meningitídy u detí"," základným faktorom virulencie je polysacharidové puzdro"," protilátky proti puzdrovým antigénorn sú protektívne"," u staršich ľudi môže častejšie vyvolať pneumóniu"," puzdro má antifagocytárny účinok"," prameňom infekcie je vždy človek"," k faktorom virulencie patrí schopnosť štiepiť povrchový IgA"],
    options: [" popri pneumónii spôsobuje otitídy a meningitídy u detí"," základným faktorom virulencie je polysacharidové puzdro"," produkuje neurotoxický proteín"," protilátky proti puzdrovým antigénorn sú protektívne"," u staršich ľudi môže častejšie vyvolať pneumóniu"," puzdro má antifagocytárny účinok"," prameňom infekcie je vždy človek"," k faktorom virulencie patrí schopnosť štiepiť povrchový IgA","všetky kmene sú citlivé na penicilín","prežíva v prostredí vd'aka odolným spóram"],
 },
 {
    numb: 98,
    question: "Identifikáciu Staphylococcus aureus robíme:",
    answer: [" dókazom produkcie plazmakoagulázy"," dôkazom zhlukovacieho faktora","  dókazom tvorby DN-ázy","  dókazom tvorby hyaluronidázy","  dókazom tvorby hemolyzínov na krvnom agare","  dôkazom proteínu A"],
    options: [" Elekovou metódou"," dókazom produkcie plazmakoagulázy"," dôkazom zhlukovacieho faktora","  simultánnym dôkazom proteínu A a zhlukovacieho faktora latexovou aglutináciou ","stanovením CRP v sére pacienta","dôkazom tvorby ASLO pri experimentálnej infekcii","  dókazom tvorby DN-ázy","  dókazom tvorby hyaluronidázy","  dókazom tvorby hemolyzínov na krvnom agare","  dôkazom proteínu A"],
 },
 {
    numb: 99,
    question: "Staphylococcus aureus:",
    answer: [" môže produkovať termostabilné enterotoxíny"," pri infekcii sa typicky tvoria abscesy"," patrí medzi pôvodcov nozokomiálnych nákaz"," často sa vyskytuje v nosohltane zdravých nosičov","  môže spósobiť postantibiotickú enterokolitídu","  v terapii infekcii spôsobených MRSA sú z betalaktámov účinné len cefalosporiny 5. generácie"],
    options: [" môže produkovať termostabilné enterotoxíny","faktorom virulencie je endotoxin"," pri infekcii sa typicky tvoria abscesy"," patrí medzi pôvodcov nozokomiálnych nákaz"," často sa vyskytuje v nosohltane zdravých nosičov","je štandardne citiivý na peniciiin","  je pôvodcom autoimúnnej myokardititídy","  môže spósobiť postantibiotickú enterokolitídu","  v terapii infekcii spôsobených MRSA sú z betalaktámov účinné len cefalosporiny 5. generácie"],
 },
 {
    numb: 100,
    question: "Corynebacterium diphthe•iae:",
    answer: ["  aktívna imunizácia spočíva v navodení antitoxickej imunity ","  toxín Účinkuje inhibiciou proteosyntézy v cieľovej bunke","  pri dôkaze toxigenity používame imunodifáziu (Elekov test) ","  účinok toxinu na bunku je nekrotický","  toxín pôsobí najmä neuro-, nefto- a kardiotoxicky"],
    options: ["izolácia mikroorganizmu z materiálu vždy potvrdzuje diagnázu diftérie","  aktívna imunizácia spočíva v navodení antitoxickej imunity ","exotoxín sa uvoľňuje do okolia až po rozpade baktérie","  toxín Účinkuje inhibiciou proteosyntézy v cieľovej bunke","  pri dôkaze toxigenity používame imunodifáziu (Elekov test) ","invazivita je podmienená lyzogénnou konverziou beta-fágom ","letálny toxín pósobi výlučne lokálne (v mieste zápalu)","  účinok toxinu na bunku je nekrotický","  toxín pôsobí najmä neuro-, nefto- a kardiotoxicky"],
 },
 {
    numb: 101,
    question: "Listeria monocytogenes:",
    answer: ["  mikroorganizmus prechádza placentou a poškodzuje plod ","  faktorom virulencie je listeriolyzín","  listéria je grampozitívna palička","  patrí medzi póvodcov zoonóz","   rastie aj pri teplote 4 °C","  patrí medzi fakultatívne intracelulárne baktérie"],
    options: ["  faktorom virulencie je puzdro s antifagocytárnym úč'inkom","  mikroorganizmus prechádza placentou a poškodzuje plod ","prekonanie ochorenia zanecháva doživotnú imunitu","  faktorom virulencie je listeriolyzín","  listéria je grampozitívna palička","  patrí medzi póvodcov zoonóz","prameňom nákazy je najčastejšie človek","   rastie aj pri teplote 4 °C","  mikrób tvorí centrálne uloženú spáru","  patrí medzi fakultatívne intracelulárne baktérie"],
 },
 {
    numb: 102,
    question: "Erysipelothrbc rhusiopathiae:",
    answer: [" j e fakultatívne anaeróbna grampozitívna palička, ktorá netvorí spóry","  patrí medzi pôvodcov zoonóz","  najčastejším prameňom nálcazy je ošipaná","  v klinickom obraze prevažujú kožné lézie a miestne artritídy","  profesionálna nákaza sa prenáša kontaktom so zvieraťom"," mikroorganizmus je citlivý na penicilín, cefalosporíny a klindamycín"," difúzny charakter kožných léziĺ podmieňuje neuraminidáza"],
    options: [" j e fakultatívne anaeróbna grampozitívna palička, ktorá netvorí spóry","  patrí medzi pôvodcov zoonóz","  najčastejším prameňom nálcazy je ošipaná","  v klinickom obraze prevažujú kožné lézie a miestne artritídy","  profesionálna nákaza sa prenáša kontaktom so zvieraťom","  prekonanie in.fekcie zanecháva trvalú imunitu"," často vyvoláva atypickú pneumóniu"," mikroorganizmus je citlivý na penicilín, cefalosporíny a klindamycín"," základná diagnostika je nepriama (sérologická)"," difúzny charakter kožných léziĺ podmieňuje neuraminidáza"],
 },
 {
    numb: 103,
    question: "Haemophilus influenzae vyvoláva obvylkle:",
    answer: [" bakteriálne infekcie horných dýchacich orgánov"," meningitídy"," otitídy"," osteomyelitídy detí"," superinfekcie dýchacich ciest"," infekcie u detí"],
    options: [" chripku"," bakteriálne infekcie horných dýchacich orgánov"," meningitídy","mäkký vred"," otitídy"," osteomyelitídy detí","uretritídy"," reumatickú horúčku"," superinfekcie dýchacich ciest"," infekcie u detí"],
 },
 {
    numb: 104,
    question: "Haemophilus:",
    answer: [" H. influenzae vyvoláva infekcie horných ciest dýchacich"," k faktorom virulencie patrí puzdro"," Hinfluenzae poškodzuje riasinkový epitel dýchacich ciest"," mikroorganizmus štiepi slizničný IgA"," infekcia H.ducreyi patrí medzi venerické nákazy "],
    options: ["je nepohyblivá pleomorfná grampozitívna baktéria ","dobre rastie na krvnom agare"," H. influenzae vyvoláva infekcie horných ciest dýchacich"," k faktorom virulencie patrí puzdro"," Hinfluenzae poškodzuje riasinkový epitel dýchacich ciest"," mikroorganizmus štiepi slizničný IgA"," spôsobuje meningitídy s epidemickým výskytom"," infekcia H.ducreyi patrí medzi venerické nákazy ","H.ducreyi je póvodcom pohlavne prenosnej uretritídy"],
 },
 {
    numb: 105,
    question: "N. gonorrhoeae a N. meningitidis rastie na:",
    answer: [" čokoládovom agare"," GC agare"," špeciálnych kultivačných pôdach (sú rastovo náročné)"],
    options: [" Endovej pôde"," čokoládovom agare"," tioglykolátovej pôde"," LA5wensteinovej pôde"," GC agare"," Sabouraudovom agare"," dezoxycholátcitrátovej pôde"," špeciálnych kultivačných pôdach (sú rastovo náročné)"],
 },
 {
    numb: 106,
    question: "Pri podozrení na kvapavku a jej komplikácie u ženy odoberáme:",
    answer: [" punktát zo zápalovo zmeneného kíbu pri diseminovanej forme"," krv na hemokultiváciu pri diseminovanej forme"," výter z cervixu"," výter z uretry"," materiál z miesta infekcie do transportného média (napr. Stuartovho)"],
    options: [" punktát zo zápalovo zmeneného kíbu pri diseminovanej forme"," excízie z tkaniva"," krv na hemokultiváciu pri diseminovanej forme","rutinne krv na dókaz špecifických protilátok"," výter z cervixu"," výter z uretry","moč suprapubickou punkciou"," materiál z miesta infekcie do transportného média (napr. Stuartovho)"],
 },
 {
    numb: 107,
    question: "Neisseria gonorrhoeae:",
    answer: [" prirodzeným hostiteľom je človek"," mikroorganizmus poškodzuje epitelové bunky sliznice "," mikroskopické vyšetrenie má diagnostický význam"," kultivačne je vel'mi náročná"," lepšie rastie pri zvýšenej tenzii CO2"," izoláciu povinne hlásime (venerické ochorenie)"],
    options: [" prirodzeným hostiteľom je človek","bežne sa prenáša aj kontaminovanými predmetmi"," mikroorganizmus poškodzuje epitelové bunky sliznice ","prekonaníe ochorenia zanecháva spoľahlivú dlhodobú imunitu"," mikroskopické vyšetrenie má diagnostický význam","je vždy citlivá na penicilín"," kultivačne je vel'mi náročná"," lepšie rastie pri zvýšenej tenzii CO2"," izoláciu povinne hlásime (venerické ochorenie)"],
 },
 {
    numb: 108,
    question: "Neisseria gonorrhoeae:",
    answer: [" produkuje proteázy, ktoré štiepia slizničný IgA"," faktorom virulencie je endotoxin"," pre antigénovú variabilitu nie je vylúčená reinfekcia antigénovo-od1išným kmeňom "],
    options: ["faktorom virulencie sú fimbrie"," produkuje proteázy, ktoré štiepia slizničný IgA","faktorom virulencie je proteín A"," faktorom virulencie je endotoxin"," pred fagocytózou ju chráni slizová vrstva"," za adhezivitu zodpovedá kyselina teichoová v bunkovej stene"," pre antigénovú variabilitu nie je vylúčená reinfekcia antigénovo-od1išným kmeňom "," ochorenie potvrdíme dôkazom protilátok testom ELISA"],
 },
 {
    numb: 109,
    question: "Neisseria meningitidis:",
    answer: [" faktorom virulencie je polysacharidové puzdro"," za toxický účinok zodpovedá lipooligosacharid"," popri epidemickom je možný aj sporadický výskyt meningitídy"," na vyšetrenie odoberáme likvor, krv a nazofaryngeálny výter "," antigény pôvodcu dokážeme priamo v likvore latexovou aglutináciou"],
    options: [" faktorom virulencie je polysacharidové puzdro"," za toxický účinok zodpovedá lipooligosacharid","tvorí membranotoxický proteín"," popri epidemickom je možný aj sporadický výskyt meningitídy"," na vyšetrenie odoberáme likvor, krv a nazofaryngeálny výter ","mikroskopické vyšetrenie nemá diagnostický význam ","nazofaryngeálne nosičstvo nie je epidemiologicky významné"," antigény pôvodcu dokážeme priamo v likvore latexovou aglutináciou"," pri meningitíde v likvore prev 'ažujú mononukleárne leukocyty ","meningitída má aseptický charakter"],
 },
 {
    numb: 110,
    question: "Enterobaktérie:",
    answer: [" Shigella dysenžeriae sérotyp 1 tvorí exotoxin"," „Vi\" antigén patrí k mikropuzdrovým antigénom"," pri, sérotypizácii sa v praxi využíva aglutinácia "],
    options: [" salmonelózy sú vždy generalizovaným ochorením","typhus abdominalis patrí k zoonózam"," Shigella dysenžeriae sérotyp 1 tvorí exotoxin","0 antigén patrí k puzdrovým antigénom bunky"," „Vi\" antigén patrí k mikropuzdrovým antigénom"," shigely sú potenciálne patogénne"," všetky druhy patria k normálnej bakteriálnej flóre čreva ","faktorom viru1encie je výlučne enterotoxin"," pri, sérotypizácii sa v praxi využíva aglutinácia ","spôsobujú výlučne ochorenia gastrointestinálneho traktu"],
 },
 {
    numb: 111,
    question: "Escherichia coli:",
    answer: [" môže vyvolať novorodenecké meningitídy (najčastejšie typ Kl)"," enterotoxiny, kolicíny a filnbrie sú často kódované plazmidmi"," niektoré kmene tvoria hemolyzín"," enteroinvazívne E.cofi móžu vyvolať krvavé hnačky"," enteropatogénne kmene vyvolávajú nozokomiálne infekcie u malých detí"," nepatrí k normálnej flóre čreva u novorodenca"],
    options: [" enteropatogénne E. coli prenikajú stenou črevnej sliznice"," môže vyvolať novorodenecké meningitídy (najčastejšie typ Kl)"," enterotoxiny, kolicíny a filnbrie sú často kódované plazmidmi"," niektoré kmene tvoria hemolyzín"," enteropatogénne E. coli tvoria enterotoxíny"," enteroinvazívne E.cofi móžu vyvolať krvavé hnačky"," enteropatogénne kmene vyvolávajú nozokomiálne infekcie u malých detí"," nepatrí k normálnej flóre čreva u novorodenca","faktorom virulencie je hyaluronidáza","pri ochorení odoberáme krv na sérologické vyš'etrenie protilátok"],
 },
 {
    numb: 112,
    question: "Prameňom infekcie pri brušnom týfuse je:",
    answer: [" chorý človek"," bacilonosič"],
    options: [" zviera"," chorý človek"," bacilonosič","voda kontaminovaná rnočom drobných hlodavcov"," ektoparazity hlodavcov"," potraviny","vajféka","výkaly domácich zvierat"],
 },
 {
    numb: 113,
    question: "Salmonelové infekcie — pôvodcovia a prenos:",
    answer: [" S. Enteritidis, požitím kontaminovanej potravy"," S. Typhi, S. Paratyphi A,B,C, vodou"," S. Enteritidis, S. Typhimurium, vodou"," primárne zoopatogénne salmonely, potravinami, vodou"," primárne zoopatogénne salmonely, fekálno-orálne, potravinami a vodou "," primárne zoopatogénne salmonely, vajíčkami infikovanej hydiny"," primárne zoopatogénne salmonely, mliekom infikovaných zvierat"],
    options: [" S. Enteritidis, požitím kontaminovanej potravy"," S. Typhi, S. Paratyphi A,B,C, vodou"," S. Enteritidis, S. Typhimurium, vodou"," primárne zoopatogénne salmonely, potravinami, vodou"," primárne zoopatogénne salmonely, fekálno-orálne, potravinami a vodou ","S. Enteritidis, kvapôčkovou infekciou"," primárne zoopatogénne salmonely, vajíčkami infikovanej hydiny"," primárne zoopatogénne salmonely, mliekom infikovaných zvierat"," Salmonella Paratyphi, transplacentálne"],
 },
 {
    numb: 114,
    question: "Yersinia enterocolitica môže spôsobiť ochorenia:",
    answer: [" hnačky"," enterokolitídu s apendicitíde podobnou mezenteriálnou lymfadenitídou"," sepsu"," erythema nodosum u dospelých"," reaktívnu polyartritídu"],
    options: [" hnačky"," enterokolitídu s apendicitíde podobnou mezenteriálnou lymfadenitídou"," sepsu"," erythema nodosum u dospelých"," reaktívnu polyartritídu","sinusitídu","impetigo"," orchitídu"],
 },
 {
    numb: 115,
    question: "Pseudomonas aeruginosa:",
    answer: [" je potenciálne patogénna baktéria"," často vyvoláva pneumónie u pacientov s cystickou fibrózou"," môže vyvolať postantibiotickú enterokolitídu"," móže sa vyskytovať v bakteriálnej flóre zdravého človeka"," faktormi virulencie sú proteázy, exotoxiny a sliz"," patrí k pôvodcom nozokomiálnych nákaz"," produkuje bakteriocíny a pigmenty"],
    options: [" je potenciálne patogénna baktéria"," často vyvoláva pneumónie u pacientov s cystickou fibrózou"," môže vyvolať postantibiotickú enterokolitídu"," móže sa vyskytovať v bakteriálnej flóre zdravého človeka"," faktormi virulencie sú proteázy, exotoxiny a sliz","niektoré kmene bývajú citlivé na penicilín"," nemocničné kmene sú dobre citlivé na antibiotiká"," patrí k pôvodcom nozokomiálnych nákaz"," produkuje bakteriocíny a pigmenty","patrí medzi fakultatívne anaeróbne gramnegatívne baktérie"],
 },
 {
    numb: 116,
    question: "Hnačkové ochorenia môžu spôsobiť tieto baktérie:",
    answer: [" Clostridium perftingens "," Bacillus cereus"," Staphylococcus aureus"," Shigella sonnei, Shigella boydii"," Escherichia coli (niektoré kmene)"," Yersinia enterocolitica "," Campylobacter jejuni"],
    options: [" Clostridium perftingens ","Streptococcus pyogenes"," Bacillus cereus","Enterobacter spp."," Staphylococcus aureus"," Shigella sonnei, Shigella boydii"," Escherichia coli (niektoré kmene)"," Yersinia enterocolitica ","Mycoplasma spp."," Campylobacter jejuni"],
 },
 {
    numb: 117,
    question: "Svoj enteroinvazívny účinok v čreve uplatiluje:",
    answer: [" Yersinia enterocolitica"," Shigella spp."," Salmonella enteritidis"," E. coli (enteroinvazívne) "],
    options: ["Staphylococcus aureus ","Neisseria gonorrhoeae"," Yersinia enterocolitica"," Shigella spp."," Bacillus cereus"," Salmonella enteritidis"," E. coli (enteroinvazívne) "," enterotoxigénne E. coli","Vibrio cholerae"],
 },
 {
    numb: 118,
    question: "Bordetella pertussis:",
    answer: [" na aktívnu imunizáciu sa používa acelulárna subjednotková vakeína"," výter z nosohltanu očkujeme na Bordetovu-Gengouovu pôdu"," má afinitu k riasinkovému epitelu dýchacích ciest"," toxin paralyzuje pohyb cílií epitelu dýchacích ciest"," medzi faktory virulencie patrí pertusový toxín"," je malý opuzdrený gramnegatívny kokobacil"],
    options: [" na aktívnu imunizáciu sa používa acelulárna subjednotková vakeína"," pri vyšetrení odoberáme krv na hemokultiváciu"," výter z nosohltanu očkujeme na Bordetovu-Gengouovu pôdu"," ochorenie a vakcinácia zanechávajú iba krátkodobú imunitu"," má afinitu k riasinkovému epitelu dýchacích ciest","najčastejším prameňom nákazy je infikované zviera"," toxin paralyzuje pohyb cílií epitelu dýchacích ciest"," medzi faktory virulencie patrí pertusový toxín"," vyvoláva nekrotizujúci zápal laryngu"," je malý opuzdrený gramnegatívny kokobacil"],
 },
 {
    numb: 119,
    question: "Yersinia pestis:",
    answer: [" je nesporulujúca, nepohyblivá gramnegatívna palička"," je pôvodcom lesného aj urbánneho moru"," faktorom virulencie sú povrchové štruktúry, blokujúce fagoeytózu"," rezervoárom pri mestskom more je potkan"," najčastejším vektorom prenosu je blcha"],
    options: [" je nesporulujúca, nepohyblivá gramnegatívna palička"," je rastovo náročná a na krvnom agare nevyrastie"," je pôvodcom lesného aj urbánneho moru"," faktorom virulencie sú povrchové štruktúry, blokujúce fagoeytózu"," rezervoárom pri mestskom more je potkan","najčastejším vektorom je kliešť"," najčastejším vektorom prenosu je blcha","pneumonická forma moru je neinfekčná"," ochorenie sa prenáša výlučne infikovanou blchou"," sa pravidelne prenáša pri pohlavnom styku"],
 },
 {
    numb: 120,
    question: "Francisella tularensis:",
    answer: [" je to drobný gramnegatívny kokobacil"," prírodným rezervoárom je zajac, králik a drobné hlodavce "," prekonanie ochorenia zanecháva doživotnú imunitu"," dôkaz protilátok patrí k bežným diagnostickým metódam"," ochorenie patrí medzi zoonózy"," dlhodobé prežívanie v makrofágoch vedie ku chronickej infekcii"],
    options: [" je to drobný gramnegatívny kokobacil"," prírodným rezervoárom je zajac, králik a drobné hlodavce ","ako extracelulárna baktéria vyvoláva pyogénne infekcie ","prenos ektoparazitmi alebo aerosólom nie je možný"," prekonanie ochorenia zanecháva doživotnú imunitu"," dôkaz protilátok patrí k bežným diagnostickým metódam"," ochorenie patrí medzi zoonózy"," dlhodobé prežívanie v makrofágoch vedie ku chronickej infekcii"," ochorenie vyvoláva len u ľudí so zníženou imunitou"],
 },
 {
    numb: 121,
    question: "Pasteurella multocida:",
    answer: [" je to drobný gramnegatívny kokobacil"," faktorom virulencie je lipopolysacharid"," vyskytuje sa v normálnej fióre dýchacích ciest niektorých zvierat"," prameriom nákazy rnôže byť aj choré zviera"," diagnostikuje sa kultivačne"," najčastejšie sa prenáša pohryzilutím zvieraťom (infikuje ranu)"," u človeka móže vyvolať aj závažné systémové infekcie"],
    options: [" je to drobný gramnegatívny kokobacil"," faktorom virulencie je tvorba slizu"," faktorom virulencie je lipopolysacharid"," vyskytuje sa v normálnej fióre dýchacích ciest niektorých zvierat"," prameriom nákazy rnôže byť aj choré zviera","prirodným rezervoárom sú ektoparazity hlodavcov","dlhodobo môže prežívať v prostredí"," diagnostikuje sa kultivačne"," najčastejšie sa prenáša pohryzilutím zvieraťom (infikuje ranu)"," u človeka móže vyvolať aj závažné systémové infekcie"],
 },
 {
    numb: 122,
    question: "Brucella spp. a brucelóza:",
    answer: [" ochorenie patrí medzi zoonózy"," základom laboratómej diagnostiky je kultivačn 'y däkaz"," faktorom virulencie je lipopolysacharid"," patrí k rastovo náročným baktériám"," je schopná rásť intracelulárne a vyvolať granulomatózny zápal "," bránou vstupu sú najčastejšie kožné odreniny"],
    options: [" ochorenie patrí medzi zoonózy"," základom laboratómej diagnostiky je kultivačn 'y däkaz"," faktorom virulencie je lipopolysacharid"," mikroorganizmy majú afinitu k nervovému tkanivu"," primokultivácia sa robí za anaeróbnych podmienok"," patrí k rastovo náročným baktériám"," je schopná rásť intracelulárne a vyvolať granulomatózny zápal ","pri infekcii nedochádza k diseminácii do parenchymatóznych orgánov"," bránou vstupu sú najčastejšie kožné odreniny","rezervoárom Brucella abortus sú netopiere"],
 },
 {
    numb: 123,
    question: "Ktoré z uvedených baktérií sa pravidelne množia aj intracelulárne:",
    answer: [" Francisella tularerals "," Brucella melitensis"," lýlycobacterium leprae"," Mycobacterium tuberculosis"," Listeria monocytogenes"," Mycobacterium bovis"],
    options: [" Escherichia coli"," Francisella tularerals ","Neisseria sicca"," Brucella melitensis"," lýlycobacterium leprae"," Mycobacterium tuberculosis"," Streptococcus pyogenes ","Streptococcus mutans"," Listeria monocytogenes"," Mycobacterium bovis"],
 },
 {
    numb: 124,
    question: "Aktívnu tuberkulózu u pacienta v praxi potvrdime:",
    answer: [" tuberkulínovým kožným testom"," mikroskopicky (Ziehlovo-Neelsenovo farbenie)"," mikroskopicky (fluorescenčným farbením)","  kultiváciou na Mwensteinovej-Jensenovej pôde ","  dókazom nukleovej kyseliny pôvodcu vo vzorke"],
    options: [" epidemiologicky vyšetrením rodinných príslušníkov"," tuberkulínovým kožným testom","mikroskopicky (Gramovo farbenie)"," mikroskopicky (Ziehlovo-Neelsenovo farbenie)"," mikroskopicky (fluorescenčným farbením)","  mikroskopicky (Burriho metódou)         0","  kultiváciou na Mwensteinovej-Jensenovej pôde ","  kultiváciou na Wilsonovej-Blairovej pôde","  dókazom nukleovej kyseliny pôvodcu vo vzorke","  dôkazom špecifických protilátok"],
 },
 {
    numb: 125,
    question: "Na tvorbe tuberkulózneho granulómu sa podieľajú najmä: ",
    answer: ["  fibroblasty","  makrofágy","  epiteloidne transformované mononuldeárne bunky ","  T-lymfocyty"],
    options: ["  granu1ocyty","  eozinofilné leukocyty","  fibroblasty","  makrofágy","  epiteloidne transformované mononuldeárne bunky ","  B-lymfocyty","  myocyty","megakaryocyty","  T-lymfocyty"],
 },
 {
    numb: 126,
    question: "Tuberkulínová sláška (Mantoux): ",
    answer: ["  hodnoti sa po 48 — 72 hodinách","  test sa hodnotí podľa veľkosti indurácie ","  hodnotenie sa overuje palpačne","  odráža precitlivenosť oneskoreného typu na proteínové antigény","  normálny priemer indurácie je 6 — 18 mm u dospelých"],
    options: ["hodnotí sa po 15 minútach od aplikácie","  hodnoti sa po 48 — 72 hodinách","  negatívny výsledok testu potvrdzuje imunitu proti tuberkulóze","  test sa hodnotí podľa veľkosti indurácie ","rozhoduje veľkosť erytému v mieste aplikácie","  hodnotenie sa overuje palpačne","  odráža precitlivenosť oneskoreného typu na proteínové antigény","  potvrdzuje protilátkovú imuni-tu proti tuberkulóze","  normálny priemer indurácie je 6 — 18 mm u dospelých","antigén sa aplikuje epikutánne"],
 },
 {
    numb: 127,
    question: "Pôvodeami mykobakterlóz môžu byť: ",
    answer: ["  Mycobacterium kansasii","  llilycobacterium marinum","  Mycobacterium a-vium","  Mycobacterium intracellulare","  Mycobacterium fortuitum"],
    options: ["Mycobacterium leprae","Mycobacterium bovis (BCG kmeň) ","Mycobacterium bovis","  Mycobacterium kansasii","  llilycobacterium marinum","  Mycobacterium tuberculosis","  Mycobacterium a-vium","  Mycobacterium intracellulare","  Mycobacterium fortuitum"],
 },
 {
    numb: 128,
    question: "Na imunitnej odpovedi proti tuberkulóze sa podieľajú najmä:",
    answer: ["  aktivované makrofágy","  T-lymfocyty produkciou lymfokínov"],
    options: ["  aktivované makrofágy","  T-lymfocyty produkciou lymfokínov","  eozinofilné leukocyty","neutrofilné leukocyty"," komplementový systém aktivovaný alternatívnou cestou"," NK-bunky"," špecifické protilátky"," neaktivované makrofágy"],
 },
 {
    numb: 129,
    question: "Rod Mycobacterium:",
    answer: [" BCG vakcína obsahuje atenuovaný kmeň M bovis"," M tuberculosis a M bovis rozlíšime podľa rastu na pevnej pôde"," M aviumĺ.~.~ intracellulare postihuje často pacientov s AIDS "," generačná doba M tuberculosis je až 18 — 24 hodín"],
    options: [" mikroorganizmy sú len acidorezistentné, nie sú alkalirezistentné"," BCG vakcína obsahuje atenuovaný kmeň M bovis"," všetky druhy rastú vermi pomaly"," druh M bovis je pre človeka nepatogénny"," M tuberculosis postihuje výlučne lymfatický systém a kostnú dreň"," M tuberculosis a M bovis rozlíšime podľa rastu na pevnej pôde"," M aviumĺ.~.~ intracellulare postihuje často pacientov s AIDS "," M tuberculosis na pevných pôdach vyrastá do 6 dni"," generačná doba M tuberculosis je až 18 — 24 hodín"],
 },
 {
    numb: 130,
    question: "Mykolové kyseliny v bunke Mycobacterium tuberculosis:",
    answer: [" podmieňujú acidorezistenciu mikroorganizmu"," chránia milu.00rganizmus pred účinkom enzýmov, kyselín a Iňhov"," indukujú granulomatóznu zápalovú reakciu"," podmieňujú hydrofóbnosť bunkovej steny"," chránia pri fagocytóze mikrób pred lyzozómovými enzýmarni"],
    options: [" podmieňujú acidorezistenciu mikroorganizmu"," chránia milu.00rganizmus pred účinkom enzýmov, kyselín a Iňhov"," indukujú granulomatóznu zápalovú reakciu"," podmieňujú hydrofóbnosť bunkovej steny"," aktivujú komplement alternatívnou cestou"," chránia pri fagocytóze mikrób pred lyzozómovými enzýmarni","indukujú tvorbu reagínových protilátok u pacienta"," používame ich ako antigén pri tuberkulínovom teste"],
 },
 {
    numb: 131,
    question: "Actinomyces spp.:",
    answer: [" mikroorganizmy nesporulujú"," pre aktinomykózu je typický výskyt drúz v hnise"," pri primokultiváci je potrebná anaeróbna atmosféra"," bránou vstupu je najčastejšie poranená sliznica"," mikroskopické vyšetrenie hnisu má diagnostický význam"," charakteristickým obrazom ochorenia je purulentný zápal a tvorba granulómu "],
    options: [" mikroorganizmy nesporulujú"," pre aktinomykózu je typický výskyt drúz v hnise"," pri primokultiváci je potrebná anaeróbna atmosféra"," A. israelii a A. odontolyticus sa izoluje z dutiny ústnej len u chorých"," bránou vstupu je najčastejšie poranená sliznica"," faktorom virulencie je termolabilný leukocidín"," mikroskopické vyšetrenie hnisu má diagnostický význam"," cervikofaciálna forma je dôsledkom hematogénneho rozsevu"," charakteristickým obrazom ochorenia je purulentný zápal a tvorba granulómu ","pri ochorení je infekcia najčastejšie exogénneho pôvodu"],
 },
 {
    numb: 132,
    question: "Bacillus anthracis:",
    answer: [" je nepohyblivý, grampozitívny (gramlabilný, ak tvorí spóry)"," faktorom virulencie je toxín a polypeptidové puzdro "," v prevencii sa môže použiť vakcína"," ochorenie môže vzniknúť inhaláciou spór"," bránou infekcie môže byt' poškodená koža"," ochorenie patrí medzi zoonózy"],
    options: [" je nepohyblivý, grampozitívny (gramlabilný, ak tvorí spóry)"," faktorom virulencie je toxín a polypeptidové puzdro ","produkuje podobne ako Bacillus cereus beta-hemolyzin"," medzi faktory virulencie patrí komplexný toxín"," medzi faktory virulencie patrí enterotoxín"," v prevencii sa môže použiť vakcína"," ochorenie môže vzniknúť inhaláciou spór"," bránou infekcie môže byt' poškodená koža"," ochorenie patrí medzi zoonózy","neliečená prúena forma má obvykle mierny priebeh a nízku mortalitu"],
 },
 {
    numb: 133,
    question: "Medzi špirálovité baktérie patri:",
    answer: [" Leptospira"," Borrelia"," Treponema"],
    options: ["Pseudomonas"," Leptospira"," Yersinia"," Borrelia","Providencia"," Francisella"," Treponema"," Vibrio"],
 },
 {
    numb: 134,
    question: "Borrelia recurrentis:",
    answer: [" mikroorganizmus prenášajú článkonožce"," mikroskopický dôkaz robĺme z krvi"," zmena antigénovej štruktúry zodpovedá za opakované záchvaty horúčky"," je pohyblivá, špirálovitá baktéria"," je patogénna len pre človeka"],
    options: [" kultivujeme na čokoládovom agare"," mikroorganizmus prenášajú článkonožce","nedá sa sledovať mikroskopom v prechádzajúcom svetle"," mikroskopický dôkaz robĺme z krvi"," zmena antigénovej štruktúry zodpovedá za opakované záchvaty horúčky","ochorenie sa prenáša priamym kontaktom"," je pohyblivá, špirálovitá baktéria"," je patogénna len pre človeka"," pri podozreni na ochorenie odoberáme krv na hemokultiváciu"],
 },
 {
    numb: 135,
    question: "Borrelia recurrentis spôsobuje:",
    answer: [" epidemickú návratnú horúčku"," celkové ochorenie s typickou teplotnou krivkou"," jediným rezervoárom je človek"],
    options: [" epidemickú návratnú horúčku"," časté aborty u dobytka ","škvrnitý týfus","maltskú horúčku","Q-horúčku","volynskú horúčku"," celkové ochorenie s typickou teplotnou krivkou"," ochorenie prenosné vzdušnou cestou","ochorenie prenosné fekálno-orálne"," jediným rezervoárom je človek"],
 },
 {
    numb: 136,
    question: "Laboratórna diagnostika lymskej boreliózy:",
    answer: [" sa opiera o dôkaz protilátok"," pri neuroborelióze sa dokazujú protilátky aj v likvore"," irnunoblot sa móže využiť ako konfirmačný test pri dôkaze protilátok"],
    options: [" sa opiera o dôkaz bunkovej imunity (kožný test)"," sa opiera o dôkaz protilátok"," pri neuroborelióze sa dokazujú protilátky aj v likvore","využíva prednostne kultivačné techniky"," irnunoblot sa móže využiť ako konfirmačný test pri dôkaze protilátok","pôvodca sa dokazuje v likvore po farbenĺ podľa Grama"," pôvodca vyrastá na bežných kultivačných pôdach za 24 — 48 hodĺn"],
 },
 {
    numb: 137,
    question: "Lynisktí horelióza sa prenáša: ",
    answer: [" vektormi (kliešte)"," ektoparazitmi"],
    options: ["vzdušnou cestou","fekálno-orálnou cestou "," priamym kontaktorn"," vektormi (kliešte)","pasívne muchami"," ektoparazitmi","pohryznutĺm infikovaným cicavcom"],
 },
 {
    numb: 138,
    question: "Borrelia burgdorferi spôsobuje:",
    answer: [" lymskú borelíózu"," erythema migrans"," celkové ochorenie s rôznorodou symptomatológiou"],
    options: [" maltskú horúčku"," epidemickú návratnú horúčku"," lymskú borelíózu"," erysipeloid"," endemickú návratnú horúčku"," erythema migrans"," hnisanie rán"," hnačky"," celkové ochorenie s rôznorodou symptomatológiou"],
 },
 {
    numb: 139,
    question: "Treponema :",
    answer: [" T pallidum sa môže podiel'ať na vzniku orgánových zmien (guma)"," T pallidum móže spôsobiť intrauterinnú infekciu plodu"," antikardiolipinové protilátky pri syfilise odrážajú aktivitu ochorenia"," likvor pri tabes dorsalis móže obsahovať živé treponémy"],
    options: [" T pallidum sa môže podiel'ať na vzniku orgánových zmien (guma)"," T pallidum móže spôsobiť intrauterinnú infekciu plodu"," T pertenue sa prenáša výlučne pohiavným stykom"," antikardiolipinové protilátky pri syfilise odrážajú aktivitu ochorenia"," lues sa prenáša z infi.kovam'rch primátov na človeka"," v terciárnom štádiu syfilisu u pacienta nedokážeme treponémy ","kož.né eflorescencie II. štádia neobsahujú virulentné treponémy"," likvor pri tabes dorsalis móže obsahovať živé treponémy"],
 },
 {
    numb: 140,
    question: "Laboratórna diagnostika syfilisu:",
    answer: [" mikroorganizmus možno mikroskopicky dokázať už v 1. štádiu"," mikroorganizmus je viditeľný v tmavom poli"," ochorenie môžeme sérologicky dokázať už koncom 1. š'tádia"," lues potvrdzuje dókaz antitreponémových protilátok"," imunoblot sa môže využiť ako konfirmačný test pri dôkaze protilátok"," len sérologické testy s treponémovým antigénom potvrdia diagnózu"],
    options: [" mikroorganizmus možno mikroskopicky dokázať už v 1. štádiu"," mikroorganizmus je viditeľný v tmavom poli"," ochorenie môžeme sérologicky dokázať už koncom 1. š'tádia"," dôkaz antikardiolipinových protilátok definitívne potvrdzuje diagnózu lues"," lues potvrdzuje dókaz antitreponémových protilátok"," mikrób vyrastá na špeciálnych tekutých pôdach za 48 hodín ","na identifikáciu je rozhodujúci dôkaz biochemických vlastností"," imunoblot sa môže využiť ako konfirmačný test pri dôkaze protilátok"," len sérologické testy s treponémovým antigénom potvrdia diagnózu"],
 },
 {
    numb: 141,
    question: "Treponema pallidurn je pôvodcom ochorenia:",
    answer: [" lues"," syfilis"," výlučne u človeka"],
    options: [" prenosného výlučne pri pohlavnom styku"," lymphogranuloma venereum"," AIDS"," lues"," syfilis"," výlučne u človeka","ulcus molle","ktoré prechádza do chronického štádia len u ženy ","pohlavne prenosnej uretritídy"],
 },
 {
    numb: 142,
    question: "Leptospira interrogans:",
    answer: [" patrí medzi š'pirálovité baktérie"," vyrastá na špeciálnych pôdach (Korthoffova pôda)"," vo vlhkom prostredí prežíva niekoľko mesiacov"," na sérotypizáciu použivame mikroaglutinačno-lytickú reakciu"," v sére pacienta možno dolcázať špecifické protilátky"," pacient móže vylučovať pôvodcu ochorenia močom"],
    options: [" patrí medzi š'pirálovité baktérie"," vyrastá na špeciálnych pôdach (Korthoffova pôda)"," vo vlhkom prostredí prežíva niekoľko mesiacov"," postinfekčná imunita nie je sérotypovo špecifická"," mikroskopicky ju možno pozorovat' v prechádzajúcom svetle"," na sérotypizáciu použivame mikroaglutinačno-lytickú reakciu"," v sére pacienta možno dolcázať špecifické protilátky"," pacient móže vylučovať pôvodcu ochorenia močom"],
 },
 {
    numb: 143,
    question: "Leptospiróza:",
    answer: [" ochorenie patrí medzi zoonózy"," zvieratá môžu leptospiry dlhodobo vylučovať močom"," človek sa môže infikovať kontaminovanou vodou alebo potravinami"," mikroorganizmus preniká sliznicami a poranenou kožou"," ochorenie sa móže manifestovať ako aseptická meningitída"," závažné formy sa prejavia ikterom a hemorágiami"," na začiatku ochorenia dokazujeme leptospiry v krvi, likvore; neskôr v moči "],
    options: [" ochorenie patrí medzi zoonózy"," zvieratá môžu leptospiry dlhodobo vylučovať močom"," človek sa môže infikovať kontaminovanou vodou alebo potravinami"," mikroorganizmus preniká sliznicami a poranenou kožou"," ochorenie na človeka prenášajú ektoparazity zvierat"," ochorenie sa móže manifestovať ako aseptická meningitída"," závažné formy sa prejavia ikterom a hemorágiami","ochorenie je vždy sprevádzané ikterom"," na začiatku ochorenia dokazujeme leptospiry v krvi, likvore; neskôr v moči ","sérologické vyšetreme protilátok nemá diagnostický význam"],
 },
 {
    numb: 144,
    question: "Clostridium:",
    answer: [" termolabilný enterotoxín produkuje C. perfi-ingens typ A","  C perfringens patrí k pôvodcom plynových gangrén","  virulenciu C. tetani podmieriuje tetanospazmfn","  tetanospazmín blokuje uvoľnenie glycinu a GABA na tlmivej synapse "],
    options: [" termolabilný enterotoxín produkuje C. perfi-ingens typ A","C.      nikdy nie je súčasťou normálnej flóry v čreve človeka","  C perfringens patrí k pôvodcom plynových gangrén","  C. tetani produkuje kolagenázu","  proti tetanu očkujeme atenuovanou baktériou","  virulenciu C. tetani podmieriuje tetanospazmfn","pri očkovaní proti tetanu stači podať 1 dávku očkovacej látky","  tetanospazmín blokuje uvoľnenie glycinu a GABA na tlmivej synapse ","klinický obraz tetanu sprevádza chabá paralýza"],
 },
 {
    numb: 145,
    question: "Clostridium spp:",
    answer: ["  C. novyi patrí k póvodcom plynovej gangrény","  C. biferrnentans môže spôsobiť plynovú gangrénu","  botulotoxin blokuje vylučovanie acetylcholinu na nervovosvalovej platničke"],
    options: ["  C. botulinurn produkuje antigénne jednotný botulotoxin","  klinická diagnóza potravinového botulizmu sa potvrdí kultivačne","  C. novyi patrí k póvodcom plynovej gangrény","protektívna imunita pri infekcii C. tetani je prednostne bunkového typu","  antibotulinické sérum inaktivuje aj už nadviazaný toxín","  C. biferrnentans môže spôsobiť plynovú gangrénu","ako prvú pri príznakoch tetanu aplikujeme antibiotickú liečbu","imunita po očkovaní proti tetanu je doživotná","pri očkovaní proti tetanu aplikujeme spóry C. tetani podkožne","  botulotoxin blokuje vylučovanie acetylcholinu na nervovosvalovej platničke"],
 },
 {
    numb: 146,
    question: "Veillonella spp:",
    answer: ["  je to granmegatívna striktne anaeróbna baktéria","  morfologicky patrí ku gramnegatívnym kokom","  ako podmienený patogén sa uplatňuje len v zmiešanej infekcii ","  je súčasťou normálnej fióry dutiny ústnej, čreva a pošvy","  je pôvodcom oportúnnych endogénnych infekcií"],
    options: ["  je to granmegatívna striktne anaeróbna baktéria","  morfologicky patrí ku gramnegatívnym kokom","  ako podmienený patogén sa uplatňuje len v zmiešanej infekcii ","nikdy sa nevyskytuje v normálnej flóre dýchacích ciest","  mikroorganizmy sú fakultatívne anaeróbne","  je súčasťou normálnej fióry dutiny ústnej, čreva a pošvy","  je pôvodcom oportúnnych endogénnych infekcií"],
 },
 {
    numb: 147,
    question: "Mykopiazmy intdu spôsobiť ochorenia:",
    answer: ["  atypická pneumónia","  endometritída a salpingitída","  uretritída","  intersticiálny zápai pľúc"],
    options: ["  atypická pneumónia","  endometritída a salpingitída","  uretritída","  intersticiálny zápai pľúc","  plynová gangréna","  furunkul","  myonelu-óza","  dermatomyozitida ","pleurodynia"],
 },
 {
    numb: 148,
    question: "Mycoplasma pneumoniae:",
    answer: ["  na špeciálnych pôdach vyrastá v mikrokolóniách až po dihšej kultivácii","  poškodzuje mukociliárny aparát dýchacieho traktu","  u časti chorých sa tvoria chladové autoaglutiníny (protilátky reagujúce serytrocytrni)","  ochorenie potvrdíme sérologicky dókazom protilátok"],
    options: ["  je pravidelne citlívá na ampicilín","  kmene tvoriace beta-laktamázy sú citlivé na amoxicilín/klavulanát","  nemožno ju kultivovať na kuitivačných pôdach","  na špeciálnych pôdach vyrastá v mikrokolóniách až po dihšej kultivácii","  poškodzuje mukociliárny aparát dýchacieho traktu","  u časti chorých sa tvoria chladové autoaglutiníny (protilátky reagujúce serytrocytrni)","  ochorenie potvrdíme sérologicky dókazom protilátok","  pre ochorenie je charakteristický purulentný zápal"],
 },
 {
    numb: 149,
    question: "Ochorenia u ľudi najčastejšie vyvolávajú:",
    answer: ["  Mycoplasrna genitalium","  Mycoplasma pneumoniae","  Ureaplasma urealyticum"," Mycoplasma hominis"],
    options: ["  Mycoplasrna genitalium","  Mycoplasma pneumoniae","  Ureaplasma urealyticum","  Mycoplasma orale","  Mycoplasma salivarium ","Mycoplasma fermentans","  Mycoplasma buccale"," Mycoplasma hominis"],
 },
 {
    numb: 150,
    question: "L-formy baktérii vznikajú:",
    answer: ["  pósobením lyzozýmu","  pod vplyvom antibiotík","  u niektorých baktérií počas liečby penícilínom","  v makroorganizme pôsobením protilátok a komplementu"],
    options: ["  pósobením lyzozýmu","  pod vplyvom antibiotík","  pod vplyvom chemických karcinogénov","  u niektorých baktérií počas liečby penícilínom","často pri mykoplazmách počas antibiotickej terapie","  v makroorganizme pôsobením protilátok a komplementu","  ako následok sporulácie","  za zníženého parciálneho tlaku kyslíka v prostredí ","pri zmene osmotického tlaku v kultivačnom prostredi"],
 },
 {
    numb: 151,
    question: "Riketsie:",
    answer: ["  sú obligátne intracelulárne","  v diagnostike infekcii sa opierame ❑ nepriamy dôkaz"," v diagnostike sa mäže použif PCR"],
    options: ["  sú obligátne intracelulárne","množia sa aj v špeciálnych syntetických médiách","  nie sú citlivé na antibiotiká","  nemajú DNA","  nemajú vlastnú proteosyntézu","  v diagnostike infekcii sa opierame ❑ nepriamy dôkaz"," v liečbe uprednostriujeme cefalosporíny a ureidopenicilíny"," v diagnostike sa mäže použif PCR"],
 },
 {
    numb: 152,
    question: "Rkkettsia prowazekii:",
    answer: [" rezervoárom je človek"," pri diagnostike sa opierame o sérologický dôkaz protilátoke"," liekom voľby sii tetracyklíny a chloramfenikol"," Brillova-Zinsserova choroba je recidíva škyrnitého týfusu"],
    options: [" rezervoárom je človek","ochorenie sa prenáša priamym kontaktom"," pri diagnostike sa opierame o sérologický dôkaz protilátoke"," liekom voľby sii tetracyklíny a chloramfenikol"," odvšivavenie nemá epidemiologický význam","je pôvodcom myšieho škvrnitého týfusu"," rezervoárom sú hlavne myši"," vektorom je bicha"," Brillova-Zinsserova choroba je reinfekcia R. prowazekii"," Brillova-Zinsserova choroba je recidíva škyrnitého týfusu"],
 },
 {
    numb: 153,
    question: "Coxiella burnetii:",
    answer: [" spósobuje Q-horúčku"," infekcia sa prenáša inhaláciou aerosólu, perorálne, alebo vektorom"," pri ochorení vyšetrujeme krv na clókaz protilátok"," infekcia sa môže preniesť požitim mlieka alebo prostredníctvom kliešťa "," ochorenie môže prebiehaf pod obrazom atypickej pneumónie a hepatitídy"," môž'e spôsobiť chronickú infekciu s endokarditídou"],
    options: [" spósobuje Q-horúčku"," prameriam nákazy je vždy človek"," infekcia sa prenáša inhaláciou aerosólu, perorálne, alebo vektorom"," pri ochorení vyšetrujeme krv na clókaz protilátok"," infekcia sa môže preniesť požitim mlieka alebo prostredníctvom kliešťa ","nepriama diagnostika nemá význam"," ochorenie sprevádza exantém a enantém"," ochorenie môže prebiehaf pod obrazom atypickej pneumónie a hepatitídy"," môž'e spôsobiť chronickú infekciu s endokarditídou"],
 },
 {
    numb: 154,
    question: "Chlamýdie:",
    answer: [" množia sa výlučne intracelulárne ","  nemajú vlastný energetický metabolizmus","  v infikovanej bunke vytvárajú inklúzie ","  infekčné sú len elementárne telieska"],
    options: [" množia sa výlučne intracelulárne ","patria ku grampozitívnym baktériám","  nemajú vlastný energetický metabolizmus","  v infikovanej bunke vytvárajú inklúzie ","mikroskopický preparát farbime podľa Ziehla-Neelsena","pri sérologickom dôkaze protilátok využívame antigény puzdra","  infekčné sú len elementárne telieska","  retikulárne teliesko je osmoticky stabilné"],
 },
 {
    numb: 155,
    question: "Chlamydia trachomatis (sérotypy D-K):",
    answer: ["  spôsobuje inklúznu konjunktivitídu","  je pôvodcom uretrititídy","  prenáša sa pohlavným stykom","  ochorenie je bežné aj v našich zemepisných šírkach","  pri diagnostike cervicitídy sa dokazuje antigén v cervikálnych výteroch"],
    options: ["liečba antibiotikami je neúčinná","prenáša sa potravinami","  u dospelých sa klinicky najčastejšie prejavi ako pneumónia","rezervoárom infekcie sú vtáky","  spôsobuje inklúznu konjunktivitídu","  je pôvodcom uretrititídy","  prenáša sa pohlavným stykom","  ochorenie je bežné aj v našich zemepisných šírkach","  pri diagnostike cervicitídy sa dokazuje antigén v cervikálnych výteroch"],
 },
 {
    numb: 156,
    question: "Chlamydia pneumoniae:",
    answer: ["  vyvoláva atypickú pneurnóniu"," pri diagnostike sa prednostne využíva dôkaz protilátok"," ochorenie častejšie postihuje horné dýchacie cesty než pľúca "," prenáša sa kvapôčkovou infekciou"],
    options: ["  vyvoláva atypickú pneurnóniu","vyvoláva purulentnú meningitidu"," pri diagnostike sa prednostne využíva dôkaz protilátok"," prenáša sa pohlavným stykom"," ochorenie častejšie postihuje horné dýchacie cesty než pľúca ","na krvnom agare vyrastie do 2 dní"," prenáša sa kvapôčkovou infekciou"],
 },
 {
    numb: 157,
    question: "Označte správne kombinácie pôvodca-ochorenie:",
    answer: ["Coxiella burnetii Q-honáčka", "Haemophilus influenzae — epiglotitída", "Chlamydia trachomatis lymfogranuloma venereum ", "Streptococcus pyogenes šarlach", "Staphylococcus aureus syndróm toxického šoku"],
    options: ["Coxiella burnetii Q-honáčka", "Haemophilus influenzae — epiglotitída", "Chlamydia trachomatis lymfogranuloma venereum ", "Streptococcus pyogenes šarlach", "Staphylococcus aureus syndróm toxického šoku", "Haemophilus ducrei ulcus du•um", "Streptococcus agalactiae — endocarditis lenta", "Rick2ttsia prowazekii — psitakóza", "Streptococcus mutans — reumatická hoffička", "Neisseria meningitidis — intersticiálna pneumónia"],
 },
];
