let questions = [
  {
    numb: 0,
    question: "Karcinoembryonálny antigén (CEA) sa používa",
    answer: [" na monitorovanie liečby pacientov s kolorektálnym karcinómom", " na včasnú diagnostiku recidívy kolorektálneho karcinómu "],
    options: ["na plošný skríning gastrointestinálnych nádorov"," na monitorovanie liečby pacientov s kolorektálnym karcinómom"," na včasnú diagnostiku kolorektálneho karcinómu", " na včasnú diagnostiku recidívy kolorektálneho karcinómu "],
 },
 {
    numb: 1,
    question: "Karcinoembryonálny antigén (CEA) sa používa",
    answer: [" na skríning kolorektálneho karcinómu v rizikových skupinách ","u pacientov s adenokarcinómom pľúc"],
    options: [" na skríning kolorektálneho karcinómu v rizikových skupinách ", "na skríning nádorov pankreasu", "na sledovanie pacientov s malobunkovým karcinómom pľúc", "u pacientov s adenokarcinómom pľúc"],
 },
 {
    numb: 2,
    question: "Karcinoembryonálny antogén (CEA)",
    answer: ["býva zvýšený u fajčiarov", "môže byť zvýšený pri divertikulitíde čreva","hodnoty do 10 µg/l nemusia znamenať prítomnosť nádoru"],
    options: ["používa sa aj v prenatálnej diagnostike", "býva zvýšený u fajčiarov", "môže byť zvýšený pri divertikulitíde čreva","hodnoty do 10 µg/l nemusia znamenať prítomnosť nádoru"],
 },
 {
    numb: 3,
    question: ".Karcinoembryonálny antogén (CEA)",
    answer: ["môže mať prognostický význam pri kolorektálnom karcinóme","fyziologicky je produkovaný bunkami GIT-u vo fetálnom období"],
    options: ["hodnoty do 10 µg/l sú podozrivé z prítomnosti metastáz","môže mať prognostický význam pri kolorektálnom karcinóme","fyziologicky je produkovaný bunkami GIT-u vo fetálnom období","je to látka hormonálnej povahy "],
 },
 {
    numb: 4,
    question: "Karcinoembryonálny antigén (CEA)",
    answer: ["môže byť zvýšený aj pri benigných chorobách", "môže byť zvýšený pri zápaloch čreva" ," môže byť zvýšený pri niektorých nádoroch pľúc "],
    options: ["môže byť zvýšený aj pri benigných chorobách", "môže byť zvýšený pri zápaloch čreva"," býva pravidelne zvýšený u pacientov s nádorom pankreasu" ," môže byť zvýšený pri niektorých nádoroch pľúc "],
 },
 {
    numb: 5,
    question: "Karcinoembryonálny antogén (CEA)",
    answer: ["byva zvyseny pri metastatickom poskodeni pecene","môže byť zvýšený u pacientov s cirhózou pečene"],
    options: ["býva zvýšený pri nádoroch pľúc z dlaždicového epitelu","môže byť zvýšený u pacientov s cirhózou pečene","používa sa ako marker pri cervikálnom karcinóme","používa sa pri seróznom type cystadenokarcinómu vaječníkov", "byva zvyseny pri metastatickom poskodeni pecene"],
 },
 {
    numb: 6,
    question: "Karcinoembryonálny antigén (CEA)",
    answer: ["fyziologicky sa syntetizuje v bunkách fetálneho čreva"],
    options: ["fyziologicky sa syntetizuje v bunkách fetálnej pečene","fyziologicky sa syntetizuje v bunkách fetálneho čreva", " býva zvýšený pri hepatocelulárnom karcinóme"," býva zvýšený pri malobunkovom karcinóme pľúc"],
 },
 {
    numb: 7,
    question: "Vyšetrenie hladiny karcinoembryonálneho antigénu sa používa pri",
    answer: ["pri monitorovaní liečby u pacienta s kolorektálnym karcinómom","pri skríningu nádoru hrubého čreva u pacientov s polypózou čreva"],
    options: ["diferenciálnej diagnostike hepatocelulárneho a cholangiocelulárneho karcinómu","diagnostike cirhózy pečene","pri monitorovaní liečby u pacienta s kolorektálnym karcinómom","pri skríningu nádoru hrubého čreva u pacientov s polypózou čreva"],
 },
 {
    numb: 8,
    question: "Karcinoembryonálny antigén (CEA)",
    answer: ["je onkofetálny antigén","býva zvýšený pri adenokarcinóme prsníka"],
    options: ["je onkofetálny antigén","je onkoplacentárny antigén","býva zvýšený pri adenokarcinóme prsníka","býva zvýšený pri nádoroch z plochého dlaždicového epitelu"],
 },
 {
    numb: 9,
    question: "Alfa-fetoproteín",
    answer: ["fyziologickly je produkovaný bunkami fetálnej pečene","fyziologicky je produkovaný bunkami žltkového vaku", "fyziologicky býva zvýšený v sére gravidných žien"],
    options: ["fyziologickly je produkovaný bunkami fetálnej pečene","fyziologicky je produkovaný bunkami žltkového vaku","v plodovej vode sa používa na posúdenie zrelosti pľúc plodu", "fyziologicky býva zvýšený v sére gravidných žien"],
 },
 {
    numb: 10,
    question: "Alfa-fetoproteín",
    answer: ["jeho vyšetrenie v krvi sa používa pri skríningu razštepov neurálnej trubice","sa svojimi vlastnosťami a funkciou podobá albumínu"],
    options: ["jeho vyšetrenie v krvi sa používa pri skríningu razštepov neurálnej trubice","sa svojimi vlastnosťami a funkciou podobá albumínu","používa sa na dôkaz gravidity","býva zvýšený pri metastatickom postihnutí pečene"],
 },
 {
    numb: 11,
    question: "Zvýšené hladiny alfa-fetoproteínu bývajú pravidelne pri",
    answer: ["primárnom hepatocelulárnom karcinóme","niektorých nádoroch semenníkov"],
    options: ["primárnom hepatocelulárnom karcinóme","niektorých nádoroch semenníkov","pri metastáze nádorov čreva do pečene","pokročilom mnohopočetnom myelóme" ],
 },
 {
    numb: 12,
    question: "Zvýšené hladiny AFP bývajú pravidelne pri",
    answer: ["v priebehu gravidity"],
    options: ["nádoroch vaječníkov","nádoroch pľúc","malobunkovom karcinóme pľúc","v priebehu gravidity"],
 },
 {
    numb: 13,
    question: "AFP",
    answer: ["možno použiť pri odlíšení hepatocelulárneho karcinómu od metastáz do pečene","možno použiť pri rozlíšení hepatocelulárneho karcinómu a cholangiocelulárneho karcinómu"," je onkofetálny antigén"],
    options: ["možno použiť pri odlíšení hepatocelulárneho karcinómu od metastáz do pečene","možno použiť pri rozlíšení hepatocelulárneho karcinómu a cholangiocelulárneho karcinómu","býva zvýšený u pacientov s adenómom pečene"," je onkofetálny antigén"],
 },
 {
    numb: 14,
    question: "Hladiny AFP bývajú zvýšené",
    answer: ["pri cirhóze pečene","pri regenerácii pečene","v gravidite"],
    options: ["pri cirhóze pečene","pri regenerácii pečene","v gravidite","pri Downovom syndróme"],
 },
 {
    numb: 15,
    question: "Alfa-fetoproteín",
    answer: ["používa sa pri diagnostike germinatívnych nádorov testes","používa sa na sledovanie pacientov s maldescensusu testes"],
    options: ["používa sa pri diagnostike germinatívnych nádorov testes","je vyšetrením 1.voľby pri podozerní na nádor pankreasu","používa sa na sledovanie pacientov s maldescensusu testes","používa sa v diagnostike nádorov prostaty"],
 },
 {
    numb: 16,
    question: "Hladiny hCG bývajú zvýšené pri",
    answer: ["choriokarcinóme","mola hydatidosa","aj pri niektorých netrofoblastových nádoroch"],
    options: ["choriokarcinóme","mola hydatidosa","aj pri niektorých netrofoblastových nádoroch","len pri nádoroch z trofoblastu" ],
 },
 {
    numb: 17,
    question: "Hladiny hCG bývajú zvýšené pri",
    answer: ["gravidite","aj pri extrauterinnej gravidite "],
    options: ["malobunkovom karcinóme pľúc","pri ovariálnom karcinóme","gravidite","aj pri extrauterinnej gravidite "],
 },
 {
    numb: 18,
    question: "O hCG môžeme povedať",
    answer: ["vyšetrujeme ho v rámci skríningu u gravidných žien"],
    options: ["býva zvýšený pri pravých seminómoch","býva zvýšený pri nádoroch semenníkov obsahujúcich štruktúry žltkového vaku","vyšetrujeme ho v rámci skríningu u gravidných žien"," býva zvýšený u plodov s anencefaliou" ],
 },
 {
    numb: 19,
    question: "O hCG môžeme povedať",
    answer: ["používa sa pri skríningu Downovej choroby","býva zvýšený pri invazívnej mole","vyšetruje sa aj voľná beta-podjednotka"],
    options: ["používa sa pri skríningu Downovej choroby","býva zvýšený pri invazívnej mole","vyšetruje sa aj voľná alfa-podjednotka","vyšetruje sa aj voľná beta-podjednotka"],
 },
 {
    numb: 20,
    question: "Ktoré z uvedených baktérií sú súčasne grampozitívne a sporulujú:",
    answer: [" Bacillus anthracis"," Clostridium botulinum"," Bacillus cereus"," Clostridium perftingens"],
    options: [" Haemophilus influenzae"," Bacillus anthracis"," Lactobacillus"," Bifidobacterium"," Clostridium botulinum"," Actinornyces spp."," Bacillus cereus"," Clostridium perftingens"],
 },
 {
    numb: 21,
    question: "Na dôkaz puzdra baktéril môžeme použiť:",
    answer: [" sérologickú reakciu so špecifickými protilátkami"," Burriho metódu (negatívne znázomenie)"," Burriho metódu pri dôkaze opuzdrených baktérií v likvore"," rušový preparát kombinovaný monochromatickým farbenfin"],
    options: [" sérologickú reakciu so špecifickými protilátkami","Ziehlovo-Neelsenovo farbenie"," Burriho metódu (negatívne znázomenie)","Wrightovo farbenie","Giemsovo farbenie","farbenie metylénovou modrou"," farbenie koncentrovanýrni farbivami za horúca"," Burriho metódu pri dôkaze opuzdrených baktérií v likvore"," rušový preparát kombinovaný monochromatickým farbenfin"],
 },
 {
    numb: 22,
    question: "Mykobaktérie v klinickom materiáli dokazujeme: ",
    answer: [" farbenim podľa Ziehla-Neelsena"," auramínom (fluorescenčné farbenie)"],
    options: ["farbením podľa Grama"," farbenim podľa Ziehla-Neelsena"," Burriho metódou"," auramínom (fluorescenčné farbenie)","metylénovou modrou ","farbením podľa Giemsu","farbenírn podľa Wrighta","pomocou fázového kontrastu"],
 },
 {
    numb: 23,
    question: "V infekčnom materiáli sú typicky vo dvojiciach usporiadané:",
    answer: [" Neisseria gonorrhoeae"," Streptococcus pneumoniae"," Neisseria meningitidis "],
    options: [" Neisseria gonorrhoeae"," Clostridium tetani"," Streptococcus pyogenes","Streptococcus agalactiae"," Streptococcus pneumoniae","Mycobacterium tuberculosis"," Treponerna pallidum"," Neisseria meningitidis "],
 },
 {
    numb: 24,
    question: "V preparáte farbenom podľa Grama majú rovnakú morfológiu:",
    answer: [" Streptococcus salivarius a Streptococcus pyogenes"," Streptococcus pyogenes a Streptococcus agalactiae"," Sžaphylococcus aureus a Staphylococcus saprophyticus"," Escherichia coli a Sahnonella Typhi"],
    options: ["Streptococcus salivarius a Streptococcus pneumoniae"," Streptococcus salivarius a Streptococcus pyogenes"," Corynebacterium diphtheriae a Lactobacillus acidophilus","Clostridium tetani a Clostridium botulinum"," Streptococcus pyogenes a Streptococcus agalactiae"," Sžaphylococcus aureus a Staphylococcus saprophyticus"," Escherichia coli a Sahnonella Typhi","Bacillus anthracis a Yersinia pestis","Francisella tularensis a Pseudomonas aeruginosa","Moraxella catarrhalis a Neisseria meningitidis"],
 },
 {
    numb: 25,
    question: "'Vi-antigén:",
    answer: [" vhodne upravený sa používa na očkovanie"," je mikropuzdrovým antigénom"],
    options: ["sa nachádza pri Staphylococcus aureus"," vhodne upravený sa používa na očkovanie","sa nachádza pri Escherichia coli"," sa nachádza pri Proteus vulgaris","je bičĺkovým antigénorn","nachádza sa pri Salmonella Typhi","sa nachádza pri Salmonella Enteritidis"," je mikropuzdrovým antigénom","je telovým (somatickým) antigénom"],
 },
 {
    numb: 26,
    question: "Ktoré z uvedených baktérii môžu tvoriť spóry:",
    answer: [" Bacillus cereus"," Clostridium botulinum"," Bacillus anthracis "," Clostridium perfi-ingens"],
    options: [" Bacillus cereus"," Clostridium botulinum"," Bacillus anthracis ","Clostridium","Clostridium tetani"," Clostridium perfi-ingens","Lactobacillus spp."," Bifidobacterium spp. ","Enterococcus faecalis ","Klebsiella pneumoniae"],
 },
 {
    numb: 27,
    question: "Transdukcia:",
    answer: [" je prenos bakteriálnej DNA bakteriofágorn"," prebieha pomocou fágov"," je prenos plazmidovej DNA bakteriofágom."],
    options: ["je zmena genetickej informácie baktérií spósobená teplom ","je zmena genetickej informácie baktérii spôsobená žiarením"," je prenos bakteriálnej DNA bakteriofágorn","je prenos bakteriálnej RNA bakteriofágom"," je vstup vornej DNA do bakteriálnej bunky","prebieha prostredníctvom sex-pilusov"," prebieha pomocou fágov"," je prenos plazmidovej DNA bakteriofágom."],
 },
 {
    numb: 28,
    question: "F-faktor je däležitý pri:",
    answer: [" konjugácii"," tvorbe sex fimbrii donorskej bunky"," prenose rezistencie na antibiotiká medzi baktériami"," kontakte donorskej a akceptorovej bunky pri konjugácii"],
    options: [" transformácii","mutácii"," konjugácii","indukcii sacharolytických enzýmov"," transdukcii"," tvorbe sex fimbrii donorskej bunky"," tvorbe spontánnych mutácii"," prenose rezistencie na antibiotiká medzi baktériami"," kontakte donorskej a akceptorovej bunky pri konjugácii"],
 },
 {
    numb: 29,
    question: "Lyzogénna konverzia je prijatie novej genetickej informácie v dôsledku: ",
    answer: [" infekcie bunky temperovaným bakteriofágom"," prítomnosti bakteriofága, ktorý infikovanú bunku nelyz-uje"],
    options: ["pôsobenia tepla","pôsobenia žiarenia"," prenosu DNA baktérie transformáciou","účinku DN-ázy"," účinku proteolytických enzýmov bakteriofága"," infekcie bunky temperovaným bakteriofágom"," prítomnosti bakteriofága, ktorý infikovanú bunku nelyz-uje"," abortívnej infekcie fágom"],
 },
 {
    numb: 30,
    question: "Sex pilus je štruktúra, ktorú baktéria využíva:",
    answer: [" pri výmene genetického materiálu konjugáciou"," pri prenose faktora F"," pri prenose genetickej informácie typickom pre gramnegatívne baktérie"],
    options: [" v energetickom metabolizme"," pri výmene genetického materiálu konjugáciou"," pri výmene genetického materiálu transdukciou"," ako orgán pohybu"," pri prenose genetickej informácie transformáciou","pri adherencii na hostiteľskú. bunku"," pri iniciácii priečneho delenia bunky"," pri prenose faktora F"," pri prenose genetickej informácie typickom pre gramnegatívne baktérie"],
 },
 {
    numb: 31,
    question: "Plazmidy môžu determinovať v bakteriálnej bunke: ",
    answer: [" tvorbu enterotoxínov"," produkciu kolicínov"," rezistenciu na antimikróbne liečivá"," tvorbu sex pilusov"," tvorbu niektorých exotoxinov"],
    options: ["tvorbu lipopolysacharidu"," tvorbu enterotoxínov","tvorbu bičlov"," syntézu mezozómov"," produkciu kolicínov"," rezistenciu na antimikróbne liečivá"," tvorbu sex pilusov"," tvorbu bunkovej steny"," tvorbu niektorých exotoxinov"],
 },
 {
    numb: 32,
    question: "Cieľom kultivačnej metódy pri mikrobiologickom vyšetreni je:",
    answer: [" izolovať mikroorganizmus z biologického materiálu"," ziskať čistú kultúru mikroorganizmu na d'aišie vyšetrovanie"," určif základné rastové vlastnosti mikroorganizmu"," určif základné metabolické vlastnosti izolovaného kmeria "],
    options: [" posúdiť virulenciu izolovaného mikroorganizmu"," izolovať mikroorganizmus z biologického materiálu"," ziskať čistú kultúru mikroorganizmu na d'aišie vyšetrovanie"," určif základné rastové vlastnosti mikroorganizmu"," určif základné metabolické vlastnosti izolovaného kmeria ","posúdiť patogenitu mikroorganizmu","detegovať gény rezistencie","určiť antigénové vybavenie mikroorganizmu"],
 },
 {
    numb: 33,
    question: "Pri eharakteristike bakteriálnych kolúnií si všímame:",
    answer: [" veľkosť"," okraj"," tvar"," povrch"," farbu a zápach"," konzistenciu"],
    options: [" veľkosť"," okraj"," objem"," výšku"," tvar"," povrch"," farbu a zápach"," konzistenciu","rozoskupenie"],
 },
 {
    numb: 34,
    question: "Pri diagnostike hnačiek sa ako rozmnožovacie pôdy používajú:",
    answer: [" alkalická peptónová voda"," selenitový bujón "," Kauffrnannova pôda"],
    options: ["pečeňový bujón s antibiotikami"," alkalická peptónová voda"," koagulované konské sérum"," selenitový bujón "," Kauffrnannova pôda","destilovaná voda","acidifikované mlieko"],
 },
 {
    numb: 35,
    question: "Medzi selektívne pôdy pre salmonely patria:",
    answer: [" Kauffmannova pôda"," dezoxycholátová-citrátová pôda"," Wilsonova-Blairova pôda"],
    options: [" Kauffmannova pôda"," dezoxycholátová-citrátová pôda"," krvný agar"," Wilsonova-Blairova pôda","Bordetova-Gengouova pôda","Francisova pôda ","čokoládový agar "," 'Levinthalova pôda"],
 },
 {
    numb: 36,
    question: "Medzi selektívne pôdy na kultiváciu grainnegatívnych baktérií patria:",
    answer: [" selenitová tekutá pôda"," Kauffmannova pôda"," deoxycholátová pôda "," MacConkey agar"],
    options: [" selenitová tekutá pôda"," Kauffmannova pôda"," pečeňový bujón"," Lôwensteinova pôda"," Endova pôda"," deoxycholátová pôda ","čokoládový agar"," MacConkey agar"],
 },
 {
    numb: 37,
    question: "Na ktorých pôdach rastú kvasinky a plesne: ",
    answer: [" Sabouraudova"," agar s mozgovo-srdcovou infúziou (náročné druhy) "," krvný agar"],
    options: [". Wilsonova-Blairova","selenitová","Kauffm annova"," Sabouraudova","dezoxycholátová"," agar s mozgovo-srdcovou infúziou (náročné druhy) ","Lôwensteinova"," krvný agar"],
 },
 {
    numb: 38,
    question: "Ktoré patogénne baktérie môžu rásť a množiť sa aj pri +4°C:",
    answer: [" Listeria monocytogenes "," Yersinia enterocolitica"],
    options: [" Streptococcus pyogenes"," Staphylococcus aureus"," Listeria monocytogenes "," Enterococcus faecalis","Streptococcus salivarius"," Moraxella catarrhalis"," Neisseria gonorrhoeae ","Escherichia coli"," Yersinia enterocolitica"],
 },
 {
    numb: 39,
    question: "Anaeróbne prostredie pri kultivácii zabezpečime:",
    answer: [" v anaerostate fyzikálnym odstránením kyslíka"," regeneráciou vysoko naliatych pôd teplom (pred naočkovaním) "," chemicky katalytickou oxidáciou vodfica v anaerostate"," Prevotella melaninogenica"," Clostridium tetani"," Clostridium histolyticum"," Bacteroides fragilis"],
    options: ["hermetizáciou termostatu"," v anaerostate fyzikálnym odstránením kyslíka"," regeneráciou vysoko naliatych pôd teplom (pred naočkovaním) ","v sušičke s exikátorom"," v Kochovom prístroji","metódou podľa Giemsu","Burriho metódou"," chemicky katalytickou oxidáciou vodfica v anaerostate",,"Medzi striktné anaeróby patria:"," Prevotella melaninogenica"," Clostridium tetani"," Pseudomonas fluorescens"," Clostridium histolyticum"," Bacteroides fragilis","Campylobacter coli"," Helicobacter pylori"," Mycobacterium tuberculosis ","Neisseria meningitidis"],
 },
 {
    numb: 40,
    question: "Aký materiál sa odoberá pri pokuse o záchyt pôvodcu pri sepse? ",
    answer: ["  krv na hemokultiváciu pred a počas vzostupu teploty","  krv z vena cubiti","  okrem krvi na hemokultiváciu d'a1ši materiál podľa predpokladaného ložiska sepsy","  optímálne tri vzorky krvi, odobraté pred teplotným vrcholom","  ster z miesta vpichu pred odberom krvi"],
    options: ["krv na dôkaz špecifických protilátok","  krv na hemokultiváciu pred a počas vzostupu teploty","  krv na hemokultiváciu, výlučne v afebrilnom období","  krv na hemokultiváciu po vrchole teplotného maxima","  krv z vena cubiti","  krv, prednos-tne z vena femoralis","  krv, klinicky významný je počet baktérií nad 105/m1","  okrem krvi na hemokultiváciu d'a1ši materiál podľa predpokladaného ložiska sepsy","  optímálne tri vzorky krvi, odobraté pred teplotným vrcholom","  ster z miesta vpichu pred odberom krvi"],
 },
 {
    numb: 41,
    question: "U pacienta s nekomplikovanou cystitídou za klinicky významný považujeme počet baktérií ",
    answer: ["  viac ako 100 000","  počet 10 000 hodnotíme ako suspektný","  pri odbere suprapubickou punkciou má byť moč sterílný"],
    options: ["v 1 ml moču:","5000 až 10 000","  viac ako 100 000","  1000 až 10 000","  100 až 1000","  počet 10 000 hodnotíme ako suspektný","počet 1000 — 5000 hodnotíme ako suspektný","  pri odbere suprapubickou punkciou iba 1000 a viac","  pri odbere suprapubickou punkciou má byť moč sterílný"],
 },
 {
    numb: 42,
    question: "Počet baktérlí v moči môleme semikvantitatívne určit': ",
    answer: [" spektrofotometricky (nefelometricky)"," semikvantitatívnou kultíváciou na pevných pôdach"," odberom moču do odberových súprav s nosičom pčd a následnou kultiváciou"," naočkovaním na pôdy kalibrovanou kl'učkou"],
    options: [" spektrofotometricky (nefelometricky)"," semikvantitatívnou kultíváciou na pevných pôdach"," nepriamo stanovenim moču"," stanovenie nemá v klinickej mikrobiológii praktický význam"," dektrónovým mikroskoporn (ak je toto zariadenie k dispozícii) ","kvanfitatívnou aglutináciou s polyš'pecifickými sérami "," odberom moču do odberových súprav s nosičom pčd a následnou kultiváciou"," imunofluorescenčnou metódou z močového sedimentu "," naočkovaním na pôdy kalibrovanou kl'učkou"],
 },
 {
    numb: 43,
    question: "Nepriama mikrobiologická diagnostika sa štandardne používa pri:",
    answer: ["  mykoplannových pneumóniách","  týfuse","  syfilise","  lymskej boreliáze"],
    options: ["  mykoplannových pneumóniách","salmonelóze","  kvapavke","  týfuse","  aktinomykóze","  syfilise","  lymskej boreliáze","4- brucelóze","  cholere"],
 },
 {
    numb: 44,
    question: "Virulencia rnikroorganizmu:",
    answer: ["  je konkrétny stupeň patogenity daného kmeria","  je kmeňovo špecifická vlastnosť"," je geneticky podmienená vlastnosť"],
    options: ["  je konkrétny stupeň patogenity daného kmeria","  je druhová charakteristika mikroorganizmu","  je rodová charakteristika mikroorganizmu","  je kmeňovo špecifická vlastnosť","  je schopnost' mikrobiálneho druhu vyvolávať ochorenia"," je geneticky podmienená vlastnosť","pasážovaním sa môže zvyšovať alebo znižovať ","u daného kmeria je stála a nemóže sa meniť"],
 },
 {
    numb: 45,
    question: "Medzi faktory virulencie baktéríí patria: ",
    answer: [" puzdro"," fimbrie"," erytrogénny toxin"," exotoxiny"," plazmakoaguláza"," extracelulárne proteázy"],
    options: [" mezozómy"," puzdro"," fimbrie"," erytrogénny toxin"," exotoxiny"," plazmakoaguláza","zásobné granuly","cytoplazmatická membrána"," extracelulárne proteázy"],
 },
 {
    numb: 46,
    question: "Medzi faktory virulencie baktérií patria:",
    answer: [" enterotoxiny"," endotoxiny"," proteín-A stafylokokov"," fimbrie","  M-proteín streptokokov","  exotoxíny"],
    options: ["ribozómy"," enterotoxiny"," endotoxiny"," proteín-A stafylokokov"," fimbrie","lyzozómy","  M-proteín streptokokov","  exotoxíny","spóry"],
 },
 {
    numb: 47,
    question: "Medzi adhezíny patria:",
    answer: ["  fimbrie","  M-protein streptokokov","  hemaglutiníny","  kyselina lipoteichoová","  polysacharidové štruktúry biofilmu "],
    options: ["  fimbrie","  M-protein streptokokov","  hemaglutiníny","  kyselina lipoteichoová","  polysacharidové štruktúry biofilmu "," F-pili","  lipopolysacharid gramnegatívnych baktérií ","  bakteriocíny"],
 },
 {
    numb: 48,
    question: "Bakteriocíny:",
    answer: ["  chemicky ide o proteíny","  viažu sa na receptor vonkajšej membrány vnímavej baktérie","  perforujú bunkovú stenu cieľovej baktérie","  schopnost' produkovať bakteriocíny sa obvykle prenáša plazmidmi ","  Col baktérie sú rezistentné na produkovaný kolicín"],
    options: ["  poškodzujú prednostne eukaryotické bunky","  chemicky ide o proteíny","  viažu sa na receptor vonkajšej membrány vnímavej baktérie","  perforujú bunkovú stenu cieľovej baktérie","  schopnost' produkovať bakteriocíny sa obvykle prenáša plazmidmi ","pôsobia nešpecificky na všetky gramnegatívne baktérie","  Col baktérie sú rezistentné na produkovaný kolicín","  na pôsobenie je nevyhnutný vzájomný kontakt (dotyk) baktérií"],
 },
 {
    numb: 49,
    question: "Bakteriocíny môžu tvoriť:",
    answer: ["  Escherichia coli","  streptokoky"," Pseudomonas aeruginosa"," Shigella"," Yersinia pestis"],
    options: ["  Escherichia coli","  streptokoky"," Pseudomonas aeruginosa"," Shigella"," Yersinia pestis"," Candida albicans"," Trichomonas vaginalis"," len nepatogénne baktérie "],
 },
 {
    numb: 50,
    question: "Ktoré baktérie predilekčne poškodzujú pohyb epiteln:",
    answer: [" Haemophilus influenzae "," Bordetella pertussis"," Mycoplasma pneumoniae"," Neisseria gonorrhoeae "],
    options: [" Streptococcus pyogenes ","Streptococcus agalactiae"," Haemophilus influenzae ","Haemophilus ducreyi"," Bordetella pertussis"," Francisella tula•ensis"," Enterobacter aerogenes"," Mycoplasma pneumoniae"," Neisseria gonorrhoeae "],
 },
 {
    numb: 51,
    question: "LPS endotoxin:",
    answer: [" za toxický úč'inok je zodpovedná jeho lipidická časť"," za antigénnu špecifickosť zodpovedá jeho polysacharidová časť"," uvoľňuje sa z gramnegatívnych baktérii prevažne po ich poškodení"," jeho uvoľňovanie má za následok vzostup teploty pri sepse"],
    options: [" za toxický úč'inok je zodpovedná jeho lipidická časť"," za antigénnu špecifickosť zodpovedá jeho polysacharidová časť","za antigénnu špecifickosť zodpovedá proteínová časť molekuly"," uvoľňuje sa z gramnegatívnych baktérii prevažne po ich poškodení","je súčasťou mikropuzdra"," nie je integrálnou súčasťou bunkovej steny"," je súčasťou cytoplazmatickej membrány","bakteriálne bunky ho aktívne uvoľň'ujú do prostredia","uvoľňuje sa z grampozitivnych baktérií po ich poškodení"," jeho uvoľňovanie má za následok vzostup teploty pri sepse"],
 },
 {
    numb: 52,
    question: "Endotoxlín má nasledovné účinky:",
    answer: [" spôsobuje diseminovanú intravaskulárnu koaguláciu"," spôsobuje poruchy hemokoagulácie"," nepriamo spósobuje nekrózu tkanáva"," aktivuje makrofágy (1-vorba IL-1 a TNF)"," aktivuje komplement"," stimuláciou tvorby TNF zvyšuje permeabilitu cievneho endotelu"],
    options: ["neuromuskulárny blok"," spôsobuje diseminovanú intravaskulárnu koaguláciu","spôsobuje zvýšenie teploty priamym pósobením na hypotalamus"," spôsobuje poruchy hemokoagulácie"," nepriamo spósobuje nekrózu tkanáva","indukuje tvorbu interleukínu-1 v B-lymfocytoch"," aktivuje makrofágy (1-vorba IL-1 a TNF)","zvyšuje v napadnutej bunke hladinu cAMP"," aktivuje komplement"," stimuláciou tvorby TNF zvyšuje permeabilitu cievneho endotelu"],
 },
 {
    numb: 53,
    question: "Beta-hemolýzu môžu na krvnom agare spôsobovať:",
    answer: [" Streptococcus pyogenes"," Streptococcus agalactiae"," Escherichia coli"," Staphylococcus aureus"," Pseudomonas aeruginosa "," Listeria monocytogenes"," Bacillus cereus"],
    options: [" Streptococcus salivarius"," Streptococcus pyogenes"," Streptococcus agalactiae"," Streptococcus mutans"," Escherichia coli"," Staphylococcus aureus"," Pseudomonas aeruginosa ","Proteus mirabilis"," Listeria monocytogenes"," Bacillus cereus"],
 },
 {
    numb: 54,
    question: "Produkovať enterotoxfn a súčasne spôsobovať beta-hemolýzu môžu:",
    answer: [" Escherichia coli"," Staphylococcus aureus "," Vibrio choierae (E1 Tor)"," Clostridium pet:Ping-ens"],
    options: ["Streptococcus pyogenes "," Proteus vulgaris"," Escherichia coli"," Staphylococcus aureus "," Salmonella typhi"," Citrobacter fteundii"," Enterobacter aerogenes"," Klebsiella oxytoca"," Vibrio choierae (E1 Tor)"," Clostridium pet:Ping-ens"],
 },
 {
    numb: 55,
    question: "Protein A:",
    answer: [" produkuje Staphylococcus aureus "," využívame v diagnostike pri identiftkácii S. aureus"," viaže Fc-fragment IgG"],
    options: ["1111 - produkuje Streptococcus pyogenes","je súčasťou slizovej vrstvy baktérií"," produkuje Streptococcus pneumoniae"," produkuje Staphylococcus aureus "," produkujú proteolytické kmene enterobaktérií"," produkuje Listeria monocytogenes"," využívame v diagnostike pri identiftkácii S. aureus"," viaže Fc-fragment IgG"," produkujú streptoky skupiny A ako súč'asť bunkovej steny"],
 },
 {
    numb: 56,
    question: "Lipidy a vosky mykobaktérif sú zodpovedné za: ",
    answer: ["  virulenciu mykobaktérií","  adjuvantný účinok pri imunizácii","  pomalý rast mykobaktéril","  odolnosť voči mikrobicídii vo fagocytoch "],
    options: ["schopnosť mykobaktérií farbiť sa gramnegatívne","  virulenciu mykobaktérií","  citlivosť na organické kyseliny","  adjuvantný účinok pri imunizácii","  pomalý rast mykobaktéril","  hemolytické vlastnosti M tuberculosis","  odolnosť voči mikrobicídii vo fagocytoch ","citlivosť na ampicilín"],
 },
 {
    numb: 57,
    question: "Cord faktor je štruktúra:",
    answer: ["  mykobaktérií ","  pôvodcu tuberkulózy","  súvisiaca s bunkovou stenou mykobaktérií"],
    options: ["  neisserií","  korynebaktérií ","enterobaktérií","  mykobaktérií ","mykoplaziem","  pôvodcu tuberkulózy","  chlamydif","  leptospir","  súvisiaca s bunkovou stenou mykobaktérií"],
 },
 {
    numb: 58,
    question: "Pre exotoxiny je charakteristické:",
    answer: [" sú to proteíny"," viaceré sú termolabilné"," majú špecifický biologický účinok"," možno ich zvyčajne detoxifikovať bez zmeny antigénnosti"," účinkujú len na bunky, ktoré majú príslušný receptor"," neutralizáciu v napadnutom organizme zabezpečujú protilátky"],
    options: [" sú to proteíny"," viaceré sú termolabilné","mechanizmus účinku všetkých exotoxinov je rovnaký"," majú špecifický biologický účinok","sú súčasťou bunkovej steny gramnegatívnych baktérií"," možno ich zvyčajne detoxifikovať bez zmeny antigénnosti"," tvoria ich len grampozitívne a gramlabilné baktérie ","do prostredia sa uvoľit'ujú len pri rozpade bakteriálnej bunky"," účinkujú len na bunky, ktoré majú príslušný receptor"," neutralizáciu v napadnutom organizme zabezpečujú protilátky"],
 },
 {
    numb: 59,
    question: "Ktoré toxíny majú viastnosti superantigénov:",
    answer: [" TSST-1"," streptokokové pyrogénne exotoxiny"," stafylokokový exfoliatín"," stafylokokové enterotoxíny"],
    options: [" TSST-1","choleratoxin"," streptokokové pyrogénne exotoxiny"," stafylokokový exfoliatín"," pertusový toxín"," difterický toxín"," stafylokokové enterotoxíny"],
 },
 {
    numb: 60,
    question: "Difterický toxín:",
    answer: [" ireverzibilne poškodzuje proteínový metabolizmus napadnutej bunky "," predilekčne poškodzuje srdce, obličky a nervový systém "," inhibuje proteosyntézu v terčovej bunke"," tvorbu toxínu podmieňuje infekcia baktérie beta-fágom "],
    options: [" ireverzibilne poškodzuje proteínový metabolizmus napadnutej bunky ","usmrcuje výlučne neutrofilné leukocyty a makrofágy"," predilekčne poškodzuje srdce, obličky a nervový systém ","lyzuje cytoplazmatickú membránu cieľovej bunky ","dočasne inhibuje proteosyntézu v napadnutej bunke"," inhibuje proteosyntézu v terčovej bunke"," toxín pôsobi paralyzujúco na nervovo-svalovú platničku"," tvorbu toxínu podmieňuje infekcia baktérie beta-fágom ","z baktérie sa do organizmu uvoľní až po jej rozpade ","pôsobí výlučne lokálne v mieste tvorby pablán"],
 },
 {
    numb: 61,
    question: "Toxigenitu Corynebacterium diphtheriae v praxi dokazujeme: ",
    answer: [" precipitáciou exoproduktov baktérie s antitoxínom v agare "," u každého kmeňa C.diphteriae izolovaného od pacienta"," Elekovým testom"," dôkazom génu pre toxin"],
    options: ["aglutinačnou reakciou s C. diphtheriae"," precipitáciou exoproduktov baktérie s antitoxínom v agare ","imunoelektroforézou"," u každého kmeňa C.diphteriae izolovaného od pacienta"," toxín sa pri podozrení na diftériu nemusí dokazovať"," imunofluorescenčným testom"," Elekovým testom","len v epidemiologicky významných situáciách"," dôkazom génu pre toxin"],
 },
 {
    numb: 62,
    question: "Toxin Vibrio cholerae (enterotoxin):",
    answer: [" poškodzuje enzymatické systémy napadnutej bunky"," pôsobi len lokálne na epitelové bunky čreva s príslušným receptorom "," v enterocyte zvyšuje hladinu cAMP"," môže u neliečeného pacienta navodiť smrť dehydratáciou"],
    options: [" poškodzuje enzymatické systémy napadnutej bunky"," pôsobi len lokálne na epitelové bunky čreva s príslušným receptorom ","v epitelovej bunke selektívne zvyšuje hladinu cGMP"," v enterocyte zvyšuje hladinu cAMP","navodí hyposekréciu Na+, Cl- a FICO3- iónov do čreva ","aktivuje anafylak-tickú reakciu na povrchu črevnej sliznice ","poškodzuje membrány epitelových buniek črevnej sliznice"," môže u neliečeného pacienta navodiť smrť dehydratáciou"," spósobuje reverzibilné poškodenie napadnutej bunky ","pósobi neurotoxicky"],
 },
 {
    numb: 63,
    question: "Medzi bakteriálne exotoxíny s membranolytickým účinkom patria:",
    answer: [" alfa-toxín Clostridium perftingens"," beta-hemolyzíny streptokokov"," streptolyzín 0"," leukocidíny baktérií"," tetanolyzín Clostridium tetani"],
    options: [" alfa-toxín Clostridium perftingens"," beta-hemolyzíny streptokokov","lipopolysacharid gramnegatívnych baktérií"," streptolyzín 0"," enterotoxin Vibrio cholerae","shigatoxín","difterícký toxin"," leukocidíny baktérií"," tetanolyzín Clostridium tetani","enterotoxin Staphylococcus aureus"],
 },
 {
    numb: 64,
    question: "Ktoré baktérie produkujú neurotoxicky pôsobíace proteiny: ",
    answer: [" Clostridium tetani"," Clostrádium botulinum"],
    options: ["Streptococcus pyogenes"," Clostridium tetani"," Clostrádium botulinum"," Bacillus anthracis"," Bacillus cereus ","Streptococcus agalactiae"],
 },
 {
    numb: 65,
    question: "Tetanotoxin:",
    answer: [" patrí medzi neurotoxíny "," pôsobi na CNS"," klinicky sa jeho pôsobenie prejaví ako generalizovaná tetania "," inhibuje prenos vzruchov na tlmivých synapsách"," detoxifikáciou pripravime anatoxín pre imunizáciu"],
    options: [" patrí medzi neurotoxíny ","spôsobuje chabú paralýzu priečne pnkovaných svalov"," má dva antigénové typy"," pôsobi na CNS","účinkuje na nervovo-svalovej platničke"," klinicky sa jeho pôsobenie prejaví ako generalizovaná tetania ","zvyšuje syntézu acetylcholínu nervovou bunkou"," inhibuje prenos vzruchov na tlmivých synapsách"," detoxifikáciou pripravime anatoxín pre imunizáciu"],
 },
 {
    numb: 66,
    question: "Ktoré z uvedených toxinov patria medzi enterotoxiny:",
    answer: [" chokratoxin"," shigatoxín"],
    options: [" chokratoxin"," TSST-1"," erytrogénny toxín"," shigatoxín"," tetanospazmín","botulotoxín"," difterický toxín","endotoxín"],
 },
 {
    numb: 67,
    question: "Medzi dôležité faktory tvorby biofilmu patri",
    answer: [" adhézia baktérií na kolonizované povrchy"," interakcia baktérií s matrixovými proteínmi hostiteľa"," dostatok živín v prostredí kolonizovanom baktériami"," akumulácia biofilmu po prichytení baktérií k povrchu"," koordinovaná aktivita baktérií regulovaná quorum sensing systémami "],
    options: [" adhézia baktérií na kolonizované povrchy"," interakcia baktérií s matrixovými proteínmi hostiteľa"," prítomnosť protilátok proti bakteriálnym povrchovým antigénom"," dostatok živín v prostredí kolonizovanom baktériami"," akumulácia biofilmu po prichytení baktérií k povrchu"," tvorba peptidoglykánu bunkovej steny baktérii"," koordinovaná aktivita baktérií regulovaná quorum sensing systémami "],
 },
 {
    numb: 68,
    question: "Bakteriálny blofilm",
    answer: [" jeho matrix obsahuje bakteriálne interceluláme polysacharidové adhezíny"," jeho matrix obsahuje extracelulárne uvoľnené nukleové kyseliny"," jeho matrix obsahuje proteíny bakteriálneho aj hostiteľského pôvodu"," sa výbome tvorí na umelých biokompatibilných povrchoch "],
    options: [" jeho matrix obsahuje bakteriálne interceluláme polysacharidové adhezíny"," jeho matrix obsahuje prevažne fosfolipidy z bakteriálnych membrán"," jeho matrix obsahuje extracelulárne uvoľnené nukleové kyseliny"," jeho matrix obsahuje proteíny bakteriálneho aj hostiteľského pôvodu"," jeho matrix obsahuje prevažne mono- a disacharidy z prostredia baktérií"," sa výbome tvorí na umelých biokompatibilných povrchoch "," sa výbome tvorí na intaktnom endokarde"],
 },
 {
    numb: 69,
    question: "Biofilm",
    answer: [" pomáha baktériám odolávať pósobeniu antimikrobiálnych liečiv"," pomáha baktériám odolávať nepriaznivým faktorom prostredia"," pomáha baktériám zachovať si vitalitu počas antibiotickej terapie "," je ložiskom, z ktorého baktérie osídľujú hostiteľa po antibiotickej terapii"," je ložiskom, z ktorého sa baktérie šíria do ostatných lokalít organizmu "],
    options: [" zvyšuje citlivosť baktérií na antimikrobiálne liečivá"," znižuje rezistenciu baktérií na antimikrobiálne liečivá"," pomáha baktériám odolávať pósobeniu antimikrobiálnych liečiv"," pomáha baktériám odolávať nepriaznivým faktorom prostredia"," pomáha baktériám zachovať si vitalitu počas antibiotickej terapie ","pri disperzii sa baktérie koncentrujú výlučne v okolí biofilmu"," je ložiskom, z ktorého baktérie osídľujú hostiteľa po antibiotickej terapii"," je ložiskom, z ktorého sa baktérie šíria do ostatných lokalít organizmu "],
 },
 {
    numb: 70,
    question: "Pritomnosť biofilmu je typická pre",
    answer: [" infekcie chronických rán"," endokarditídy"," chronické osteomyelitídy"," katétrové infekcie a periimplantitídy"," chronické urogenitálne infekcie"],
    options: [" akútne tonzilitídy"," infekcie chronických rán"," endokarditídy"," chronické osteomyelitídy"," katétrové infekcie a periimplantitídy"," chronické urogenitálne infekcie","hnačky vyvolané bakteriálnymi toxínmi","septické meningitídy novorodencov"],
 },
 {
    numb: 71,
    question: "Pri sterilizácii:",
    answer: [" musia byt' zničené všetky mikroorganizmy a ich spóry"," použivame fyzikálne aj chemické metódy"," musia byť zničené alebo odstránené aj všetky vírusy, huby a parazity"," používame špeciálne postupy na inaktiváciu priónov"],
    options: [" musia byť zničené všetky baktérie okrem nepatogénnych"," musia byt' zničené všetky mikroorganizmy a ich spóry"," sú zničené minimálne všetky vegetatívne formy mikroorganizmov"," používame výlučne fyzikálne metódy"," použivame fyzikálne aj chemické metódy"," sterilizáciu dosiahneme varom trvajúcim minimálne 180 minút"," musia byť zničené alebo odstránené aj všetky vírusy, huby a parazity"," chemicky dosiahneme len dezinfekciu, nie sterilizáciu"," používame špeciálne postupy na inaktiváciu priónov"],
 },
 {
    numb: 72,
    question: "Ilir Sterilizáciu môžeme dosiahnúť:",
    answer: [" pósobením etylénoxidu"," pôsobením UV-žiarenia (len povrchu a vzduchu)"," účinkom gama žiarenia"," parou pod tlakom v autokláve"," pôsobením pár kyseliny peroctovej"],
    options: [" pósobením etylénoxidu"," pôsobením UV-žiarenia (len povrchu a vzduchu)"," účinkom gama žiarenia"," suchým tepiom v autoldáve"," parou pri vare za normálneho tlaku"," parou pod tlakom v autokláve"," filtráciou filtrom s pórmi 0,45 pim"," infrazvukom",". dlhším povarením v destilovanej vode"," pôsobením pár kyseliny peroctovej"],
 },
 {
    numb: 73,
    question: "Na. sterilizáciu môleme použiť:",
    answer: [" etylénoxíd"," autokláv"," paru pod tlakom"," vypaľovanie v plameni"," pary kyseliny peroctovej"],
    options: [" Ajatín"," etylénoxíd"," autokláv"," paru pod tlakom","Septonex"," vypaľovanie v plameni"," Chloramín B","prúdiacu paru","180-minútový var pri 100°C"," pary kyseliny peroctovej"],
 },
 {
    numb: 74,
    question: "Na dezinfekeiu kože živého organizmu sa pouliva:",
    answer: [" Ajatín"," Spitaderm"," 70 % etanol"," jódová tinktúra"," jódpovidon"],
    options: [" Ajatín"," amfotericín B"," ampicilín","garna žiarenie"," Spitaderm"," 70 % etanol"," 40 % Persteril"," etylénoxid"," jódová tinktúra"," jódpovidon"],
 },
 {
    numb: 75,
    question: "Medzi dezinfekčné činidlá patria:",
    answer: [" Ajatín"," Chloramín B"," Septonex"," chlórnan sodný "," preparáty s obsahom jódu"," chlorhexidín"," oktenidín"],
    options: ["spektinomycín"," Ajatín"," Chloramín B"," Septonex"," amfotericín B"," chlórnan sodný ","neomycín"," preparáty s obsahom jódu"," chlorhexidín"," oktenidín"],
 },
 {
    numb: 76,
    question: "Komensálne mikroorganizmy na slizniciach:",
    answer: [" inhibujú množenie patogénnych mikroorganizmov"," súťažia s patogénmi pri adhézii na epitelové bunky"," produkujú biogénne faktory (napr. vítamíny)"," sú súčasťou nešpecifickej imunity"," môžu meniť pH prostredia a inhibovať tak rast patogénov (napr. laktobacily)"],
    options: [" inhibujú množenie patogénnych mikroorganizmov"," súťažia s patogénmi pri adhézii na epitelové bunky"," produkujú biogénne faktory (napr. vítamíny)"," sú súčasťou nešpecifickej imunity"," môžu meniť pH prostredia a inhibovať tak rast patogénov (napr. laktobacily)","bránia prenosu plazmidov medzi patogénnymi mikroorganizmami","spotrebovávajú kyslík potrebný pre patogénne mikroorganizuly","na rozdiel od patogénov neprodukujú bakteriocíny"],
 },
 {
    numb: 77,
    question: "Kvapôčkovou nákazou sa pravidelne prenášajú: ",
    answer: [" mykopiazmová pneumónia"," diftéria"," epidemická meningitída"," čierny kašeľ"," tuberkulóza"," záškrt"," mor"],
    options: ["impetigo"," mykopiazmová pneumónia","lymská borelióza"," diftéria"," epidemická meningitída"," čierny kašeľ"," tuberkulóza"," záškrt"," mor"," erysipeloid"],
 },
 {
    numb: 78,
    question: "Prameňom pôvodeu mikrobiálnej infekcie môže byť:",
    answer: [" chorý človek"," choré zvieratá"," bacilonosič"," infikovaný alebo kolonizovaný hostíteľ"],
    options: [" chorý človek"," choré zvieratá"," bacilonosič","prachové častice"," voda","hmyz ako pasívny prenášač"," kontaminované predmety"," infikovaný alebo kolonizovaný hostíteľ"],
 },
 {
    numb: 79,
    question: "Medzi cesty prenosu rnikrobiálnej infekcie zaraďujeme:",
    answer: [" vzdušnú kvapôčkovú"," kontaminovanú vodu"," kontaminovanú pôdu a predmety"," hmyzie vektory"," pohlavný styk"," transplacentálny prenos"," prenos krvou (transfúziu) a transplantátmi"],
    options: [" vzdušnú kvapôčkovú"," choré zviera"," kontaminovanú vodu"," kontaminovanú pôdu a predmety","bacilonosičov"," hmyzie vektory"," pohlavný styk"," transplacentálny prenos"," genetickú transdukciu"," prenos krvou (transfúziu) a transplantátmi"],
 },
 {
    numb: 80,
    question: "Interhumánny kontakt je potrebný pri prenose:",
    answer: [" chlamýdiovej uretritídy"," syfilisu"," kvapavky"," Inäkkého vredu"," šarlachu"],
    options: [" škvrnitého týfusu"," chlamýdiovej uretritídy"," syfilisu"," kvapavky"," Inäkkého vredu","psitakózy"," Q-horúčky","listeriózy"," šarlachu"],
 },
 {
    numb: 81,
    question: "Patogenita predpokladá schopnosť mikroorganizmu:",
    answer: [" množit' sa na povrchu sliznice hostiteľa"," preniknúť do organizmu hostiteľa"," vyvolať ochorenie u vnimavého hostiteľa"," prekonať vrodené obranné mechanizmy hostiteľa"," prenikať do vnímavých buniek hostíteľa a množiť sa v nich "],
    options: [" množit' sa na povrchu sliznice hostiteľa"," preniknúť do organizmu hostiteľa"," vyvolať ochorenie u vnimavého hostiteľa","meniť zioženie normálnej bakteriálnej flóry hostiteľa"," prekonať vrodené obranné mechanizmy hostiteľa"," poškodzovať hostiteľa (štruktúry alebo funkcie organizmu)","vyvolať u hostiteľa špecifickú imunitnú odpoved'"," prenikať do vnímavých buniek hostíteľa a množiť sa v nich ","pretrvávať v organizme aj po navodení špecifickej imunity "],
 },
 {
    numb: 82,
    question: "Vznik ochorenia miiže/môžu podmieňovať:",
    answer: [" imunopatologické mechanizmy vyvolané infikujúcim mikroorganizmom"," bakteriálne exotoxíny"," endotoxíny gramnegatívnych baktérií"," tvorba neuraminidázy a fibrinolyzínu"],
    options: ["lyzozómové enzýmy aeróbnych baktérií"," imunopatologické mechanizmy vyvolané infikujúcim mikroorganizmom"," bakteriálne exotoxíny"," tvorba spór sporulujúcimi mikroorganizmami"," endotoxíny gramnegatívnych baktérií"," tvorba neuraminidázy a fibrinolyzínu"," tvorba bičficov","R-plazmidy baktérií","bakteriocíny baktérií","faktor F baktérií"],
 },
 {
    numb: 83,
    question: "Pre vzťah medzi mikroorganizmom a hostiteľom je charakterlstické:",
    answer: [" pri kolonizácii chýba imunitná odpoved' hostiteľa na mikroorganizmus"," pri infekcii sa u imunokompetentného hostiteľa vytvorí imunitná odpoved' proti mikroorganizmu"," za prejavy ochorenia hostiteľa mďže byt' zodpovedná aj vlastná imunitná odpoved'"," kolonizácia nepatrí medzi formy parazitizmu"," infekcia nemusí byt' sprevádzaná klinickými príznakmi ochorenia "," pň očkovaní vyvoláme infekciu, nie však typické ochorenie "],
    options: [" pri kolonizácii chýba imunitná odpoved' hostiteľa na mikroorganizmus"," pri infekcii musí byt' poškodené tkanivo hostiteľa"," pri infekcii sa u imunokompetentného hostiteľa vytvorí imunitná odpoved' proti mikroorganizmu"," za prejavy ochorenia hostiteľa mďže byt' zodpovedná aj vlastná imunitná odpoved'"," kolonizácia nepatrí medzi formy parazitizmu"," infekcia nemusí byt' sprevádzaná klinickými príznakmi ochorenia ","pri očkovaní využívame kolonizáciu hostiteľa vakcinačným krneň'om"," pň očkovaní vyvoláme infekciu, nie však typické ochorenie "],
 },
 {
    numb: 84,
    question: "Predĺžená kultivácia je potrebná pri dôkaze:",
    answer: [" Mycobacterium tuberculosis"," pôvodcov mykobakterióz"," Brucella spp."," Actinomyces spp."],
    options: ["Sahnonella Typhi"," Mycobacterium tuberculosis"," pôvodcov mykobakterióz"," Brucella spp."," Haemophilus influenzae"," Actinomyces spp.","Streptococcus pyogenes"," Staphylococcus aureus"],
 },
 {
    numb: 85,
    question: "Baktérie identifikujeme na základe:",
    answer: [" tvaru a usporiadania baktérií (koky, paličky, špirály)"," farbiteľnosti podľa Grama"," oxidázového testu"," farbiteľnosti podľa Ziehla-Neelsena"," tvorby spór"," pohyblivosti"],
    options: [" tvaru a usporiadania baktérií (koky, paličky, špirály)"," farbiteľnosti podľa Grama","tvorby a chemického zloženie puzdra"," oxidázového testu","schopnosti rásť na krvnom agare"," farbiteľnosti podľa Ziehla-Neelsena"," tvorby spór"," pohyblivosti"," prítomnosti plazmidov"," tvorby exotoxinov"],
 },
 {
    numb: 86,
    question: "Streptokoky:",
    answer: [" základné delenie je podľa polysacharidovej substancie"," proteín M má antifagocytámu aktivitu"," diagnostickou pôdou je krvný agar"," beta hemolyzíny bežne produkujú streptokoky skupiny A, B, C, F a G"," streptokoky skupiny A sú pravidelne citlivé na penicilín"],
    options: [" všetky streptokoky sa dajú typizovať podľa Lancefieldovej"," základné delenie je podľa polysacharidovej substancie"," proteín M má antifagocytámu aktivitu","proteín M je faktorom virulencie streptokokov skupiny D"," po prekonanom ochorení hladina antistreptolyzínu S stúpa ","pre mikroskopický obraz sú typické zhluky G+ kokov"," diagnostickou pôdou je krvný agar"," beta hemolyzíny bežne produkujú streptokoky skupiny A, B, C, F a G"," streptokoky skupiny A sú pravidelne citlivé na penicilín"],
 },
 {
    numb: 87,
    question: "Medzi faktory virulencie ►treptococcus pyogenes patria:",
    answer: [" hyaluronidáza"," streptokináza"," deoxyribonukleáza B"," erytrogénne toxíny"],
    options: [" hyaluronidáza","zhiukovací faktor"," streptokináza"," deoxyribonukleáza B"," erytrogénne toxíny"," kord faktor","lipopolysacharid","enterotoxin"," pyocyanín"],
 },
 {
    numb: 88,
    question: "Pre hemolytické streptokoky nepatriace do skupiny A platí:",
    answer: [" skupina C nemá proteín M"," enterokoky môžu spôsobovať aj beta hemolýzu"," skupiny C a G môžu produkovať streptolyzín 0"," testom CAMP dokážeme exoprodukt potencujúci hemolyzín (beta toxin) S.aureus"," S. agalactiae môže kolonizovať vaginálnu sliznicu"],
    options: ["S. agalactiae nie je patogénny pre človeka"," skupina C nemá proteín M"," môžu byt' podobne ako skupina A pôvodcami reumatickej horáčky"," enterokoky môžu spôsobovať aj beta hemolýzu"," skupiny C a G môžu produkovať streptolyzín 0"," testom CAMP dokážeme exoprodukt potencujúci hemolyzín (beta toxin) S.aureus"," S. agalactiae môže kolonizovať vaginálnu sliznicu"," infekcia S. agalactiae sa prejaví zvýšením titra ASLO","skupina G je pôvodcom postreptokokovej glomerulonefritídy","faktorom virulencie je proteín A"],
 },
 {
    numb: 89,
    question: "Príčinou opakovaných ochorení vyvolaných Streptococcus pyogenes je: ",
    answer: [" protektívny proteín M má veľa antigénnych typov"," infekcia inýrn typom S.pyogenes, než voči ktorému má hostiteľ protilátky "," pri opakovaní šarlachu antigénna róznorodosť erytrogénneho toxinu"],
    options: [" typicky epidemický výskyt infekcil v populácii"," protektívny antigén nie je dostatočne imunogénny","postinfekčná imunita je krátkodobá"," protektívny proteín M má veľa antigénnych typov","protektívny proteĺn T má viacero antigénnych typov"," infekcia inýrn typom S.pyogenes, než voči ktorému má hostiteľ protilátky ","neschopnosť organizmu vytvoriť protilátky proti hemolyzinu S ","nedostatočná tvorba protilátok proti streptolyzinu 0"," pri opakovaní šarlachu antigénna róznorodosť erytrogénneho toxinu"],
 },
 {
    numb: 90,
    question: "Poststreptokokové ochorenia:",
    answer: [" diagnosticky sa opierame o vyšetrenie hladín ASLO a anti-DNázy"," príčinou sú krížovo reagujúce protilátky, ktoré vznikajú počas infekcie S. pyogenes"," autoĺmúnna reakcia je indukovaná antigénmi S. pyogenes"],
    options: ["sú bezprostredným pokračovaním streptokokovej inťekcie"," reumatická horúčka vzniká po faryngeálnej infekcii S. agalactiae","príčinou je precitlivenosť I. typu na antigény S. pyogenes","vyskytujú sa len po manifestovanej in.fekcii so šarlachovou vyrážlou"," diagnosticky sa opierame o vyšetrenie hladín ASLO a anti-DNázy"," u chorého vyšetríme hladinu antistreptolyzinu S v sére ","postihnuté sú výlučne obličky a srdce"," príčinou sú krížovo reagujúce protilátky, ktoré vznikajú počas infekcie S. pyogenes"," autoĺmúnna reakcia je indukovaná antigénmi S. pyogenes"],
 },
 {
    numb: 91,
    question: "Do ktorej skupiny patrí a ako môžeme určiť Streptococcus agalactiae:",
    answer: [" B, test CAMP je pozitívny "," B, dókaz skupinového antigénu latexovou aglutináciou"," B, bacitracínový test je negatívny"],
    options: [" B, test CAMP je pozitívny ","B, Neufeldovým testom ","A, test CAMP je pozitívny"," B, dókaz skupinového antigénu latexovou aglutináciou"," A, Elekov test je pozitívny"," B, bacitracínový test je negatívny"," A, bacitracinový test je pozitívny"],
 },
 {
    numb: 92,
    question: "Na ziklade pozitivity testu CAMP určujeme:",
    answer: [" Streptococcus agalactiae"," produkciu faktora zosilujikeho hemolýzu Staphylococcus aureus "," beta-hemolytické streptokoky skupiny B"],
    options: [" Arcanobacteruim haemolyficum"," Streptococcus agalactiae"," produkciu faktora zosilujikeho hemolýzu Staphylococcus aureus ","schopnosť kmehov Staphylococcus aureus tvoriť beta-laktamázu"," beta-hemolytické streptokoky skupiny B"," beta-hemolytické streptokoky skupiny D"," Staphylococcus epidermidis"],
 },
 {
    numb: 93,
    question: "Titer antistreptolyzínu 0 využívame pri diagnostike: ",
    answer: [" sterilných následkov streptokokových infekcil"," poststreptokokovej chorey minor"," reumatickej horúčky"," akútnej glomerulonefi-itídy"," poststreptokokovej myokarditítidy"],
    options: ["erysipeloidu"," sterilných následkov streptokokových infekcil"," poststreptokokovej chorey minor"," reumatickej horúčky","záškrtu"," akútnej glomerulonefi-itídy","stafylokokovej enterokolitídy"," poststreptokokovej myokarditítidy","epidemickej meningitídy"],
 },
 {
    numb: 94,
    question: "Poststreptokokové ochorenia diagnostikujeme pomocou:",
    answer: [" stanovenia antistreptolyzínu O"," zisťovanim sedimentácie (pornocné vyšetrenie)"," stanovenia antistreptodornázy (antideoxyribonukleázy B)"," stanovenia hladiny CRP (C-reaktívny proteín, nešpecifický ukazovater zápalu)"],
    options: [" stanovenia antistreptolyzínu O"," stanovenia antistreptolyzinu S"," stanovenia voľnej koagulázy"," zisťovanim sedimentácie (pornocné vyšetrenie)"," stanovenia antistreptodornázy (antideoxyribonukleázy B)"," bacitracínového testu"," stanovenia hladiny CRP (C-reaktívny proteín, nešpecifický ukazovater zápalu)","stanovenia protilátok proti erytrogénnemu toxínu"],
 },
 {
    numb: 95,
    question: "Za ešte normálnu hodnotu ASLO u deti by ste považovali hladinu:",
    answer: [" lOj "," 128j"," 196j"," 160j "],
    options: [" lOj "," 128j"," 196j"," 160j ","900j"," 375j ","600j ","500j ","380j"],
 },
 {
    numb: 96,
    question: "Pri diagnostike reumatickej horúčky odoberáme na vyšetrenie:",
    answer: [" krv na sérologické vyšetrenie antistreptolyzínu O"," krv na sérologické vyšetrenie antistreptodomázy (antideoxyribonukleázy B)"," krv na stanovenie hladiny CRP"],
    options: ["výter z tonzíl na dôkaz prítomnosti Staphylocaccus aureus"," krv na hemokultiváciu"," krv na sérologické vyšetrenie antistreptolyzínu O"," krv na sérologické vyšetrenie antistreptodomázy (antideoxyribonukleázy B)","výter z laryngu na dôkaz Corynebacterium diphtheriae","spútum na kvantitatívne vyšetrenie"," punktáty z postihnutých klbov","stolicu na dôkaz Yersinia enterocolitica"," krv na stanovenie hladiny CRP","krv na stanovenie hladiny antistrepto1yzínu S"],
 },
 {
    numb: 97,
    question: "Streptococcus pneumoniae:",
    answer: [" popri pneumónii spôsobuje otitídy a meningitídy u detí"," základným faktorom virulencie je polysacharidové puzdro"," protilátky proti puzdrovým antigénorn sú protektívne"," u staršich ľudi môže častejšie vyvolať pneumóniu"," puzdro má antifagocytárny účinok"," prameňom infekcie je vždy človek"," k faktorom virulencie patrí schopnosť štiepiť povrchový IgA"],
    options: [" popri pneumónii spôsobuje otitídy a meningitídy u detí"," základným faktorom virulencie je polysacharidové puzdro"," produkuje neurotoxický proteín"," protilátky proti puzdrovým antigénorn sú protektívne"," u staršich ľudi môže častejšie vyvolať pneumóniu"," puzdro má antifagocytárny účinok"," prameňom infekcie je vždy človek"," k faktorom virulencie patrí schopnosť štiepiť povrchový IgA","všetky kmene sú citlivé na penicilín","prežíva v prostredí vd'aka odolným spóram"],
 },
 {
    numb: 98,
    question: "Identifikáciu Staphylococcus aureus robíme:",
    answer: [" dókazom produkcie plazmakoagulázy"," dôkazom zhlukovacieho faktora","  dókazom tvorby DN-ázy","  dókazom tvorby hyaluronidázy","  dókazom tvorby hemolyzínov na krvnom agare","  dôkazom proteínu A"],
    options: [" Elekovou metódou"," dókazom produkcie plazmakoagulázy"," dôkazom zhlukovacieho faktora","  simultánnym dôkazom proteínu A a zhlukovacieho faktora latexovou aglutináciou ","stanovením CRP v sére pacienta","dôkazom tvorby ASLO pri experimentálnej infekcii","  dókazom tvorby DN-ázy","  dókazom tvorby hyaluronidázy","  dókazom tvorby hemolyzínov na krvnom agare","  dôkazom proteínu A"],
 },
 {
    numb: 99,
    question: "Staphylococcus aureus:",
    answer: [" môže produkovať termostabilné enterotoxíny"," pri infekcii sa typicky tvoria abscesy"," patrí medzi pôvodcov nozokomiálnych nákaz"," často sa vyskytuje v nosohltane zdravých nosičov","  môže spósobiť postantibiotickú enterokolitídu","  v terapii infekcii spôsobených MRSA sú z betalaktámov účinné len cefalosporiny 5. generácie"],
    options: [" môže produkovať termostabilné enterotoxíny","faktorom virulencie je endotoxin"," pri infekcii sa typicky tvoria abscesy"," patrí medzi pôvodcov nozokomiálnych nákaz"," často sa vyskytuje v nosohltane zdravých nosičov","je štandardne citiivý na peniciiin","  je pôvodcom autoimúnnej myokardititídy","  môže spósobiť postantibiotickú enterokolitídu","  v terapii infekcii spôsobených MRSA sú z betalaktámov účinné len cefalosporiny 5. generácie"],
 },
 {
    numb: 100,
    question: "Corynebacterium diphthe•iae:",
    answer: ["  aktívna imunizácia spočíva v navodení antitoxickej imunity ","  toxín Účinkuje inhibiciou proteosyntézy v cieľovej bunke","  pri dôkaze toxigenity používame imunodifáziu (Elekov test) ","  účinok toxinu na bunku je nekrotický","  toxín pôsobí najmä neuro-, nefto- a kardiotoxicky"],
    options: ["izolácia mikroorganizmu z materiálu vždy potvrdzuje diagnázu diftérie","  aktívna imunizácia spočíva v navodení antitoxickej imunity ","exotoxín sa uvoľňuje do okolia až po rozpade baktérie","  toxín Účinkuje inhibiciou proteosyntézy v cieľovej bunke","  pri dôkaze toxigenity používame imunodifáziu (Elekov test) ","invazivita je podmienená lyzogénnou konverziou beta-fágom ","letálny toxín pósobi výlučne lokálne (v mieste zápalu)","  účinok toxinu na bunku je nekrotický","  toxín pôsobí najmä neuro-, nefto- a kardiotoxicky"],
 },
 {
    numb: 101,
    question: "Listeria monocytogenes:",
    answer: ["  mikroorganizmus prechádza placentou a poškodzuje plod ","  faktorom virulencie je listeriolyzín","  listéria je grampozitívna palička","  patrí medzi póvodcov zoonóz","   rastie aj pri teplote 4 °C","  patrí medzi fakultatívne intracelulárne baktérie"],
    options: ["  faktorom virulencie je puzdro s antifagocytárnym úč'inkom","  mikroorganizmus prechádza placentou a poškodzuje plod ","prekonanie ochorenia zanecháva doživotnú imunitu","  faktorom virulencie je listeriolyzín","  listéria je grampozitívna palička","  patrí medzi póvodcov zoonóz","prameňom nákazy je najčastejšie človek","   rastie aj pri teplote 4 °C","  mikrób tvorí centrálne uloženú spáru","  patrí medzi fakultatívne intracelulárne baktérie"],
 },
 {
    numb: 102,
    question: "Erysipelothrbc rhusiopathiae:",
    answer: [" j e fakultatívne anaeróbna grampozitívna palička, ktorá netvorí spóry","  patrí medzi pôvodcov zoonóz","  najčastejším prameňom nálcazy je ošipaná","  v klinickom obraze prevažujú kožné lézie a miestne artritídy","  profesionálna nákaza sa prenáša kontaktom so zvieraťom"," mikroorganizmus je citlivý na penicilín, cefalosporíny a klindamycín"," difúzny charakter kožných léziĺ podmieňuje neuraminidáza"],
    options: [" j e fakultatívne anaeróbna grampozitívna palička, ktorá netvorí spóry","  patrí medzi pôvodcov zoonóz","  najčastejším prameňom nálcazy je ošipaná","  v klinickom obraze prevažujú kožné lézie a miestne artritídy","  profesionálna nákaza sa prenáša kontaktom so zvieraťom","  prekonanie in.fekcie zanecháva trvalú imunitu"," často vyvoláva atypickú pneumóniu"," mikroorganizmus je citlivý na penicilín, cefalosporíny a klindamycín"," základná diagnostika je nepriama (sérologická)"," difúzny charakter kožných léziĺ podmieňuje neuraminidáza"],
 },
 {
    numb: 103,
    question: "Haemophilus influenzae vyvoláva obvylkle:",
    answer: [" bakteriálne infekcie horných dýchacich orgánov"," meningitídy"," otitídy"," osteomyelitídy detí"," superinfekcie dýchacich ciest"," infekcie u detí"],
    options: [" chripku"," bakteriálne infekcie horných dýchacich orgánov"," meningitídy","mäkký vred"," otitídy"," osteomyelitídy detí","uretritídy"," reumatickú horúčku"," superinfekcie dýchacich ciest"," infekcie u detí"],
 },
 {
    numb: 104,
    question: "Haemophilus:",
    answer: [" H. influenzae vyvoláva infekcie horných ciest dýchacich"," k faktorom virulencie patrí puzdro"," Hinfluenzae poškodzuje riasinkový epitel dýchacich ciest"," mikroorganizmus štiepi slizničný IgA"," infekcia H.ducreyi patrí medzi venerické nákazy "],
    options: ["je nepohyblivá pleomorfná grampozitívna baktéria ","dobre rastie na krvnom agare"," H. influenzae vyvoláva infekcie horných ciest dýchacich"," k faktorom virulencie patrí puzdro"," Hinfluenzae poškodzuje riasinkový epitel dýchacich ciest"," mikroorganizmus štiepi slizničný IgA"," spôsobuje meningitídy s epidemickým výskytom"," infekcia H.ducreyi patrí medzi venerické nákazy ","H.ducreyi je póvodcom pohlavne prenosnej uretritídy"],
 },
 {
    numb: 105,
    question: "N. gonorrhoeae a N. meningitidis rastie na:",
    answer: [" čokoládovom agare"," GC agare"," špeciálnych kultivačných pôdach (sú rastovo náročné)"],
    options: [" Endovej pôde"," čokoládovom agare"," tioglykolátovej pôde"," LA5wensteinovej pôde"," GC agare"," Sabouraudovom agare"," dezoxycholátcitrátovej pôde"," špeciálnych kultivačných pôdach (sú rastovo náročné)"],
 },
 {
    numb: 106,
    question: "Pri podozrení na kvapavku a jej komplikácie u ženy odoberáme:",
    answer: [" punktát zo zápalovo zmeneného kíbu pri diseminovanej forme"," krv na hemokultiváciu pri diseminovanej forme"," výter z cervixu"," výter z uretry"," materiál z miesta infekcie do transportného média (napr. Stuartovho)"],
    options: [" punktát zo zápalovo zmeneného kíbu pri diseminovanej forme"," excízie z tkaniva"," krv na hemokultiváciu pri diseminovanej forme","rutinne krv na dókaz špecifických protilátok"," výter z cervixu"," výter z uretry","moč suprapubickou punkciou"," materiál z miesta infekcie do transportného média (napr. Stuartovho)"],
 },
 {
    numb: 107,
    question: "Neisseria gonorrhoeae:",
    answer: [" prirodzeným hostiteľom je človek"," mikroorganizmus poškodzuje epitelové bunky sliznice "," mikroskopické vyšetrenie má diagnostický význam"," kultivačne je vel'mi náročná"," lepšie rastie pri zvýšenej tenzii CO2"," izoláciu povinne hlásime (venerické ochorenie)"],
    options: [" prirodzeným hostiteľom je človek","bežne sa prenáša aj kontaminovanými predmetmi"," mikroorganizmus poškodzuje epitelové bunky sliznice ","prekonaníe ochorenia zanecháva spoľahlivú dlhodobú imunitu"," mikroskopické vyšetrenie má diagnostický význam","je vždy citlivá na penicilín"," kultivačne je vel'mi náročná"," lepšie rastie pri zvýšenej tenzii CO2"," izoláciu povinne hlásime (venerické ochorenie)"],
 },
 {
    numb: 108,
    question: "Neisseria gonorrhoeae:",
    answer: [" produkuje proteázy, ktoré štiepia slizničný IgA"," faktorom virulencie je endotoxin"," pre antigénovú variabilitu nie je vylúčená reinfekcia antigénovo-od1išným kmeňom "],
    options: ["faktorom virulencie sú fimbrie"," produkuje proteázy, ktoré štiepia slizničný IgA","faktorom virulencie je proteín A"," faktorom virulencie je endotoxin"," pred fagocytózou ju chráni slizová vrstva"," za adhezivitu zodpovedá kyselina teichoová v bunkovej stene"," pre antigénovú variabilitu nie je vylúčená reinfekcia antigénovo-od1išným kmeňom "," ochorenie potvrdíme dôkazom protilátok testom ELISA"],
 },
 {
    numb: 109,
    question: "Neisseria meningitidis:",
    answer: [" faktorom virulencie je polysacharidové puzdro"," za toxický účinok zodpovedá lipooligosacharid"," popri epidemickom je možný aj sporadický výskyt meningitídy"," na vyšetrenie odoberáme likvor, krv a nazofaryngeálny výter "," antigény pôvodcu dokážeme priamo v likvore latexovou aglutináciou"],
    options: [" faktorom virulencie je polysacharidové puzdro"," za toxický účinok zodpovedá lipooligosacharid","tvorí membranotoxický proteín"," popri epidemickom je možný aj sporadický výskyt meningitídy"," na vyšetrenie odoberáme likvor, krv a nazofaryngeálny výter ","mikroskopické vyšetrenie nemá diagnostický význam ","nazofaryngeálne nosičstvo nie je epidemiologicky významné"," antigény pôvodcu dokážeme priamo v likvore latexovou aglutináciou"," pri meningitíde v likvore prev 'ažujú mononukleárne leukocyty ","meningitída má aseptický charakter"],
 },
 {
    numb: 110,
    question: "Enterobaktérie:",
    answer: [" Shigella dysenžeriae sérotyp 1 tvorí exotoxin"," „Vi\" antigén patrí k mikropuzdrovým antigénom"," pri, sérotypizácii sa v praxi využíva aglutinácia "],
    options: [" salmonelózy sú vždy generalizovaným ochorením","typhus abdominalis patrí k zoonózam"," Shigella dysenžeriae sérotyp 1 tvorí exotoxin","0 antigén patrí k puzdrovým antigénom bunky"," „Vi\" antigén patrí k mikropuzdrovým antigénom"," shigely sú potenciálne patogénne"," všetky druhy patria k normálnej bakteriálnej flóre čreva ","faktorom viru1encie je výlučne enterotoxin"," pri, sérotypizácii sa v praxi využíva aglutinácia ","spôsobujú výlučne ochorenia gastrointestinálneho traktu"],
 },
 {
    numb: 111,
    question: "Escherichia coli:",
    answer: [" môže vyvolať novorodenecké meningitídy (najčastejšie typ Kl)"," enterotoxiny, kolicíny a filnbrie sú často kódované plazmidmi"," niektoré kmene tvoria hemolyzín"," enteroinvazívne E.cofi móžu vyvolať krvavé hnačky"," enteropatogénne kmene vyvolávajú nozokomiálne infekcie u malých detí"," nepatrí k normálnej flóre čreva u novorodenca"],
    options: [" enteropatogénne E. coli prenikajú stenou črevnej sliznice"," môže vyvolať novorodenecké meningitídy (najčastejšie typ Kl)"," enterotoxiny, kolicíny a filnbrie sú často kódované plazmidmi"," niektoré kmene tvoria hemolyzín"," enteropatogénne E. coli tvoria enterotoxíny"," enteroinvazívne E.cofi móžu vyvolať krvavé hnačky"," enteropatogénne kmene vyvolávajú nozokomiálne infekcie u malých detí"," nepatrí k normálnej flóre čreva u novorodenca","faktorom virulencie je hyaluronidáza","pri ochorení odoberáme krv na sérologické vyš'etrenie protilátok"],
 },
 {
    numb: 112,
    question: "Prameňom infekcie pri brušnom týfuse je:",
    answer: [" chorý človek"," bacilonosič"],
    options: [" zviera"," chorý človek"," bacilonosič","voda kontaminovaná rnočom drobných hlodavcov"," ektoparazity hlodavcov"," potraviny","vajféka","výkaly domácich zvierat"],
 },
 {
    numb: 113,
    question: "Salmonelové infekcie — pôvodcovia a prenos:",
    answer: [" S. Enteritidis, požitím kontaminovanej potravy"," S. Typhi, S. Paratyphi A,B,C, vodou"," S. Enteritidis, S. Typhimurium, vodou"," primárne zoopatogénne salmonely, potravinami, vodou"," primárne zoopatogénne salmonely, fekálno-orálne, potravinami a vodou "," primárne zoopatogénne salmonely, vajíčkami infikovanej hydiny"," primárne zoopatogénne salmonely, mliekom infikovaných zvierat"],
    options: [" S. Enteritidis, požitím kontaminovanej potravy"," S. Typhi, S. Paratyphi A,B,C, vodou"," S. Enteritidis, S. Typhimurium, vodou"," primárne zoopatogénne salmonely, potravinami, vodou"," primárne zoopatogénne salmonely, fekálno-orálne, potravinami a vodou ","S. Enteritidis, kvapôčkovou infekciou"," primárne zoopatogénne salmonely, vajíčkami infikovanej hydiny"," primárne zoopatogénne salmonely, mliekom infikovaných zvierat"," Salmonella Paratyphi, transplacentálne"],
 },
 {
    numb: 114,
    question: "Yersinia enterocolitica môže spôsobiť ochorenia:",
    answer: [" hnačky"," enterokolitídu s apendicitíde podobnou mezenteriálnou lymfadenitídou"," sepsu"," erythema nodosum u dospelých"," reaktívnu polyartritídu"],
    options: [" hnačky"," enterokolitídu s apendicitíde podobnou mezenteriálnou lymfadenitídou"," sepsu"," erythema nodosum u dospelých"," reaktívnu polyartritídu","sinusitídu","impetigo"," orchitídu"],
 },
 {
    numb: 115,
    question: "Pseudomonas aeruginosa:",
    answer: [" je potenciálne patogénna baktéria"," často vyvoláva pneumónie u pacientov s cystickou fibrózou"," môže vyvolať postantibiotickú enterokolitídu"," móže sa vyskytovať v bakteriálnej flóre zdravého človeka"," faktormi virulencie sú proteázy, exotoxiny a sliz"," patrí k pôvodcom nozokomiálnych nákaz"," produkuje bakteriocíny a pigmenty"],
    options: [" je potenciálne patogénna baktéria"," často vyvoláva pneumónie u pacientov s cystickou fibrózou"," môže vyvolať postantibiotickú enterokolitídu"," móže sa vyskytovať v bakteriálnej flóre zdravého človeka"," faktormi virulencie sú proteázy, exotoxiny a sliz","niektoré kmene bývajú citlivé na penicilín"," nemocničné kmene sú dobre citlivé na antibiotiká"," patrí k pôvodcom nozokomiálnych nákaz"," produkuje bakteriocíny a pigmenty","patrí medzi fakultatívne anaeróbne gramnegatívne baktérie"],
 },
 {
    numb: 116,
    question: "Hnačkové ochorenia môžu spôsobiť tieto baktérie:",
    answer: [" Clostridium perftingens "," Bacillus cereus"," Staphylococcus aureus"," Shigella sonnei, Shigella boydii"," Escherichia coli (niektoré kmene)"," Yersinia enterocolitica "," Campylobacter jejuni"],
    options: [" Clostridium perftingens ","Streptococcus pyogenes"," Bacillus cereus","Enterobacter spp."," Staphylococcus aureus"," Shigella sonnei, Shigella boydii"," Escherichia coli (niektoré kmene)"," Yersinia enterocolitica ","Mycoplasma spp."," Campylobacter jejuni"],
 },
 {
    numb: 117,
    question: "Svoj enteroinvazívny účinok v čreve uplatiluje:",
    answer: [" Yersinia enterocolitica"," Shigella spp."," Salmonella enteritidis"," E. coli (enteroinvazívne) "],
    options: ["Staphylococcus aureus ","Neisseria gonorrhoeae"," Yersinia enterocolitica"," Shigella spp."," Bacillus cereus"," Salmonella enteritidis"," E. coli (enteroinvazívne) "," enterotoxigénne E. coli","Vibrio cholerae"],
 },
 {
    numb: 118,
    question: "Bordetella pertussis:",
    answer: [" na aktívnu imunizáciu sa používa acelulárna subjednotková vakeína"," výter z nosohltanu očkujeme na Bordetovu-Gengouovu pôdu"," má afinitu k riasinkovému epitelu dýchacích ciest"," toxin paralyzuje pohyb cílií epitelu dýchacích ciest"," medzi faktory virulencie patrí pertusový toxín"," je malý opuzdrený gramnegatívny kokobacil"],
    options: [" na aktívnu imunizáciu sa používa acelulárna subjednotková vakeína"," pri vyšetrení odoberáme krv na hemokultiváciu"," výter z nosohltanu očkujeme na Bordetovu-Gengouovu pôdu"," ochorenie a vakcinácia zanechávajú iba krátkodobú imunitu"," má afinitu k riasinkovému epitelu dýchacích ciest","najčastejším prameňom nákazy je infikované zviera"," toxin paralyzuje pohyb cílií epitelu dýchacích ciest"," medzi faktory virulencie patrí pertusový toxín"," vyvoláva nekrotizujúci zápal laryngu"," je malý opuzdrený gramnegatívny kokobacil"],
 },
 {
    numb: 119,
    question: "Yersinia pestis:",
    answer: [" je nesporulujúca, nepohyblivá gramnegatívna palička"," je pôvodcom lesného aj urbánneho moru"," faktorom virulencie sú povrchové štruktúry, blokujúce fagoeytózu"," rezervoárom pri mestskom more je potkan"," najčastejším vektorom prenosu je blcha"],
    options: [" je nesporulujúca, nepohyblivá gramnegatívna palička"," je rastovo náročná a na krvnom agare nevyrastie"," je pôvodcom lesného aj urbánneho moru"," faktorom virulencie sú povrchové štruktúry, blokujúce fagoeytózu"," rezervoárom pri mestskom more je potkan","najčastejším vektorom je kliešť"," najčastejším vektorom prenosu je blcha","pneumonická forma moru je neinfekčná"," ochorenie sa prenáša výlučne infikovanou blchou"," sa pravidelne prenáša pri pohlavnom styku"],
 },
 {
    numb: 120,
    question: "Francisella tularensis:",
    answer: [" je to drobný gramnegatívny kokobacil"," prírodným rezervoárom je zajac, králik a drobné hlodavce "," prekonanie ochorenia zanecháva doživotnú imunitu"," dôkaz protilátok patrí k bežným diagnostickým metódam"," ochorenie patrí medzi zoonózy"," dlhodobé prežívanie v makrofágoch vedie ku chronickej infekcii"],
    options: [" je to drobný gramnegatívny kokobacil"," prírodným rezervoárom je zajac, králik a drobné hlodavce ","ako extracelulárna baktéria vyvoláva pyogénne infekcie ","prenos ektoparazitmi alebo aerosólom nie je možný"," prekonanie ochorenia zanecháva doživotnú imunitu"," dôkaz protilátok patrí k bežným diagnostickým metódam"," ochorenie patrí medzi zoonózy"," dlhodobé prežívanie v makrofágoch vedie ku chronickej infekcii"," ochorenie vyvoláva len u ľudí so zníženou imunitou"],
 },
 {
    numb: 121,
    question: "Pasteurella multocida:",
    answer: [" je to drobný gramnegatívny kokobacil"," faktorom virulencie je lipopolysacharid"," vyskytuje sa v normálnej fióre dýchacích ciest niektorých zvierat"," prameriom nákazy rnôže byť aj choré zviera"," diagnostikuje sa kultivačne"," najčastejšie sa prenáša pohryzilutím zvieraťom (infikuje ranu)"," u človeka móže vyvolať aj závažné systémové infekcie"],
    options: [" je to drobný gramnegatívny kokobacil"," faktorom virulencie je tvorba slizu"," faktorom virulencie je lipopolysacharid"," vyskytuje sa v normálnej fióre dýchacích ciest niektorých zvierat"," prameriom nákazy rnôže byť aj choré zviera","prirodným rezervoárom sú ektoparazity hlodavcov","dlhodobo môže prežívať v prostredí"," diagnostikuje sa kultivačne"," najčastejšie sa prenáša pohryzilutím zvieraťom (infikuje ranu)"," u človeka móže vyvolať aj závažné systémové infekcie"],
 },
 {
    numb: 122,
    question: "Brucella spp. a brucelóza:",
    answer: [" ochorenie patrí medzi zoonózy"," základom laboratómej diagnostiky je kultivačn 'y däkaz"," faktorom virulencie je lipopolysacharid"," patrí k rastovo náročným baktériám"," je schopná rásť intracelulárne a vyvolať granulomatózny zápal "," bránou vstupu sú najčastejšie kožné odreniny"],
    options: [" ochorenie patrí medzi zoonózy"," základom laboratómej diagnostiky je kultivačn 'y däkaz"," faktorom virulencie je lipopolysacharid"," mikroorganizmy majú afinitu k nervovému tkanivu"," primokultivácia sa robí za anaeróbnych podmienok"," patrí k rastovo náročným baktériám"," je schopná rásť intracelulárne a vyvolať granulomatózny zápal ","pri infekcii nedochádza k diseminácii do parenchymatóznych orgánov"," bránou vstupu sú najčastejšie kožné odreniny","rezervoárom Brucella abortus sú netopiere"],
 },
 {
    numb: 123,
    question: "Ktoré z uvedených baktérií sa pravidelne množia aj intracelulárne:",
    answer: [" Francisella tularerals "," Brucella melitensis"," lýlycobacterium leprae"," Mycobacterium tuberculosis"," Listeria monocytogenes"," Mycobacterium bovis"],
    options: [" Escherichia coli"," Francisella tularerals ","Neisseria sicca"," Brucella melitensis"," lýlycobacterium leprae"," Mycobacterium tuberculosis"," Streptococcus pyogenes ","Streptococcus mutans"," Listeria monocytogenes"," Mycobacterium bovis"],
 },
 {
    numb: 124,
    question: "Aktívnu tuberkulózu u pacienta v praxi potvrdime:",
    answer: [" tuberkulínovým kožným testom"," mikroskopicky (Ziehlovo-Neelsenovo farbenie)"," mikroskopicky (fluorescenčným farbením)","  kultiváciou na Mwensteinovej-Jensenovej pôde ","  dókazom nukleovej kyseliny pôvodcu vo vzorke"],
    options: [" epidemiologicky vyšetrením rodinných príslušníkov"," tuberkulínovým kožným testom","mikroskopicky (Gramovo farbenie)"," mikroskopicky (Ziehlovo-Neelsenovo farbenie)"," mikroskopicky (fluorescenčným farbením)","  mikroskopicky (Burriho metódou)         0","  kultiváciou na Mwensteinovej-Jensenovej pôde ","  kultiváciou na Wilsonovej-Blairovej pôde","  dókazom nukleovej kyseliny pôvodcu vo vzorke","  dôkazom špecifických protilátok"],
 },
 {
    numb: 125,
    question: "Na tvorbe tuberkulózneho granulómu sa podieľajú najmä: ",
    answer: ["  fibroblasty","  makrofágy","  epiteloidne transformované mononuldeárne bunky ","  T-lymfocyty"],
    options: ["  granu1ocyty","  eozinofilné leukocyty","  fibroblasty","  makrofágy","  epiteloidne transformované mononuldeárne bunky ","  B-lymfocyty","  myocyty","megakaryocyty","  T-lymfocyty"],
 },
 {
    numb: 126,
    question: "Tuberkulínová sláška (Mantoux): ",
    answer: ["  hodnoti sa po 48 — 72 hodinách","  test sa hodnotí podľa veľkosti indurácie ","  hodnotenie sa overuje palpačne","  odráža precitlivenosť oneskoreného typu na proteínové antigény","  normálny priemer indurácie je 6 — 18 mm u dospelých"],
    options: ["hodnotí sa po 15 minútach od aplikácie","  hodnoti sa po 48 — 72 hodinách","  negatívny výsledok testu potvrdzuje imunitu proti tuberkulóze","  test sa hodnotí podľa veľkosti indurácie ","rozhoduje veľkosť erytému v mieste aplikácie","  hodnotenie sa overuje palpačne","  odráža precitlivenosť oneskoreného typu na proteínové antigény","  potvrdzuje protilátkovú imuni-tu proti tuberkulóze","  normálny priemer indurácie je 6 — 18 mm u dospelých","antigén sa aplikuje epikutánne"],
 },
 {
    numb: 127,
    question: "Pôvodeami mykobakterlóz môžu byť: ",
    answer: ["  Mycobacterium kansasii","  llilycobacterium marinum","  Mycobacterium a-vium","  Mycobacterium intracellulare","  Mycobacterium fortuitum"],
    options: ["Mycobacterium leprae","Mycobacterium bovis (BCG kmeň) ","Mycobacterium bovis","  Mycobacterium kansasii","  llilycobacterium marinum","  Mycobacterium tuberculosis","  Mycobacterium a-vium","  Mycobacterium intracellulare","  Mycobacterium fortuitum"],
 },
 {
    numb: 128,
    question: "Na imunitnej odpovedi proti tuberkulóze sa podieľajú najmä:",
    answer: ["  aktivované makrofágy","  T-lymfocyty produkciou lymfokínov"],
    options: ["  aktivované makrofágy","  T-lymfocyty produkciou lymfokínov","  eozinofilné leukocyty","neutrofilné leukocyty"," komplementový systém aktivovaný alternatívnou cestou"," NK-bunky"," špecifické protilátky"," neaktivované makrofágy"],
 },
 {
    numb: 129,
    question: "Rod Mycobacterium:",
    answer: [" BCG vakcína obsahuje atenuovaný kmeň M bovis"," M tuberculosis a M bovis rozlíšime podľa rastu na pevnej pôde"," M aviumĺ.~.~ intracellulare postihuje často pacientov s AIDS "," generačná doba M tuberculosis je až 18 — 24 hodín"],
    options: [" mikroorganizmy sú len acidorezistentné, nie sú alkalirezistentné"," BCG vakcína obsahuje atenuovaný kmeň M bovis"," všetky druhy rastú vermi pomaly"," druh M bovis je pre človeka nepatogénny"," M tuberculosis postihuje výlučne lymfatický systém a kostnú dreň"," M tuberculosis a M bovis rozlíšime podľa rastu na pevnej pôde"," M aviumĺ.~.~ intracellulare postihuje často pacientov s AIDS "," M tuberculosis na pevných pôdach vyrastá do 6 dni"," generačná doba M tuberculosis je až 18 — 24 hodín"],
 },
 {
    numb: 130,
    question: "Mykolové kyseliny v bunke Mycobacterium tuberculosis:",
    answer: [" podmieňujú acidorezistenciu mikroorganizmu"," chránia milu.00rganizmus pred účinkom enzýmov, kyselín a Iňhov"," indukujú granulomatóznu zápalovú reakciu"," podmieňujú hydrofóbnosť bunkovej steny"," chránia pri fagocytóze mikrób pred lyzozómovými enzýmarni"],
    options: [" podmieňujú acidorezistenciu mikroorganizmu"," chránia milu.00rganizmus pred účinkom enzýmov, kyselín a Iňhov"," indukujú granulomatóznu zápalovú reakciu"," podmieňujú hydrofóbnosť bunkovej steny"," aktivujú komplement alternatívnou cestou"," chránia pri fagocytóze mikrób pred lyzozómovými enzýmarni","indukujú tvorbu reagínových protilátok u pacienta"," používame ich ako antigén pri tuberkulínovom teste"],
 },
 {
    numb: 131,
    question: "Actinomyces spp.:",
    answer: [" mikroorganizmy nesporulujú"," pre aktinomykózu je typický výskyt drúz v hnise"," pri primokultiváci je potrebná anaeróbna atmosféra"," bránou vstupu je najčastejšie poranená sliznica"," mikroskopické vyšetrenie hnisu má diagnostický význam"," charakteristickým obrazom ochorenia je purulentný zápal a tvorba granulómu "],
    options: [" mikroorganizmy nesporulujú"," pre aktinomykózu je typický výskyt drúz v hnise"," pri primokultiváci je potrebná anaeróbna atmosféra"," A. israelii a A. odontolyticus sa izoluje z dutiny ústnej len u chorých"," bránou vstupu je najčastejšie poranená sliznica"," faktorom virulencie je termolabilný leukocidín"," mikroskopické vyšetrenie hnisu má diagnostický význam"," cervikofaciálna forma je dôsledkom hematogénneho rozsevu"," charakteristickým obrazom ochorenia je purulentný zápal a tvorba granulómu ","pri ochorení je infekcia najčastejšie exogénneho pôvodu"],
 },
 {
    numb: 132,
    question: "Bacillus anthracis:",
    answer: [" je nepohyblivý, grampozitívny (gramlabilný, ak tvorí spóry)"," faktorom virulencie je toxín a polypeptidové puzdro "," v prevencii sa môže použiť vakcína"," ochorenie môže vzniknúť inhaláciou spór"," bránou infekcie môže byt' poškodená koža"," ochorenie patrí medzi zoonózy"],
    options: [" je nepohyblivý, grampozitívny (gramlabilný, ak tvorí spóry)"," faktorom virulencie je toxín a polypeptidové puzdro ","produkuje podobne ako Bacillus cereus beta-hemolyzin"," medzi faktory virulencie patrí komplexný toxín"," medzi faktory virulencie patrí enterotoxín"," v prevencii sa môže použiť vakcína"," ochorenie môže vzniknúť inhaláciou spór"," bránou infekcie môže byt' poškodená koža"," ochorenie patrí medzi zoonózy","neliečená prúena forma má obvykle mierny priebeh a nízku mortalitu"],
 },
 {
    numb: 133,
    question: "Medzi špirálovité baktérie patri:",
    answer: [" Leptospira"," Borrelia"," Treponema"],
    options: ["Pseudomonas"," Leptospira"," Yersinia"," Borrelia","Providencia"," Francisella"," Treponema"," Vibrio"],
 },
 {
    numb: 134,
    question: "Borrelia recurrentis:",
    answer: [" mikroorganizmus prenášajú článkonožce"," mikroskopický dôkaz robĺme z krvi"," zmena antigénovej štruktúry zodpovedá za opakované záchvaty horúčky"," je pohyblivá, špirálovitá baktéria"," je patogénna len pre človeka"],
    options: [" kultivujeme na čokoládovom agare"," mikroorganizmus prenášajú článkonožce","nedá sa sledovať mikroskopom v prechádzajúcom svetle"," mikroskopický dôkaz robĺme z krvi"," zmena antigénovej štruktúry zodpovedá za opakované záchvaty horúčky","ochorenie sa prenáša priamym kontaktom"," je pohyblivá, špirálovitá baktéria"," je patogénna len pre človeka"," pri podozreni na ochorenie odoberáme krv na hemokultiváciu"],
 },
 {
    numb: 135,
    question: "Borrelia recurrentis spôsobuje:",
    answer: [" epidemickú návratnú horúčku"," celkové ochorenie s typickou teplotnou krivkou"," jediným rezervoárom je človek"],
    options: [" epidemickú návratnú horúčku"," časté aborty u dobytka ","škvrnitý týfus","maltskú horúčku","Q-horúčku","volynskú horúčku"," celkové ochorenie s typickou teplotnou krivkou"," ochorenie prenosné vzdušnou cestou","ochorenie prenosné fekálno-orálne"," jediným rezervoárom je človek"],
 },
 {
    numb: 136,
    question: "Laboratórna diagnostika lymskej boreliózy:",
    answer: [" sa opiera o dôkaz protilátok"," pri neuroborelióze sa dokazujú protilátky aj v likvore"," irnunoblot sa móže využiť ako konfirmačný test pri dôkaze protilátok"],
    options: [" sa opiera o dôkaz bunkovej imunity (kožný test)"," sa opiera o dôkaz protilátok"," pri neuroborelióze sa dokazujú protilátky aj v likvore","využíva prednostne kultivačné techniky"," irnunoblot sa móže využiť ako konfirmačný test pri dôkaze protilátok","pôvodca sa dokazuje v likvore po farbenĺ podľa Grama"," pôvodca vyrastá na bežných kultivačných pôdach za 24 — 48 hodĺn"],
 },
 {
    numb: 137,
    question: "Lynisktí horelióza sa prenáša: ",
    answer: [" vektormi (kliešte)"," ektoparazitmi"],
    options: ["vzdušnou cestou","fekálno-orálnou cestou "," priamym kontaktorn"," vektormi (kliešte)","pasívne muchami"," ektoparazitmi","pohryznutĺm infikovaným cicavcom"],
 },
 {
    numb: 138,
    question: "Borrelia burgdorferi spôsobuje:",
    answer: [" lymskú borelíózu"," erythema migrans"," celkové ochorenie s rôznorodou symptomatológiou"],
    options: [" maltskú horúčku"," epidemickú návratnú horúčku"," lymskú borelíózu"," erysipeloid"," endemickú návratnú horúčku"," erythema migrans"," hnisanie rán"," hnačky"," celkové ochorenie s rôznorodou symptomatológiou"],
 },
 {
    numb: 139,
    question: "Treponema :",
    answer: [" T pallidum sa môže podiel'ať na vzniku orgánových zmien (guma)"," T pallidum móže spôsobiť intrauterinnú infekciu plodu"," antikardiolipinové protilátky pri syfilise odrážajú aktivitu ochorenia"," likvor pri tabes dorsalis móže obsahovať živé treponémy"],
    options: [" T pallidum sa môže podiel'ať na vzniku orgánových zmien (guma)"," T pallidum móže spôsobiť intrauterinnú infekciu plodu"," T pertenue sa prenáša výlučne pohiavným stykom"," antikardiolipinové protilátky pri syfilise odrážajú aktivitu ochorenia"," lues sa prenáša z infi.kovam'rch primátov na človeka"," v terciárnom štádiu syfilisu u pacienta nedokážeme treponémy ","kož.né eflorescencie II. štádia neobsahujú virulentné treponémy"," likvor pri tabes dorsalis móže obsahovať živé treponémy"],
 },
 {
    numb: 140,
    question: "Laboratórna diagnostika syfilisu:",
    answer: [" mikroorganizmus možno mikroskopicky dokázať už v 1. štádiu"," mikroorganizmus je viditeľný v tmavom poli"," ochorenie môžeme sérologicky dokázať už koncom 1. š'tádia"," lues potvrdzuje dókaz antitreponémových protilátok"," imunoblot sa môže využiť ako konfirmačný test pri dôkaze protilátok"," len sérologické testy s treponémovým antigénom potvrdia diagnózu"],
    options: [" mikroorganizmus možno mikroskopicky dokázať už v 1. štádiu"," mikroorganizmus je viditeľný v tmavom poli"," ochorenie môžeme sérologicky dokázať už koncom 1. š'tádia"," dôkaz antikardiolipinových protilátok definitívne potvrdzuje diagnózu lues"," lues potvrdzuje dókaz antitreponémových protilátok"," mikrób vyrastá na špeciálnych tekutých pôdach za 48 hodín ","na identifikáciu je rozhodujúci dôkaz biochemických vlastností"," imunoblot sa môže využiť ako konfirmačný test pri dôkaze protilátok"," len sérologické testy s treponémovým antigénom potvrdia diagnózu"],
 },
 {
    numb: 141,
    question: "Treponema pallidurn je pôvodcom ochorenia:",
    answer: [" lues"," syfilis"," výlučne u človeka"],
    options: [" prenosného výlučne pri pohlavnom styku"," lymphogranuloma venereum"," AIDS"," lues"," syfilis"," výlučne u človeka","ulcus molle","ktoré prechádza do chronického štádia len u ženy ","pohlavne prenosnej uretritídy"],
 },
 {
    numb: 142,
    question: "Leptospira interrogans:",
    answer: [" patrí medzi š'pirálovité baktérie"," vyrastá na špeciálnych pôdach (Korthoffova pôda)"," vo vlhkom prostredí prežíva niekoľko mesiacov"," na sérotypizáciu použivame mikroaglutinačno-lytickú reakciu"," v sére pacienta možno dolcázať špecifické protilátky"," pacient móže vylučovať pôvodcu ochorenia močom"],
    options: [" patrí medzi š'pirálovité baktérie"," vyrastá na špeciálnych pôdach (Korthoffova pôda)"," vo vlhkom prostredí prežíva niekoľko mesiacov"," postinfekčná imunita nie je sérotypovo špecifická"," mikroskopicky ju možno pozorovat' v prechádzajúcom svetle"," na sérotypizáciu použivame mikroaglutinačno-lytickú reakciu"," v sére pacienta možno dolcázať špecifické protilátky"," pacient móže vylučovať pôvodcu ochorenia močom"],
 },
 {
    numb: 143,
    question: "Leptospiróza:",
    answer: [" ochorenie patrí medzi zoonózy"," zvieratá môžu leptospiry dlhodobo vylučovať močom"," človek sa môže infikovať kontaminovanou vodou alebo potravinami"," mikroorganizmus preniká sliznicami a poranenou kožou"," ochorenie sa móže manifestovať ako aseptická meningitída"," závažné formy sa prejavia ikterom a hemorágiami"," na začiatku ochorenia dokazujeme leptospiry v krvi, likvore; neskôr v moči "],
    options: [" ochorenie patrí medzi zoonózy"," zvieratá môžu leptospiry dlhodobo vylučovať močom"," človek sa môže infikovať kontaminovanou vodou alebo potravinami"," mikroorganizmus preniká sliznicami a poranenou kožou"," ochorenie na človeka prenášajú ektoparazity zvierat"," ochorenie sa móže manifestovať ako aseptická meningitída"," závažné formy sa prejavia ikterom a hemorágiami","ochorenie je vždy sprevádzané ikterom"," na začiatku ochorenia dokazujeme leptospiry v krvi, likvore; neskôr v moči ","sérologické vyšetreme protilátok nemá diagnostický význam"],
 },
 {
    numb: 144,
    question: "Clostridium:",
    answer: [" termolabilný enterotoxín produkuje C. perfi-ingens typ A","  C perfringens patrí k pôvodcom plynových gangrén","  virulenciu C. tetani podmieriuje tetanospazmfn","  tetanospazmín blokuje uvoľnenie glycinu a GABA na tlmivej synapse "],
    options: [" termolabilný enterotoxín produkuje C. perfi-ingens typ A","C.      nikdy nie je súčasťou normálnej flóry v čreve človeka","  C perfringens patrí k pôvodcom plynových gangrén","  C. tetani produkuje kolagenázu","  proti tetanu očkujeme atenuovanou baktériou","  virulenciu C. tetani podmieriuje tetanospazmfn","pri očkovaní proti tetanu stači podať 1 dávku očkovacej látky","  tetanospazmín blokuje uvoľnenie glycinu a GABA na tlmivej synapse ","klinický obraz tetanu sprevádza chabá paralýza"],
 },
 {
    numb: 145,
    question: "Clostridium spp:",
    answer: ["  C. novyi patrí k póvodcom plynovej gangrény","  C. biferrnentans môže spôsobiť plynovú gangrénu","  botulotoxin blokuje vylučovanie acetylcholinu na nervovosvalovej platničke"],
    options: ["  C. botulinurn produkuje antigénne jednotný botulotoxin","  klinická diagnóza potravinového botulizmu sa potvrdí kultivačne","  C. novyi patrí k póvodcom plynovej gangrény","protektívna imunita pri infekcii C. tetani je prednostne bunkového typu","  antibotulinické sérum inaktivuje aj už nadviazaný toxín","  C. biferrnentans môže spôsobiť plynovú gangrénu","ako prvú pri príznakoch tetanu aplikujeme antibiotickú liečbu","imunita po očkovaní proti tetanu je doživotná","pri očkovaní proti tetanu aplikujeme spóry C. tetani podkožne","  botulotoxin blokuje vylučovanie acetylcholinu na nervovosvalovej platničke"],
 },
 {
    numb: 146,
    question: "Veillonella spp:",
    answer: ["  je to granmegatívna striktne anaeróbna baktéria","  morfologicky patrí ku gramnegatívnym kokom","  ako podmienený patogén sa uplatňuje len v zmiešanej infekcii ","  je súčasťou normálnej fióry dutiny ústnej, čreva a pošvy","  je pôvodcom oportúnnych endogénnych infekcií"],
    options: ["  je to granmegatívna striktne anaeróbna baktéria","  morfologicky patrí ku gramnegatívnym kokom","  ako podmienený patogén sa uplatňuje len v zmiešanej infekcii ","nikdy sa nevyskytuje v normálnej flóre dýchacích ciest","  mikroorganizmy sú fakultatívne anaeróbne","  je súčasťou normálnej fióry dutiny ústnej, čreva a pošvy","  je pôvodcom oportúnnych endogénnych infekcií"],
 },
 {
    numb: 147,
    question: "Mykopiazmy intdu spôsobiť ochorenia:",
    answer: ["  atypická pneumónia","  endometritída a salpingitída","  uretritída","  intersticiálny zápai pľúc"],
    options: ["  atypická pneumónia","  endometritída a salpingitída","  uretritída","  intersticiálny zápai pľúc","  plynová gangréna","  furunkul","  myonelu-óza","  dermatomyozitida ","pleurodynia"],
 },
 {
    numb: 148,
    question: "Mycoplasma pneumoniae:",
    answer: ["  na špeciálnych pôdach vyrastá v mikrokolóniách až po dihšej kultivácii","  poškodzuje mukociliárny aparát dýchacieho traktu","  u časti chorých sa tvoria chladové autoaglutiníny (protilátky reagujúce serytrocytrni)","  ochorenie potvrdíme sérologicky dókazom protilátok"],
    options: ["  je pravidelne citlívá na ampicilín","  kmene tvoriace beta-laktamázy sú citlivé na amoxicilín/klavulanát","  nemožno ju kultivovať na kuitivačných pôdach","  na špeciálnych pôdach vyrastá v mikrokolóniách až po dihšej kultivácii","  poškodzuje mukociliárny aparát dýchacieho traktu","  u časti chorých sa tvoria chladové autoaglutiníny (protilátky reagujúce serytrocytrni)","  ochorenie potvrdíme sérologicky dókazom protilátok","  pre ochorenie je charakteristický purulentný zápal"],
 },
 {
    numb: 149,
    question: "Ochorenia u ľudi najčastejšie vyvolávajú:",
    answer: ["  Mycoplasrna genitalium","  Mycoplasma pneumoniae","  Ureaplasma urealyticum"," Mycoplasma hominis"],
    options: ["  Mycoplasrna genitalium","  Mycoplasma pneumoniae","  Ureaplasma urealyticum","  Mycoplasma orale","  Mycoplasma salivarium ","Mycoplasma fermentans","  Mycoplasma buccale"," Mycoplasma hominis"],
 },
 {
    numb: 150,
    question: "L-formy baktérii vznikajú:",
    answer: ["  pósobením lyzozýmu","  pod vplyvom antibiotík","  u niektorých baktérií počas liečby penícilínom","  v makroorganizme pôsobením protilátok a komplementu"],
    options: ["  pósobením lyzozýmu","  pod vplyvom antibiotík","  pod vplyvom chemických karcinogénov","  u niektorých baktérií počas liečby penícilínom","často pri mykoplazmách počas antibiotickej terapie","  v makroorganizme pôsobením protilátok a komplementu","  ako následok sporulácie","  za zníženého parciálneho tlaku kyslíka v prostredí ","pri zmene osmotického tlaku v kultivačnom prostredi"],
 },
 {
    numb: 151,
    question: "Riketsie:",
    answer: ["  sú obligátne intracelulárne","  v diagnostike infekcii sa opierame ❑ nepriamy dôkaz"," v diagnostike sa mäže použif PCR"],
    options: ["  sú obligátne intracelulárne","množia sa aj v špeciálnych syntetických médiách","  nie sú citlivé na antibiotiká","  nemajú DNA","  nemajú vlastnú proteosyntézu","  v diagnostike infekcii sa opierame ❑ nepriamy dôkaz"," v liečbe uprednostriujeme cefalosporíny a ureidopenicilíny"," v diagnostike sa mäže použif PCR"],
 },
 {
    numb: 152,
    question: "Rkkettsia prowazekii:",
    answer: [" rezervoárom je človek"," pri diagnostike sa opierame o sérologický dôkaz protilátoke"," liekom voľby sii tetracyklíny a chloramfenikol"," Brillova-Zinsserova choroba je recidíva škyrnitého týfusu"],
    options: [" rezervoárom je človek","ochorenie sa prenáša priamym kontaktom"," pri diagnostike sa opierame o sérologický dôkaz protilátoke"," liekom voľby sii tetracyklíny a chloramfenikol"," odvšivavenie nemá epidemiologický význam","je pôvodcom myšieho škvrnitého týfusu"," rezervoárom sú hlavne myši"," vektorom je bicha"," Brillova-Zinsserova choroba je reinfekcia R. prowazekii"," Brillova-Zinsserova choroba je recidíva škyrnitého týfusu"],
 },
 {
    numb: 153,
    question: "Coxiella burnetii:",
    answer: [" spósobuje Q-horúčku"," infekcia sa prenáša inhaláciou aerosólu, perorálne, alebo vektorom"," pri ochorení vyšetrujeme krv na clókaz protilátok"," infekcia sa môže preniesť požitim mlieka alebo prostredníctvom kliešťa "," ochorenie môže prebiehaf pod obrazom atypickej pneumónie a hepatitídy"," môž'e spôsobiť chronickú infekciu s endokarditídou"],
    options: [" spósobuje Q-horúčku"," prameriam nákazy je vždy človek"," infekcia sa prenáša inhaláciou aerosólu, perorálne, alebo vektorom"," pri ochorení vyšetrujeme krv na clókaz protilátok"," infekcia sa môže preniesť požitim mlieka alebo prostredníctvom kliešťa ","nepriama diagnostika nemá význam"," ochorenie sprevádza exantém a enantém"," ochorenie môže prebiehaf pod obrazom atypickej pneumónie a hepatitídy"," môž'e spôsobiť chronickú infekciu s endokarditídou"],
 },
 {
    numb: 154,
    question: "Chlamýdie:",
    answer: [" množia sa výlučne intracelulárne ","  nemajú vlastný energetický metabolizmus","  v infikovanej bunke vytvárajú inklúzie ","  infekčné sú len elementárne telieska"],
    options: [" množia sa výlučne intracelulárne ","patria ku grampozitívnym baktériám","  nemajú vlastný energetický metabolizmus","  v infikovanej bunke vytvárajú inklúzie ","mikroskopický preparát farbime podľa Ziehla-Neelsena","pri sérologickom dôkaze protilátok využívame antigény puzdra","  infekčné sú len elementárne telieska","  retikulárne teliesko je osmoticky stabilné"],
 },
 {
    numb: 155,
    question: "Chlamydia trachomatis (sérotypy D-K):",
    answer: ["  spôsobuje inklúznu konjunktivitídu","  je pôvodcom uretrititídy","  prenáša sa pohlavným stykom","  ochorenie je bežné aj v našich zemepisných šírkach","  pri diagnostike cervicitídy sa dokazuje antigén v cervikálnych výteroch"],
    options: ["liečba antibiotikami je neúčinná","prenáša sa potravinami","  u dospelých sa klinicky najčastejšie prejavi ako pneumónia","rezervoárom infekcie sú vtáky","  spôsobuje inklúznu konjunktivitídu","  je pôvodcom uretrititídy","  prenáša sa pohlavným stykom","  ochorenie je bežné aj v našich zemepisných šírkach","  pri diagnostike cervicitídy sa dokazuje antigén v cervikálnych výteroch"],
 },
 {
    numb: 156,
    question: "Chlamydia pneumoniae:",
    answer: ["  vyvoláva atypickú pneurnóniu"," pri diagnostike sa prednostne využíva dôkaz protilátok"," ochorenie častejšie postihuje horné dýchacie cesty než pľúca "," prenáša sa kvapôčkovou infekciou"],
    options: ["  vyvoláva atypickú pneurnóniu","vyvoláva purulentnú meningitidu"," pri diagnostike sa prednostne využíva dôkaz protilátok"," prenáša sa pohlavným stykom"," ochorenie častejšie postihuje horné dýchacie cesty než pľúca ","na krvnom agare vyrastie do 2 dní"," prenáša sa kvapôčkovou infekciou"],
 },
 {
    numb: 157,
    question: "Označte správne kombinácie pôvodca-ochorenie:",
    answer: ["Coxiella burnetii Q-honáčka", "Haemophilus influenzae — epiglotitída", "Chlamydia trachomatis lymfogranuloma venereum ", "Streptococcus pyogenes šarlach", "Staphylococcus aureus syndróm toxického šoku"],
    options: ["Coxiella burnetii Q-honáčka", "Haemophilus influenzae — epiglotitída", "Chlamydia trachomatis lymfogranuloma venereum ", "Streptococcus pyogenes šarlach", "Staphylococcus aureus syndróm toxického šoku", "Haemophilus ducrei ulcus du•um", "Streptococcus agalactiae — endocarditis lenta", "Rick2ttsia prowazekii — psitakóza", "Streptococcus mutans — reumatická hoffička", "Neisseria meningitidis — intersticiálna pneumónia"],
 },
];
