let questions = [
  {
    numb: 0,
    question: "Karcinoembryonálny antigén (CEA) sa používa",
    answer: [" na monitorovanie liečby pacientov s kolorektálnym karcinómom", " na včasnú diagnostiku recidívy kolorektálneho karcinómu "],
    options: ["na plošný skríning gastrointestinálnych nádorov"," na monitorovanie liečby pacientov s kolorektálnym karcinómom"," na včasnú diagnostiku kolorektálneho karcinómu", " na včasnú diagnostiku recidívy kolorektálneho karcinómu "],
 },
 {
    numb: 1,
    question: "Karcinoembryonálny antigén (CEA) sa používa",
    answer: [" na skríning kolorektálneho karcinómu v rizikových skupinách ","u pacientov s adenokarcinómom pľúc"],
    options: [" na skríning kolorektálneho karcinómu v rizikových skupinách ", "na skríning nádorov pankreasu", "na sledovanie pacientov s malobunkovým karcinómom pľúc", "u pacientov s adenokarcinómom pľúc"],
 },
 {
    numb: 2,
    question: "Karcinoembryonálny antigén (CEA)",
    answer: ["býva zvýšený u fajčiarov", "môže byť zvýšený pri divertikulitíde čreva","hodnoty do 10 µg/l nemusia znamenať prítomnosť nádoru"],
    options: ["používa sa aj v prenatálnej diagnostike", "býva zvýšený u fajčiarov", "môže byť zvýšený pri divertikulitíde čreva","hodnoty do 10 µg/l nemusia znamenať prítomnosť nádoru"],
 },
 {
    numb: 3,
    question: "Karcinoembryonálny antigén (CEA)",
    answer: ["môže mať prognostický význam pri kolorektálnom karcinóme","fyziologicky je produkovaný bunkami GIT-u vo fetálnom období"],
    options: ["hodnoty do 10 µg/l sú podozrivé z prítomnosti metastáz","môže mať prognostický význam pri kolorektálnom karcinóme","fyziologicky je produkovaný bunkami GIT-u vo fetálnom období","je to látka hormonálnej povahy "],
 },
 {
    numb: 4,
    question: "Karcinoembryonálny antigén (CEA)",
    answer: ["môže byť zvýšený aj pri benigných chorobách", "môže byť zvýšený pri zápaloch čreva" ," môže byť zvýšený pri niektorých nádoroch pľúc "],
    options: ["môže byť zvýšený aj pri benigných chorobách", "môže byť zvýšený pri zápaloch čreva"," býva pravidelne zvýšený u pacientov s nádorom pankreasu" ," môže byť zvýšený pri niektorých nádoroch pľúc "],
 },
 {
    numb: 5,
    question: "Karcinoembryonálny antigén (CEA)",
    answer: ["môže byť zvýšený u pacientov s cirhózou pečene"],
    options: ["býva zvýšený pri nádoroch pľúc z dlaždicového epitelu","môže byť zvýšený u pacientov s cirhózou pečene","používa sa ako marker pri cervikálnom karcinóme","používa sa pri seróznom type cystadenokarcinómu vaječníkov", ],
 },
 {
    numb: 6,
    question: "Karcinoembryonálny antigén (CEA)",
    answer: ["fyziologicky sa syntetizuje v bunkách fetálneho čreva"],
    options: ["fyziologicky sa syntetizuje v bunkách fetálnej pečene","fyziologicky sa syntetizuje v bunkách fetálneho čreva", " býva zvýšený pri hepatocelulárnom karcinóme"," býva zvýšený pri malobunkovom karcinóme pľúc"],
 },
 {
    numb: 7,
    question: "Vyšetrenie hladiny karcinoembryonálneho antigénu sa používa pri",
    answer: ["pri monitorovaní liečby u pacienta s kolorektálnym karcinómom","pri skríningu nádoru hrubého čreva u pacientov s polypózou čreva"],
    options: ["diferenciálnej diagnostike hepatocelulárneho a cholangiocelulárneho karcinómu","diagnostike cirhózy pečene","pri monitorovaní liečby u pacienta s kolorektálnym karcinómom","pri skríningu nádoru hrubého čreva u pacientov s polypózou čreva"],
 },
 {
    numb: 8,
    question: "Karcinoembryonálny antigén (CEA)",
    answer: ["je onkofetálny antigén","býva zvýšený pri adenokarcinóme prsníka"],
    options: ["je onkofetálny antigén","je onkoplacentárny antigén","býva zvýšený pri adenokarcinóme prsníka","býva zvýšený pri nádoroch z plochého dlaždicového epitelu"],
 },
 {
    numb: 9,
    question: "Alfa-fetoproteín",
    answer: ["fyziologickly je produkovaný bunkami fetálnej pečene","fyziologicky je produkovaný bunkami žltkového vaku", "fyziologicky býva zvýšený v sére gravidných žien"],
    options: ["fyziologickly je produkovaný bunkami fetálnej pečene","fyziologicky je produkovaný bunkami žltkového vaku","v plodovej vode sa používa na posúdenie zrelosti pľúc plodu", "fyziologicky býva zvýšený v sére gravidných žien"],
 },
 {
    numb: 10,
    question: "Alfa-fetoproteín",
    answer: ["jeho vyšetrenie v krvi sa používa pri skríningu razštepov neurálnej trubice","sa svojimi vlastnosťami a funkciou podobá albumínu"],
    options: ["jeho vyšetrenie v krvi sa používa pri skríningu razštepov neurálnej trubice","sa svojimi vlastnosťami a funkciou podobá albumínu","používa sa na dôkaz gravidity","býva zvýšený pri metastatickom postihnutí pečene"],
 },
 {
    numb: 11,
    question: "Zvýšené hladiny alfa-fetoproteínu bývajú pravidelne pri",
    answer: ["primárnom hepatocelulárnom karcinóme","niektorých nádoroch semenníkov"],
    options: ["primárnom hepatocelulárnom karcinóme","niektorých nádoroch semenníkov","pri metastáze nádorov čreva do pečene","pokročilom mnohopočetnom myelóme" ],
 },
 {
    numb: 12,
    question: "Zvýšené hladiny AFP bývajú pravidelne pri",
    answer: ["v priebehu gravidity"],
    options: ["nádoroch vaječníkov","nádoroch pľúc","malobunkovom karcinóme pľúc","v priebehu gravidity"],
 },
 {
    numb: 13,
    question: "AFP",
    answer: ["možno použiť pri odlíšení hepatocelulárneho karcinómu od metastáz do pečene","možno použiť pri rozlíšení hepatocelulárneho karcinómu a cholangiocelulárneho karcinómu"," je onkofetálny antigén"],
    options: ["možno použiť pri odlíšení hepatocelulárneho karcinómu od metastáz do pečene","možno použiť pri rozlíšení hepatocelulárneho karcinómu a cholangiocelulárneho karcinómu","býva zvýšený u pacientov s adenómom pečene"," je onkofetálny antigén"],
 },
 {
    numb: 14,
    question: "Hladiny AFP bývajú zvýšené",
    answer: ["pri cirhóze pečene","pri regenerácii pečene","v gravidite"],
    options: ["pri cirhóze pečene","pri regenerácii pečene","v gravidite","pri Downovom syndróme"],
 },
 {
    numb: 15,
    question: "Alfa-fetoproteín",
    answer: ["používa sa pri diagnostike germinatívnych nádorov testes","používa sa na sledovanie pacientov s maldescensusu testes"],
    options: ["používa sa pri diagnostike germinatívnych nádorov testes","je vyšetrením 1.voľby pri podozerní na nádor pankreasu","používa sa na sledovanie pacientov s maldescensusu testes","používa sa v diagnostike nádorov prostaty"],
 },
 {
    numb: 16,
    question: "Hladiny hCG bývajú zvýšené pri",
    answer: ["choriokarcinóme","mola hydatidosa","aj pri niektorých netrofoblastových nádoroch"],
    options: ["choriokarcinóme","mola hydatidosa","aj pri niektorých netrofoblastových nádoroch","len pri nádoroch z trofoblastu" ],
 },
 {
    numb: 17,
    question: "Hladiny hCG bývajú zvýšené pri",
    answer: ["gravidite","aj pri extrauterinnej gravidite "],
    options: ["malobunkovom karcinóme pľúc","pri ovariálnom karcinóme","gravidite","aj pri extrauterinnej gravidite "],
 },
 {
    numb: 18,
    question: "O hCG môžeme povedať",
    answer: ["vyšetrujeme ho v rámci skríningu u gravidných žien"],
    options: ["býva zvýšený pri pravých seminómoch","býva zvýšený pri nádoroch semenníkov obsahujúcich štruktúry žltkového vaku","vyšetrujeme ho v rámci skríningu u gravidných žien"," býva zvýšený u plodov s anencefaliou" ],
 },
 {
    numb: 19,
    question: "O hCG môžeme povedať",
    answer: ["používa sa pri skríningu Downovej choroby","býva zvýšený pri invazívnej mole","vyšetruje sa aj voľná beta-podjednotka"],
    options: ["používa sa pri skríningu Downovej choroby","býva zvýšený pri invazívnej mole","vyšetruje sa aj voľná alfa-podjednotka","vyšetruje sa aj voľná beta-podjednotka"],
 },
 {
    numb: 20,
    question: "O testikulárnych nádoroch možno povedať",
    answer: ["čistý seminóm má obvykle normálny AFP"," zrelé teratómy mávajú obvykle negatívny AFP aj hCG","choriokarcinómy majú zvýšené hCG a negatívne AFP",],
    options: ["čistý seminóm má obvykle normálny AFP"," zrelé teratómy mávajú obvykle negatívny AFP aj hCG","choriokarcinómy majú zvýšené hCG a negatívne AFP","nádory obsahujúce štruktúry žltkového vaku majú zvýšený hCG" ],
 },
 {
    numb: 21,
    question: "O testikulárnych nádoroch možno povedať",
    answer: [ "čistý seminóm má obvykle normálny hCG", "embryonálny karcinóm má zvýšené AFP aj hCG "],
    options: ["choriokarcinómy majú zvýšený AFP a negatívny hCG", "embryonálne karcinómy majú negatívny AFP aj hCG", "čistý seminóm má obvykle normálny hCG", "embryonálny karcinóm má zvýšené AFP aj hCG "],
 },
 {
    numb: 22,
    question: "O nádoroch pľúc možno povedať ",
    answer: ["markerom adenokarcinómu pľúc je CEA","nádor z viacvrstvového dlaždicového epitelu má zvýšené hladiny SCC "],
    options: ["markerom pre malobunkový karcinóm pľúc je CYFRA 21-1","markerom adenokarcinómu pľúc je CEA","markerom veľkobunkového karcinómu pľúc je NSE","nádor z viacvrstvového dlaždicového epitelu má zvýšené hladiny SCC "],
 },
 {
    numb: 23,
    question: "O nádoroch pľúc možno povedať",
    answer: [],
    options: ["malobunkový karcinóm je častejší ako nemalobunkový karcinóm", "markerom typickým pre malobunkový karcinóm pľuc je SCC", "nádor z viacvrstvového dlaždicového epitelu má zvýšené hladiny NSE"," pre nádory pľúc je charakteristické zvýšenie CA 15-3" ],
 },
 {
    numb: 24,
    question: "Neurošpecifická enoláza býva zvýšená u pacientov",
    answer: ["s neuroblastómom","s malobunkovým karcinómom pľúc" ],
    options: ["s meduloblastómom", "s myelómom", "s neuroblastómom","s malobunkovým karcinómom pľúc" ],
 },
 {
    numb: 25,
    question: "Pri stanovení prognózy u pacienta s myelómom sa používa vyšetrenie",
    answer: ["beta-2-mikroglobulínu"],
    options: ["NSE","beta-2-mikroglobulínu"," hCG","transferínu"],
 },
 {
    numb: 26,
    question: "Pre monitorovanie priebehu ochorenia u pacientov s melanómom sa používa",
    answer: [
      "S100B proteín",],
    options: ["chromogranín",
      "SCC-antigén",
      "S100B proteín",
      "tkanivový polypeptidový antigén (TPA)"],
 },
 {
    numb: 27,
    question: "SCC-antigén je",
    answer: ["zvýšený pri nádoroch pažeráka","zvýšený pri adenokarcinóme cervixu "],
    options: ["zvýšený pri nádoroch pažeráka",
      " produkovaný bunkami fetálneho GIT-u",
       "zvýšený pri hematologických malignitách",
       "zvýšený pri adenokarcinóme cervixu "],
 },
 {
    numb: 28,
    question: "SCC-antigén je",
    answer: ["zvýšený pri niektorých nádoroch pľúc",
    "zvýšený pri nádoroch ústnej dutiny"],
    options: ["zvýšený pri pankreatických nádoroch",
      "zvýšený pri niektorých nádoroch pľúc",
    "zvýšený pri nádoroch ústnej dutiny",
      "zvýšený pri adenokarcinóme žalúdka "],
 },
 {
    numb: 29,
    question: "O gynekologických nádoroch možno povedať ",
    answer: [
      "mucinózne karcinómy ovárií mávajú zvýšené hodnoty CA 72-4",
      "pri nádoroch cervixu býva zvýšený SCC-antigén"],
    options: ["mucinózne karcinómy ovárií majú zvýšené hodnoty hCG",
       "mucinózne karcinómy ovárií mávajú zvýšené hodnoty CA 72-4",
       "pri nádoroch cervixu býva zvýšený SCC-antigén",
       "pri nádoroch vagíny býva zvýšený CA 15-3 "],
 },
 {
    numb: 30,
    question: "O gynekologických nádoroch možno povedať",
    answer: ["pri nádoroch prsníka môže byť zvýšený CEA",
      "serózne karcinómy ovárií mávajú zvýšené hodnoty CA 125"],
    options: ["pri nádoroch prsníka môže byť zvýšený CEA",
      " pri nádoroch prsníka býva zvýšený AFP",
      "serózne karcinómy ovárií mávajú zvýšené hodnoty CA 125",
       "nádory maternice mávajú zvýšené hodnoty NSE "],
 },
 {
    numb: 31,
    question: "Pre nádory z viacvrstvového dlaždicového epitelu platí",
    answer: [
      "bývajú zvýšené hladiny CYFRA 21-1",
      "bývajú zvýšené hladiny SCC-antigénu"],
    options: [ "bývajú zvýšené hladiny CEA",
       "bývajú zvýšené hladiny CYFRA 21-1",
       "bývajú zvýšené hladiny CA 125",
       "bývajú zvýšené hladiny SCC-antigénu"],
 },
 {
    numb: 32,
    question: "Pre nádory z viacvrstvového dlaždicového epitelu platí",
    answer: [ "hladiny CEA sú obvykle nezmenené",
      "hladiny CA 72-4 sú obvykle nezmenené",
      "nemáva zvýšené hodnoty hCG"],
    options: [ "hladiny CEA sú obvykle nezmenené",
       "hladiny CA 72-4 sú obvykle nezmenené",
       "nemáva zvýšené hodnoty hCG",
       "bývajú zvýšené hodnoty voľnej frakcie PSA"],
 },
 {
    numb: 33,
    question: "Pri neuroblastómoch bývajú zvýšené hladiny",
    answer: ["NSE"],
    options: ["CA 72-4",
       "NSE",
       "AFP",
       "CA 15-3"],
 },
 {
    numb: 34,
    question: " Pri neuroblastómoch bývajú zvýšené hladiny",
    answer: [" alkalická peptónová voda"," selenitový bujón "," Kauffrnannova pôda"],
    options: ["CEA",
       "beta-2-mikroglobulínu",
       "PSA",
       "SCC-antigénu"],
 },
 {
    numb: 35,
    question: "Beta-2-mikroglobulín býva zvýšený v sére pacientov s",
    answer: ["hematologickými malignitami",
       "chronickou lymfatickou leukémiou"],
    options: ["hematologickými malignitami",
       "epitelovými nádormi",
       "nádormi pankreasu",
       "chronickou lymfatickou leukémiou"],
 },
 {
    numb: 36,
    question: "Beta-2-mikroglobulín býva zvýšený v sére pacientov s",
    answer: [
      "mnohopočetným myelómom",
      "lymfómom"],
    options: [ "mucinóznym nádorom vaječníkov",
       "mnohopočetným myelómom",
       "lymfómom",
       "neuroblastómom" ],
 },
 {
    numb: 37,
    question: "Onkomarker CA 15-3 je vyšetrením 1.voľby u pacientov s",
    answer: [
      "karcinómom prsníka"],
    options: ["karcinómom hrubého čreva",
       "karcinómom prsníka",
       "myelómom",
       "neuroblastómom" ],
 },
 {
    numb: 38,
    question: "Onkomarker CA 72-4",
    answer: ["býva zvýšený aj pri mucinóznom cystadenokarcinóme vaječníkov",
      "používa sa hlavne pri karcinómoch žalúdka",
      "môže byť zvýšený u pacientov s pankreatitídou" ],
    options: ["býva zvýšený aj pri mucinóznom cystadenokarcinóme vaječníkov",
      "býva zvýšený aj pri seróznom cystadenokarcinóme vaječkíkov",
      "používa sa hlavne pri karcinómoch žalúdka",
      "môže byť zvýšený u pacientov s pankreatitídou" ],
 },
 {
    numb: 39,
    question: "Onkomarker CA 72-4",
    answer: ["býva zvýšený pri nádoroch GIT-u",
       "môže byť zvýšený u pacientov s benignými ochoreniami žalúdka"],
    options: ["býva zvýšený pri nádoroch GIT-u",
       "býva pravidelne negatívny pri nádoroch prsníka",
       "môže byť zvýšený u pacientov s benignými ochoreniami žalúdka",
       "býva zvýšený u pacientov s testikulárnymi nádormi "],
 },
 {
    numb: 40,
    question: "Pri hepatocelulárnom karcinóme nachádzame",
    answer: [
      "zvýšenú hladinu AFP"],
    options: ["zvýšenú hladinu hCG",
       "zvýšenú hladinu AFP",
       "zvýšené aktivity ALP",
       "zvýšené aktivity CK-BB"],
 },
 {
    numb: 41,
    question: "Onkomarker CA125 sa používa ",
    answer: ["pri diagnostike gynekologických nádorov",
       "pri diagnostike karcinómov ovárií",],
    options: ["pri diagnostike gynekologických nádorov",
       "pri diagnostike karcinómov ovárií",
       "ako marker 1.voľby pri nádoroch prsníka",
       "najčastejšie pri nádoroch pľúc "],
 },
 {
    numb: 42,
    question: "Vyšetrenie onkomarkeru CA125  ",
    answer: [
      "je pri mucinóznych karcinómoch ovárií menej citlivé",
      "sa používa aj u pacientov s karcinómom pankreasu"],
    options: ["je pri seróznych karcinómoch ovárií menej citlivé",
      "je pri mucinóznych karcinómoch ovárií menej citlivé",
      "sa používa aj u pacientov s karcinómom pankreasu",
      "sa používa aj u pacientov s karcinómom žalúdka"],
 },
 {
    numb: 43,
    question: "Pri nádoroch žalúdka sa využíva hlavne vyšetrenie",
    answer: [
      "CA 72-4 "],
    options: ["CA19-9",
       "CA125",
       "CA549",
      "CA 72-4 "],
 },
 {
    numb: 44,
    question: "Pri nádoroch pankreasu sa používa ",
    answer: ["ako onkomarker 1.voľby vyšetrenie CA19-9",
       "ako marker 2.voľby vyšetrenie CA125 "],
    options: [ "hlavne vyšetrenie CA72-4",
       "ako onkomarker 1.voľby vyšetrenie CA19-9",
       "ako marker 2.voby vyšetrenie CA15-3",
       "ako marker 2.voľby vyšetrenie CA125 "],
 },
 {
    numb: 45,
    question: "Pri nádoroch cervixu maternice sa využíva vyšetrenie",
    answer: [
      "SCC-antigén"],
    options: [ "CA125",
       "CA19-9",
       "SCC-antigén",
       "NSE" ],
 },
 {
    numb: 46,
    question: "Pre vyšetrenie CA19-9 ako onkomarkera je hlavnou indikáciou",
    answer: [
      "nádor exokrinného pankreasu"],
    options: ["nádor žalúdka",
       "nádory pečene",
       "nádor exokrinného pankreasu",
       "nádory semenníkov"],
 },
 {
    numb: 47,
    question: "Pri nádoroch pľúc sa využíva vyšetrenie",
    answer: ["CYFRA21-1",
       "NSE",
       "CEA"],
    options: ["CYFRA21-1",
       "NSE",
       "CEA",
       "CA15-3 "],
 },
 {
    numb: 48,
    question: "Pri adenokarcinóme pľúc sa uplatňuje vyšetrenie",
    answer: ["CEA"],
    options: ["CYFRA21-1",
      "NSE",
      "CEA",
      "AFP"],
 },
 {
    numb: 49,
    question: "Pri metastatickom postihnutí pečene býva",
    answer: ["zvýšená aktivita GMT",
       "zvýšená hladina CEA",
       "zvýšená aktivita ALP"],
    options: ["zvýšená aktivita GMT",
       "zvýšená hladina CEA",
       "zvýšená aktivita ALP",
       "zvýšená hladina AFP "],
 },
 {
    numb: 50,
    question: "Laktátdehydrogenáza",
    answer: ["je ubikvitárny enzým",
       "je bohato zastúpená v erytrocytoch",
       "býva v sére zvýšená pri poškodeniach pečene"],
    options: ["je ubikvitárny enzým",
       "je bohato zastúpená v erytrocytoch",
       "býva v sére zvýšená pri poškodeniach pečene",
       "má štyri izoenzýmy"],
 },
 {
    numb: 51,
    question: "Laktátdehydrogenáza",
    answer: ["býva zvýšená u pacientov s nádorovým ochorením",
       "býva zvýšená pri hemolýze",
       "môže byť zvýšená po väčšej fyzickej záťaži "],
    options: ["je lokalizovaná v mitochondriach",
       "býva zvýšená u pacientov s nádorovým ochorením",
       "býva zvýšená pri hemolýze",
       "môže byť zvýšená po väčšej fyzickej záťaži "],
 },
 {
    numb: 52,
    question: "O laktátdehydrogenáze môžeme povedať",
    answer: ["v sére je najviac zastúpený izoenzým LD-2",
       "z kardiálnych enzýmov sa zvyšuje ako posledná "],
    options: ["v sére je fyziologicky najviac zastúpený izoenzým LD-5",
       "v sére je najviac zastúpený izoenzým LD-2",
      " hemolýza znižuje jej aktivitu",
       "z kardiálnych enzýmov sa zvyšuje ako posledná "],
 },
 {
    numb: 53,
    question: "O laktátdehydrogenáze môžeme povedať",
    answer: [ "izoenzým LD-1 býva zvýšený pri poškodení myokardu",
      "jej vyšetrenie nemá praktický význam u pacientov s ochorením pankreasu"],
    options: ["izoenzým LD-1 býva zvýšený pri pečeňových ochoreniach",
       "izoenzým LD-1 býva zvýšený pri poškodení myokardu",
       "jej koenzýmom je FAD",
       "jej vyšetrenie nemá praktický význam u pacientov s ochorením pankreasu"],
 },
 {
    numb: 54,
    question: "Laktátdehydrogenáza",
    answer: [
      " v hepatologii sa využíva vyšetrenie izoenzýmu LD5",
       "pri onkologických ochoreniach sa jej aktivita zvyšuje"],
    options: ["v kardiologii sa využíva vyšetrenie izoenzýmu LD2",
      " v hepatologii sa využíva vyšetrenie izoenzýmu LD5",
       "pri onkologických ochoreniach sa jej aktivita zvyšuje",
      "izoenzým LD1 označujeme ako alfa-butyrátdehyydrogenázu "],
 },
 {
    numb: 55,
    question: "Laktátdehydrogenáza",
    answer: [
      "je markerom intravaskulárnej hemolýzy",
      "jej aktivita býva zvýšená pri pernicioznej anémii "],
    options: [ "u pacientov s akútnym infarktom myokardu sa normalizuje za 3 dni",
       "u pacientov s akútnym infarktom myokardu sa normalizuje za 24 hodín",
       "je markerom intravaskulárnej hemolýzy",
       "jej aktivita býva zvýšená pri pernicioznej anémii "],
 },
 {
    numb: 56,
    question: "Pre laktátdehydrogenázu platí",
    answer: [
      "jej aktivita sa pri infarkte myokardu zvyšuje 6-12 hodín po vzniku ischémie",
      "pri akútnom infarkte myokardu sa zvyšuje predovšetkým izoenzým LD1",
      "najviac zastúpeným izoenzýmom v erytrocytoch je LD2 "],
    options: ["jej aktivita sa pri infarkte myokardu zvyšuje 1-2 hodiny po vzniku ischémi",
       "jej aktivita sa pri infarkte myokardu zvyšuje 6-12 hodín po vzniku ischémie",
       "pri akútnom infarkte myokardu sa zvyšuje predovšetkým izoenzým LD1",
       "najviac zastúpeným izoenzýmom v erytrocytoch je LD2 "],
 },
 {
    numb: 57,
    question: "Výrazné zvýšenie aktivity laktátdehydrogenázy nachádzame pri",
    answer: ["poruchách pečene",
       "hemolytických stavoch",
       "maligných nádoroch "],
    options: [ "poruchách pečene",
       "hemolytických stavoch",
       "chronickej pankreatitíde",
       "maligných nádoroch "],
 },
 {
    numb: 58,
    question: "O laktátdehydrogenáze platí",
    answer: [
      "pre ochorenie pečene je typické zvýšenie aktivity LD5",
      "pre myopatie je charakteristické zvýšenie aktivity LD5",
      "pri malígnych ochoreniach sa zvyšuje hlavne aktivita LD3 - LD5"],
    options: [ "pre ochorenie myokardu je typické zvýšenie aktivity LD2",
       "pre ochorenie pečene je typické zvýšenie aktivity LD5",
       "pre myopatie je charakteristické zvýšenie aktivity LD5",
       "pri malígnych ochoreniach sa zvyšuje hlavne aktivita LD3 - LD5"],
 },
 {
    numb: 59,
    question: "Gama-glutamyltransferáza",
    answer: [
      "patrí medzi tzv. cholestatické enzýmy",
      "je membránovo-viazaný enzým"],
    options: ["jej prevažná časť sa nachádza v mitochondriach",
       "patrí medzi tzv. cholestatické enzýmy",
       "je membránovo-viazaný enzým",
       "je cytosolový enzým "],
 },
 {
    numb: 60,
    question: "Gama-glutamyltransferáza",
    answer: ["je induktívny enzým",
       "býva zvýšená pri alkoholizme",],
    options: ["je induktívny enzým",
       "býva zvýšená u pacientov s akútnym infarktom myokardu",
       "býva zvýšená pri alkoholizme",
       "je ukazovateľom proteosyntetickej funkcie pečene "],
 },
 {
    numb: 61,
    question: "O gama-glutamyltransferáze možno povedať",
    answer: ["býva zvýšená pri užívaní barbiturátov",
       "býva zvýšená pri cholestáze"],
    options: [ "býva zvýšená pri užívaní barbiturátov",
       "býva zvýšená pri užívaní beta-blokátorov",
       "býva zvýšená hlavne pri hepatitíde A",
       "býva zvýšená pri cholestáze"],
 },
 {
    numb: 62,
    question: "O gama-glutamyltransferáze možno povedať",
    answer: [ "býva zvýšená pri alkohol-toxickej hepatitíde",
      "ak je zvýšená a zvýšená je aj ALP, tak ide o cholestázu",
      "jej zvýšené hodnoty v sére pochádzajú len z pečene"],
    options: [ "býva zvýšená pri alkohol-toxickej hepatitíde",
       "ak je zvýšená a zvýšená je aj ALP, tak ide o cholestázu",
       "jej zvýšené hodnoty v sére pochádzajú len z pečene",
       "býva zvýšená pri intoxikácii organofosfátmi "],
 },
 {
    numb: 63,
    question: "O gama-glutamyltransferáze možno povedať",
    answer: ["zdrojom jej zvýšených aktivít v sére je len pečeň"],
    options: ["zdrojom zvýšených aktivít v sére môžu byť erytrocyty",
       "zdrojom jej zvýšených aktivít v sére je len pečeň",
       "zdrojom jej zvýšených aktivít v sére môžu byť obličky",
       "zvýšenie jej aktivity v sére podmieňuje hypercholesterolémia "],
 },
 {
    numb: 64,
    question: "Zvýšená aktivita GMT v sére býva prítomná pri ",
    answer: ["konzumácii alkoholu",
       "pri cholestatických hepatopatiach"],
    options: ["užívaní acylpyrínu",
       "konzumácii alkoholu",
       "pri cholestatických hepatopatiach",
       "zvýšení fibrogenézy v pečeni "],
 },
 {
    numb: 65,
    question: "Zvýšená aktivita GMT v sére môže byť u pacientov",
    answer: ["s obštrukčným ikterom",
       "s primárnou biliárnou cirhózou",
       "s nádorovým postihnutím pečene "],
    options: ["s obštrukčným ikterom",
       "s prehepatálnym ikterom",
       "s primárnou biliárnou cirhózou",
       "s nádorovým postihnutím pečene "],
 },
 {
    numb: 66,
    question: "Pre GMT platí",
    answer: ["aktivita GMT býva zvýšená u pacientov užívajúcich barbituráty",
       "pri alkoholových hepatopatiach",
       "pri cholestatických hepatopatiach "],
    options: ["pri diagnostike sa využíva aj vyšetrenie izoenzýmov GMT",
       "aktivita GMT býva zvýšená u pacientov užívajúcich barbituráty",
       "pri alkoholových hepatopatiach",
       "pri cholestatických hepatopatiach "],
 },
 {
    numb: 67,
    question: "O aminotransferázach možno povedať",
    answer: ["najvyššia špecifická aktivita AST je v myokarde"],
    options: ["AST je membránovo-viazaný enzým",
       "najvyššia špecifická aktivita AST je v myokarde",
       "ALT je hlavne mitochondriový enzým",
       "AST je hlavne cytosolový enzým "],
 },
 {
    numb: 68,
    question: "O aminotransferázach možno povedať",
    answer: [
      "pomer AST/ALT sa používa v hepatológii",
      "ich aktivita môže byť zvýšená po väčšej fyzickej námahe",
      "AST býva zvýšená pri ochoreniach pečene "],
    options: ["pomer AST/ALT sa používa v kardiológii",
       "pomer AST/ALT sa používa v hepatológii",
       "ich aktivita môže byť zvýšená po väčšej fyzickej námahe",
       "AST býva zvýšená pri ochoreniach pečene "],
 },
 {
    numb: 69,
    question: "ALT",
    answer: ["jej aktivita býva zvýšená u pacientov s hepatitídou typu A",
       "jej aktivita býva zvýšená u pacientov s myozitídou",
      "používa sa ako skríningové vyšetrenie pri podozrení na ochorenie pečene"],
    options: [ "jej aktivita býva zvýšená u pacientov s hepatitídou typu A",
       "jej aktivita býva zvýšená u pacientov s myozitídou",
      "používa sa ako skríningové vyšetrenie pri podozrení na ochorenie pečene",
       "je vhodný parameter pri podozrení na ochorenia srdca "],
 },
 {
    numb: 70,
    question: "ALT",
    answer: ["zvyšuje sa aj pri ľahšom ochorení pečene",
       "má nižšiu aktivitu v erytrocytoch ako AST"],
    options: ["zvyšuje sa aj pri ľahšom ochorení pečene",
       "aj malá hemolýza zvyšuje jej aktivitu v sére",
       "má nižšiu aktivitu v erytrocytoch ako AST",
       "patrí medzi cholestatické enzýmy"],
 },
 {
    numb: 71,
    question: "Výrazné zvýšenie aktivity ALT je charakteristické pre",
    answer: ["akútnu vírusovú hepatitídu"],
    options: ["akútnu vírusovú hepatitídu",
       "cirhózu pečene",
       "extrahepatálnu obštrukciu",
       "hemolýzu" ],
 },
 {
    numb: 72,
    question: "Aktivita AST v sére",
    answer: ["sa výrazne zvyšuje pri akútnych toxických hepatitídach",
       "sa zvyšuje pri myopatiach "],
    options: [ "sa výrazne zvyšuje pri akútnych toxických hepatitídach",
       "sa výrazne zvyšuje pri chronickej hepatitíde",
       "sa zvyšuje výraznejšie ako ALT u pacientov s cirhózou pečene",
       "sa zvyšuje pri myopatiach "],
 },
 {
    numb: 73,
    question: "Pomer aktivity AST+ALT/glutamátdehydrogenáza",
    answer: ["jeho hodnota sa zvyšuje u pacientov s chronickým zlyhávaním pravého srdca"],
    options: ["čím je vyšší, tym je poškodenie pečene závažnejšie",
      " jeho hodnota sa využíva u pacientov s poškodením myokardu",
       "jeho hodnota sa zvyšuje u pacientov s chronickým zlyhávaním pravého srdca",
       "používa sa ako marker intravaskulárnej hemolýzy"],
 },
 {
    numb: 74,
    question: "Cholínesteráza",
    answer: ["používa sa ako ukazovateľ proteosyntetickej funkcie pečene",
       "jej aktivita sa pri poškodení pečene obvykle znižuje"],
    options: ["zvýšenie jej aktivity indukuje alkohol",
       "používa sa ako ukazovateľ proteosyntetickej funkcie pečene",
       "jej aktivita sa pri poškodení pečene obvykle znižuje",
       "jej aktivita sa pri ochoreniach pečene zvyšuje "],
 },
 {
    numb: 75,
    question: "Cholínesteráza",
    answer: ["býva zvýšená pri obezite a hyperlipoproteinémii",
       "býva znížená pri intoxikácii organofosfátmi",],
    options: ["býva zvýšená pri obezite a hyperlipoproteinémii",
       "býva zvýšená pri užívaní barbiturátov",
       "býva znížená pri intoxikácii organofosfátmi",
       "býva zvýšená u pacientov s vírusovou hepatitídou "],
 },
 {
    numb: 76,
    question: "Medzi indikácie vyšetrenia cholínesterázy v sére patrí",
    answer: ["posúdenie funkcie pečene",
       "vyhľadávanie abnormálnych variant cholínesterázy v rámci predoperačného vyšetrenia"],
    options: ["posúdenie funkcie pečene",
       "podozrenie na intoxikáciu barbiturátmi",
       "vyhľadávanie abnormálnych variant cholínesterázy v rámci predoperačného vyšetrenia",
       "podozrenie na diabetes mellitus"],
 },
 {
    numb: 77,
    question: "Cholínesteráza ",
    answer: ["je sekrečný enzým",
      "syntetizuje sa v pečeni "],
    options: ["je indikátorový enzým",
       "je sekrečný enzým",
      " patrí medzi cholestatické enzýmy",
       "syntetizuje sa v pečeni "],
 },
 {
    numb: 78,
    question: "Kyslá fosfatáza",
    answer: ["môže pochádzať z kostného tkaniva",
       "jej aktivitu v sére tvorí viacero izoenzýmov"],
    options: ["môže pochádzať z kostného tkaniva",
       "jej aktivitu v sére tvorí viacero izoenzýmov",
       "je markerom osteoblastov",
       "jej aktivita je vyššia v plazme ako v sére"],
 },
 {
    numb: 79,
    question: "Kyslá fosfatáza",
    answer: ["môže pochádzať z trombocytov",
       "môže pochádzať z prostaty",
       "jej aktivita býva zvýšená pri osteolytických léziach "],
    options: ["môže pochádzať z trombocytov",
       "môže pochádzať z prostaty",
       "je citlivejším ukazovateľom postihnutia prostaty ako PSA",
       "jej aktivita býva zvýšená pri osteolytických léziach "],
 },
];
