let questions = [
    {
        numb: 0,
        question: "Označte rody baktérií, ktoré sú grampozitívne",
        answer: [" Lactobacillus"," Listeria"," Staphylococcus"," Streptococcus"],
        options: [" Lactobacillus"," Listeria"," Legionella"," Leptospira"," Staphylococcus"," Shigella"," Salmonella"," Streptococcus"," Streptobacillus"," Stenotrophomonas"],
     },
     {
        numb: 1,
        question: "Označte rody baktérií, ktoré sú gramnegatívne",
        answer: [" Vibrio"," Campylobacter"," Helicobacter"," Klebsiella"," Moraxella"," Neisseria"],
        options: [" Arcanobacterium"," Erysipelothrix"," Vibrio"," Enterococcus"," Campylobacter"," Faecalibacterium prausnitzii"," Helicobacter"," Klebsiella"," Moraxella"," Neisseria"],
     },
     {
        numb: 2,
        question: "Medzi dôležité faktory podporujúce tvorbu biofilmu patrí/patria",
        answer: [" elektrostatické interakcie baktérií s kolonizovaným povrchom"," bakteriálne adhezíny"," matrixové proteíny hostiteľa"," subinhibičné koncentrácie antimikrobiálnych látok"," prítomnosť cudzieho telesa v organizme hostiteľa"," prítomnosť tkaniva poškodeného primárnym patologickým procesom"],
        options: [" elektrostatické interakcie baktérií s kolonizovaným povrchom"," bakteriálne adhezíny"," matrixové proteíny hostiteľa"," prítomnosť protilátok proti bakteriálnym povrchovým antigénom"," inhibičné koncentrácie toxických látok v prostredí kolonizovanom baktériami"," subinhibičné koncentrácie antimikrobiálnych látok"," vysoká hustota bakteriálnej populácie v biofilme"," prítomnosť cudzieho telesa v organizme hostiteľa"," prítomnosť tkaniva poškodeného primárnym patologickým procesom"," tvorba disperzínov mikroorganizmami v biofilme"],
     },
     {
        numb: 3,
        question: "Biofilm",
        answer: [" pomáha baktériám odolávať pôsobeniu antimikrobiálnych liečiv"," pomáha baktériám odolávať nepriaznivým faktorom prostredia"," pomáha baktériám zachovať si vitalitu počas antibiotickej terapie"," je ložiskom, z ktorého baktérie osídľujú hostiteľa po antibiotickej terapii"," je ložiskom, z ktorého sa baktérie šíria do ostatných lokalít organizmu"],
        options: [" zvyšuje citlivosť baktérií na antimikrobiálne liečivá"," znižuje rezistenciu baktérií na antimikrobiálne liečivá"," pomáha baktériám odolávať pôsobeniu antimikrobiálnych liečiv"," pomáha baktériám odolávať nepriaznivým faktorom prostredia"," pomáha baktériám zachovať si vitalitu počas antibiotickej terapie"," po disperzii sa baktérie koncentrujú výlučne v okolí biofilmu"," je ložiskom, z ktorého baktérie osídľujú hostiteľa po antibiotickej terapii"," je ložiskom, z ktorého sa baktérie šíria do ostatných lokalít organizmu"," nie je prítomný na slizniciach zdravého človeka"," v súvislosti s antibiotickou terapiou má pre človeka len negatívny význam"],
     },
     {
        numb: 4,
        question: "Prítomnosť biofilmu je typická pre",
        answer: [" infekcie chronických rán"," endokarditídy"," chronické osteomyelitídy"," katétrové infekcie a periimplantitídy"," chronické urogenitálne infekcie"],
        options: [" akútne tonzilitídy"," infekcie chronických rán"," endokarditídy"," chronické osteomyelitídy"," katétrové infekcie a periimplantitídy"," chronické urogenitálne infekcie"," hnačky vyvolané bakteriálnymi toxínmi"," septické meningitídy novorodencov"," botulizmus"," atypické pneumónie"],
     },
     {
        numb: 5,
        question: "Pre baktérie v biofilme je charakteristické, že",
        answer: [" majú utlmenú motilitu"," intenzívne využívajú reguláciu „quorum-sensing“ systémami"," netvoria toxíny a invazíny"," vo vyššom percente prechádzajú do stavu perzistencie"," lepšie odolávajú pôsobeniu antimikrobiálnych látok"," lepšie odolávajú mechanizmom imunity hostiteľa"],
        options: [" sú virulentnejšie než planktonické formy"," majú utlmenú motilitu"," intenzívne využívajú reguláciu „quorum-sensing“ systémami"," netvoria toxíny a invazíny"," vo vyššom percente prechádzajú do stavu perzistencie"," lepšie odolávajú pôsobeniu antimikrobiálnych látok"," lepšie odolávajú mechanizmom imunity hostiteľa"," nemôžu prejsť na planktonický spôsob života"," nie sú schopné vyvolať ochorenie človeka"," existujú v biofilmovej forme len pri dysbióze"],
     },
     {
        numb: 6,
        question: "Biofilm a jeho vývoj charakterizuje",
        answer: [" adhézia mikroorganizmov a spevnenie kontaktu s kolonizovaným povrchom"," tvorba mikrokolónií a ich následné splývanie"," tvorba biofilmového matrixu"," klesanie množstva kyslíka smerom do hĺbky biofilmu"," vznik gradientov pH a Eh"," inicializácia disperzie po dosiahnutí kritickej hustoty populácie"],
        options: [" adhézia mikroorganizmov a spevnenie kontaktu s kolonizovaným povrchom"," tvorba mikrokolónií a ich následné splývanie"," tvorba biofilmového matrixu"," klesanie množstva kyslíka smerom do hĺbky biofilmu"," rovnomerné rozmiestnenie živín a metabolických produktov v matrixe"," výborný prienik antibiotík do celého objemu biofilmu"," vznik gradientov pH a Eh"," nižšia frekvencia vzniku SCV foriem a perzistujúcich buniek"," uniformný fenotyp mikroorganizmov v biofilme"," inicializácia disperzie po dosiahnutí kritickej hustoty populácie"],
     },
     {
        numb: 7,
        question: "Biofilmový matrix",
        answer: [" je vysoko hydratovaný"," jeho súčasťou sú intercelulárne polysacharidové adhezíny"," obsahuje extracelulárne polysacharidy, proteíny a voľnú DNA"," je schopný kumulovať bakteriálne enzýmy inaktivujúce antibiotiká"," je ťažko odstrániteľný z povrchu implantátov"],
        options: [" je vysoko hydratovaný"," jeho súčasťou sú intercelulárne polysacharidové adhezíny"," obsahuje extracelulárne polysacharidy, proteíny a voľnú DNA"," je schopný kumulovať bakteriálne enzýmy inaktivujúce antibiotiká"," je schopný kumulovať protilátky a komplement hostiteľa"," v organizme hostiteľa je tvorený len polymérmi mikrobiálneho pôvodu"," je štruktúrne aj obsahovo homogénny"," nepodporuje vznik viacdruhového spoločenstva mikroorganizmov"," účinne ho degradujú disperzíny tvorené organizmom hostiteľa"," je ťažko odstrániteľný z povrchu implantátov"],
     },
     {
        numb: 8,
        question: "Antibiotickú terapiu v organizme pacienta môžu ľahšie prežiť",
        answer: [" baktérie v biofilme"," L-formy baktérií"," SCV-formy baktérií"," baktérie v stave perzistencie"," klostrídie v čreve po vytvorení spór"," baktérie v stacionárnej fáze rastu"],
        options: [" rýchlo sa množiace baktérie"," baktérie v biofilme"," L-formy baktérií"," SCV-formy baktérií"," baktérie v stave perzistencie"," klostrídie v čreve po vytvorení spór"," baktérie v exponenciálnej fáze rastu"," baktérie v stacionárnej fáze rastu"," vysoko virulentné baktérie"," opuzdrené baktérie"],
     },
     {
        numb: 9,
        question: "Bakteriofágy",
        answer: [" infikujú vnímavé bakteriálne bunky"," po kontakte s receptorom inzertujú svoj genóm do baktérie"," pri lyzogénnom cykle sa inkorporujú do genómu baktérie"," môžu sa využiť pri typizácii baktérií"," sú súčasťou mikrobioty človeka"," môžu sa podieľať na prenose génov medzi baktériami"],
        options: [" v kapside obsahujú DNA aj RNA"," infikujú vnímavé bakteriálne bunky"," infikujú aj eukaryotické bunky"," po kontakte s receptorom inzertujú svoj genóm do baktérie"," môžu vyvolať ochorenie človeka"," pri lyzogénnom cykle sa inkorporujú do genómu baktérie"," pri lytickom cykle ostáva infikovaná baktéria intaktná"," môžu sa využiť pri typizácii baktérií"," sú súčasťou mikrobioty človeka"," môžu sa podieľať na prenose génov medzi baktériami"],
     },
     {
        numb: 10,
        question: "Lyzogénna konverzia bakteriálnej bunky",
        answer: [" je získanie novej genetickej informácie kódovanej genómom profága"," je následok infekcie lyzogénnym bakteriofágom"," je zmena vlastností baktérie po včlenení profága do jej chromozómu"," je zodpovedná za tvorbu difterického a botulinického toxínu"],
        options: [" je získanie novej genetickej informácie kódovanej genómom profága"," vzniká po prenose bakteriálnej DNA transdukciou"," je zmenou vlastností baktérie po prijatí voľnej bakteriálnej DNA"," je následok infekcie lyzogénnym bakteriofágom"," je následok infekcie lytickým fágom"," je následok účinku fágových endolyzínov"," je pravidelnou súčasťou fágovej terapie infekčných chorôb"," je zmena vlastností baktérie po včlenení profága do jej chromozómu"," je následkom abortívnej infekcie fágom"," je zodpovedná za tvorbu difterického a botulinického toxínu"],
     },
     {
        numb: 11,
        question: "Lyzogénnu konverziu charakterizuje",
        answer: [" baktéria obsahuje profág"," metabolizmus baktérie sa môže zmeniť"," baktéria môže získať schopnosť tvoriť toxín"," baktéria získava nové gény"," bakteriofág sa replikuje synchrónne s hostiteľskou bunkou"],
        options: [" baktéria obsahuje profág"," baktéria infikovaná fágom získava citlivosť na lyzozým"," baktéria spontánne lyzuje"," metabolizmus baktérie sa môže zmeniť"," baktéria môže získať schopnosť tvoriť toxín"," baktéria získava nové gény"," baktéria obsahuje samostatne sa replikujúci bakteriofág"," bakteriofág sa replikuje synchrónne s hostiteľskou bunkou"," baktéria stráca nepotrebné gény"," anaeróbna baktéria môže získať aeróbny metabolizmus"],
     },
     {
        numb: 12,
        question: "Fágová terapia",
        answer: [" využíva detailne charakterizované fágy"," je vhodná pre pacientov s chronickými infekciami"," je vhodná pre pacientov infikovaných polyrezistentnými baktériami"," pre zvýšenie spektra účinku sa používajú fágové koktejly"," fágy sa na mieste infekcie aktívne množia"," aplikuje sa prevažne lokálne"],
        options: [" využíva detailne charakterizované fágy"," využíva lyzogénne fágy"," je vhodná pre pacientov s chronickými infekciami"," je vhodná pre pacientov infikovaných polyrezistentnými baktériami"," pre zvýšenie spektra účinku sa používajú fágové koktejly"," fágy sa na mieste infekcie aktívne množia"," nie je určená deťom a gravidným ženám"," nie je určená imunosuprimovaným pacientom a seniorom"," aplikuje sa prevažne lokálne"," vedľajším účinkom fágovej terapie je črevná, vaginálna a orálna dysbióza"],
     },
     {
        numb: 13,
        question: "Patogenita predpokladá schopnosť mikroorganizmu",
        answer: [" vyvolať ochorenie vnímavého hostiteľa"," vyvolať ochorenie neimúnneho imunokompetentného človeka (primárny patogén)"," vyvolať ochorenie len u imunokompromitovaného človeka (oportúnny patogén)"," prekonať vrodené obranné mechanizmy hostiteľa"," poškodzovať hostiteľa (štruktúry alebo funkcie jeho organizmu)"],
        options: [" vyvolať ochorenie vnímavého hostiteľa"," vyvolať ochorenie neimúnneho imunokompetentného človeka (primárny patogén)"," vyvolať ochorenie až po znížení imunity (primárny patogén)"," vyvolať ochorenie len u imunokompromitovaného človeka (oportúnny patogén)"," meniť zloženie normálnej bakteriálnej flóry hostiteľa"," prekonať vrodené obranné mechanizmy hostiteľa"," poškodzovať hostiteľa (štruktúry alebo funkcie jeho organizmu)"," potláčať množenie nepatogénnychbaktérií"," kolonizovať kožu a sliznice človeka"," sporulovať v infikovanom tkanive hostiteľa"],
     },
     {
        numb: 14,
        question: "Virulencia mikroorganizmu",
        answer: [" je konkrétny stupeň patogénnosti daného kmeňa"," je geneticky podmienená vlastnosť kódovaná akcesórnymi génmi"," závisí od spektra a kvantity produkovaných faktorov virulencie"," môže sa zvýšiť alebo znížiť prirodzene alebo génovými manipuláciami"," jej znížením vznikne atenuovaný kmeň vhodný pre vakcináciu"," jej zvýšením sa môže pripraviť biologická zbraň"],
        options: [" je schopnosť mikrobiálneho druhu vyvolávať ochorenia"," je rodová charakteristika mikroorganizmu"," je druhová charakteristika mikroorganizmu, kódovaná esenciálnymi génmi"," je konkrétny stupeň patogénnosti daného kmeňa"," je geneticky podmienená vlastnosť kódovaná akcesórnymi génmi"," závisí od spektra a kvantity produkovaných faktorov virulencie"," je stabilnou vlastnosťou bakteriálneho kmeňa"," môže sa zvýšiť alebo znížiť prirodzene alebo génovými manipuláciami"," jej znížením vznikne atenuovaný kmeň vhodný pre vakcináciu"," jej zvýšením sa môže pripraviť biologická zbraň"],
     },
     {
        numb: 15,
        question: "Baktérie tvorbou biofilmu obvykle spôsobujú",
        answer: [" zlyhanie antimikrobiálnej terapie"," problémy pri hojení rán a popálenín"," zlyhanie implantátu"," upchatie užších katétrov a stentov po enkrustácii biofilmu"," zápalovú reakciu v okolí biofilmu"," vznik perzistujúceho ložiska infekcie"],
        options: [" zlyhanie antimikrobiálnej terapie"," akútny fulminantný priebeh infekcie"," problémy pri hojení rán a popálenín"," vznik autoimunitných reakcií"," zlyhanie implantátu"," lýzu implantátov"," upchatie užších katétrov a stentov po enkrustácii biofilmu"," reakcie včasnej precitlivenosti v okolí implantátu"," zápalovú reakciu v okolí biofilmu"," vznik perzistujúceho ložiska infekcie"],
     },
     {
        numb: 16,
        question: "Komenzálne mikroorganizmy na koži a slizniciach",
        answer: [" žijú v eubióze a vo vzájomne prospešnom vzťahu s hostiteľom"," bakteriocínmi a produktmi metabolizmom inhibujú rast patogénov"," produktmi metabolizmu podporujú správnu funkciu slizníc"," podporujú správny vývoj imunitného systému"," ich spektrum a kvantita v čreve je v asociácii so vznikom obezity a karcinómu čreva"],
        options: [" žijú v eubióze a vo vzájomne prospešnom vzťahu s hostiteľom"," bakteriocínmi a produktmi metabolizmom inhibujú rast patogénov"," produktmi metabolizmu podporujú správnu funkciu slizníc"," podporujú správny vývoj imunitného systému"," ich spektrum a kvantita v čreve je v asociácii so vznikom obezity a karcinómu čreva"," nie sú zdrojom endogénnych infekcií svojho hostiteľa"," bránia prenosu plazmidov medzi patogénnymi mikroorganizmami"," spotrebúvajú kyslík potrebný pre patogénne mikroorganizmy"," sú dramaticky devastované počas fágovej terapie"," nie sú ovplyvnené systémovou antibiotickou liečbou"],
     },
     {
        numb: 17,
        question: "Sterilizácia",
        answer: [" inaktivuje alebo odstraňuje všetky infekčné častice"," využíva fyzikálne aj chemické metódy"," vyžaduje vyššie koncentrácie chemických látok a dlhšie expozičné časy"," nie je aplikovateľná na kožu, sliznice a rany"," kontroluje sa fyzikálnymi, chemickými a biologickými metódami"],
        options: [" inaktivuje alebo odstraňuje všetky infekčné častice"," inaktivuje len patogénne mikroorganizmy"," inaktivuje všetky infekčné častice okrem spór a priónov"," inaktivuje iba vegetatívne formy mikroorganizmov"," využíva fyzikálne aj chemické metódy"," nepôsobí na perzistujúce a dormantné mikroorganizmy"," vyžaduje vyššie koncentrácie chemických látok a dlhšie expozičné časy"," nie je aplikovateľná na kožu, sliznice a rany"," je možná iba v prostredí a vysokou teplotou (nad 100 °C)"," kontroluje sa fyzikálnymi, chemickými a biologickými metódami"],
     },
     {
        numb: 18,
        question: "Sterilizáciu môžeme dosiahnuť",
        answer: [" pôsobením etylénoxidu"," pôsobením gama-žiarenia"," opakovaným varom (frakcionovaná sterilizácia)"," studenou plazmou z pár H2O2 alebo kyseliny peroctovej"," parou pod tlakom v autokláve"," vypaľovaním kovových nástrojov nad plameňom kahana"],
        options: [" pôsobením etylénoxidu"," pôsobením gama-žiarenia"," opakovaným varom (frakcionovaná sterilizácia)"," jódpovidonom aplikovaným na kožu a sliznice"," studenou plazmou z pár H2O2 alebo kyseliny peroctovej"," parou pod tlakom v autokláve"," filtráciou filtrom s priemerom pórov viac než 0,45 m"," pasterizáciou"," dlhšie trvajúcim varom"," vypaľovaním kovových nástrojov nad plameňom kahana"],
     },
     {
        numb: 19,
        question: "Na sterilizáciu je v ambulancii lekára možné použiť",
        answer: [" autokláv"," horúcovzdušný sterilizátor"," plazmový sterilizátor"," UV žiarič (iba povrchy a vzduch)"," plameň kahana"],
        options: [" autokláv"," gama-žiarič"," horúcovzdušný sterilizátor"," plazmový sterilizátor"," Kochov prístroj (para s teplotou 100°C)"," UV žiarič (iba povrchy a vzduch)"," vriacu vodu"," fén"," antibiotiká"," plameň kahana"],
     },
     {
        numb: 20,
        question: "Dezinfekcia",
        answer: [" podstatne znižuje počet kontaminujúcich mikroorganizmov"," vyšší stupeň dezinfekcie nie je účinný na vajíčka a cysty parazitov"," inaktivuje iba vegetatívne formy mikroorganizmov"," je účinnejšia na obalené vírusy než na neobalené"," mechanické odstránenie nečistôt zvyšuje jej účinnosť"],
        options: [" podstatne znižuje počet kontaminujúcich mikroorganizmov"," vyšší stupeň dezinfekcie nie je účinný na vajíčka a cysty parazitov"," nevyužíva kombinované prípravky"," inaktivuje iba vegetatívne formy mikroorganizmov"," je účinnejšia na obalené vírusy než na neobalené"," neovplyvňuje ju štruktúra dezinfikovaného povrchu"," mechanické odstránenie nečistôt zvyšuje jej účinnosť"," účinne a spoľahlivo inaktivuje patologické priónové molekuly"," nie je schopná ovplyvniť baktérie v biofilme"," neúčinkuje na nozokomiálne kmene mikroorganizmov"],
     },
     {
        numb: 21,
        question: "Na dezinfekciu je možné použiť",
        answer: [" var"," oxidačné látky"," bakteriologické filtre"," nanočastice striebra"," striedanie jednotlivých skupín dezinfekčných prípravkov"],
        options: [" var"," gentamicín"," oxidačné látky"," vysoké koncentrácie glukózy"," oplachovanie vodou"," bakteriologické filtre"," nanočastice striebra"," zubnú kefku"," striedanie jednotlivých skupín dezinfekčných prípravkov"," viditeľné spektrum slnečného svetla"],
     },
     {
        numb: 22,
        question: "Medzi dezinfekčné činidlá patria",
        answer: [" kyselina peroctová"," plynný chlór"," glutaraldehyd"," chlórnan sodný"," ozón (v špeciálnych prístrojoch sa môže použiť aj na sterilizáciu)"," nehasené vápno"],
        options: [" acyklovir"," kyselina peroctová"," plynný chlór"," 25 % etanol"," glutaraldehyd"," chlórnan sodný"," bacitracín"," ozón (v špeciálnych prístrojoch sa môže použiť aj na sterilizáciu)"," zinková masť"," nehasené vápno"],
     },
     {
        numb: 23,
        question: "Antiseptiká",
        answer: [" sú netoxické, nedráždivé a nie sú karcinogénne"," používajú sa v zdravotníctve na ošetrenie pacientov"," nepôsobia na intracelulárne umiestnené mikroorganizmy"," pri lokálnych infekciách imunokompetentných pacientov môžu nahradiť antibiotiká"," pôsobia nešpecificky reakciami s biogénnymi molekulami mikroorganizmov"," poškodzujú biologické membrány, DNA a molekuly bielkovín"],
        options: [" sú netoxické, nedráždivé a nie sú karcinogénne"," používajú sa v zdravotníctve na ošetrenie pacientov"," voči žiadnemu z nich nemôže vzniknúť rezistencia"," nepôsobia na intracelulárne umiestnené mikroorganizmy"," pri lokálnych infekciách imunokompetentných pacientov môžu nahradiť antibiotiká"," pôsobia nešpecificky reakciami s biogénnymi molekulami mikroorganizmov"," na mikroorganizmy pôsobia cielene, podobne ako antibiotiká"," poškodzujú biologické membrány, DNA a molekuly bielkovín"," na predoperačnú prípravu pacienta nie sú vhodné"," účinkujú na všetky formy mikroorganizmov"],
     },
     {
        numb: 24,
        question: "Medzi antiseptiká patria",
        answer: [" niektoré zlúčeniny striebra"," 3 % peroxid vodíka"," oktenidín"," kvartérne amóniové soli"," chlórhexidín"," jódpovidon"],
        options: [" niektoré zlúčeniny striebra"," amfotericín B"," 3 % peroxid vodíka"," gama žiarenie"," oktenidín"," kvartérne amóniové soli"," chlórnan sodný"," etylénoxid"," chlórhexidín"," jódpovidon"],
     },
     {
        numb: 25,
        question: "Cieľom kultivačnej mikrobiologickej diagnostiky je",
        answer: [" izolovať pôvodcu ochorenia z biologického materiálu"," získať čistú kultúru mikroorganizmu na ďalšie vyšetrovanie"," určiť základné rastové a metabolické vlastnosti mikroorganizmu"," rozmnožiť mikroorganizmy prítomné vo vzorke"," posúdiť kvantitatívne zastúpenie mikroorganizmov vo vzorke"," predbežne identifikovať mikroorganizmy na chromogénnych médiách"],
        options: [" posúdiť virulenciu izolovaného mikroorganizmu"," izolovať pôvodcu ochorenia z biologického materiálu"," získať čistú kultúru mikroorganizmu na ďalšie vyšetrovanie"," určiť základné rastové a metabolické vlastnosti mikroorganizmu"," rozmnožiť mikroorganizmy prítomné vo vzorke"," posúdiť patogenitu mikroorganizmu"," detegovať gény rezistencie"," určiť antigénové vybavenie mikroorganizmu"," posúdiť kvantitatívne zastúpenie mikroorganizmov vo vzorke"," predbežne identifikovať mikroorganizmy na chromogénnych médiách"],
     },
     {
        numb: 26,
        question: "Pri charakteristike bakteriálnych kolónií si všímame",
        answer: [" veľkosť"," okraj"," tvar"," povrch"," farbu a zápach"," konzistenciu"," zmeny kultivačnej pôdy v ich okolí"],
        options: [" veľkosť"," okraj"," objem"," výšku"," tvar"," povrch"," farbu a zápach"," konzistenciu"," rozmiestnenie na povrchu pôdy"," zmeny kultivačnej pôdy v ich okolí"],
     },
     {
        numb: 27,
        question: "Medzi selektívne alebo diagnostické pôdy pre črevné patogény patria",
        answer: [" alkalická peptónová voda"," selenitový bujón"," pôdy s prítomnosťou laktózy"," MacConkeyov agar"," deoxycholátový citrátový agar"],
        options: [" Schaedlerov agar"," alkalická peptónová voda"," Levithalova pôda"," selenitový bujón"," Sabouraudova pôda"," krvný agar"," čokoládový agar"," pôdy s prítomnosťou laktózy"," MacConkeyov agar"," deoxycholátový citrátový agar"],
     },
     {
        numb: 28,
        question: "Laktózu štiepi väčšina kmeňov týchto črevných baktérií",
        answer: [" Escherichia spp."," Enterobacter spp."," Klebsiella spp."," Cronobacter spp."," Citrobacter spp."],
        options: [" Escherichia spp."," Enterobacter spp."," Klebsiella spp."," Cronobacter spp."," Citrobacter spp."," Shigella spp."," Yersinia spp."," Salmonella spp."," Morganella spp."," Proteus spp."],
     },
     {
        numb: 29,
        question: "Beta-hemolýzu môžu na krvnom agare spôsobovať",
        answer: [" Streptococcus pyogenes"," Streptococcus agalactiae"," Escherichia coli"," Staphylococcus aureus"," Pseudomonas aeruginosa"," Listeria monocytogenes"],
        options: [" Streptococcus salivarius"," Streptococcus pyogenes"," Streptococcus agalactiae"," Streptococcus mutans"," Escherichia coli"," Staphylococcus aureus"," Pseudomonas aeruginosa"," Proteus mirabilis"," Listeria monocytogenes"," Salmonella Enteritidis"],
     },
     {
        numb: 30,
        question: "Anaeróbne prostredie pri kultivácii sa dá zabezpečiť",
        answer: [" v anaerostate fyzikálnym odstránením kyslíka"," regeneráciou vysoko naliatych pôd teplom (pred naočkovaním)"," chemicky katalytickou oxidáciou vodíka v anaerostate"," chemicky vo vakoch pre anaeróbnu kultiváciu"],
        options: [" hermetickým uzatvorením termostatu"," v anaerostate fyzikálnym odstránením kyslíka"," regeneráciou vysoko naliatych pôd teplom (pred naočkovaním)"," v sušičke s exikátorom"," v Kochovom prístroji"," metódou podľa Giemsu"," Burriho metódou"," chemicky katalytickou oxidáciou vodíka v anaerostate"," chemicky vo vakoch pre anaeróbnu kultiváciu"," umiestnením naočkovanej vzorky v nevetranom termostate"],
     },
];


