let questions = [
   {
      numb: 0,
      question: "Archaea",
      answer: [" transkripcia v nich prebieha podobne ako v eukaryotických bunkách"," viaceré mezofilné druhy sú súčasťou mikrobioty človeka"," väčšina z nich nerastie na dostupných kultivačných pôdach"," obsahujú unikátne enzýmy"," sú citlivé na statíny"],
      options: [" majú eukaryotický typ buniek"," transkripcia v nich prebieha podobne ako v eukaryotických bunkách"," viaceré mezofilné druhy sú súčasťou mikrobioty človeka"," väčšina z nich nerastie na dostupných kultivačných pôdach"," obsahujú unikátne enzýmy"," v bunkovej stene majú peptidoglykán"," DNA replikujú podobne ako baktérie"," sú citlivé na statíny"," všetky sú v raste inhibované teplotou nad 70°C"," nie sú citlivé na fágy"],
   },
   {
      numb: 1,
      question: "Bakteriálne bunky sa líšia od eukaryotických",
      answer: [" jednoduchšou štruktúrou a organizáciou bunky"," tvorbou ATP na cytoplazmatickej membráne"," neprítomnosťou jadra a jadrovej membrány"," odlišným typom ribozómov"," odlišným spôsobom replikácie DNA"," neprítomnosťou lamelárnych systémov v cytoplazme"],
      options: [" jednoduchšou štruktúrou a organizáciou bunky"," tvorbou ATP na cytoplazmatickej membráne"," neprítomnosťou jadra a jadrovej membrány"," odlišným typom mitochondrií"," neprítomnosťou fimbrií"," polyploidným genómom"," odlišným typom ribozómov"," zložitejšou stavbou bičíkov"," odlišným spôsobom replikácie DNA"," neprítomnosťou lamelárnych systémov v cytoplazme"],
   },
   {
      numb: 2,
      question: "Pre baktérie sú typické nasledujúce vlastnosti",
      answer: [" v bunkovej stene väčšiny baktérií sa nachádza peptidoglykán"," štruktúry bunkovej steny baktérií sú rozpoznávané PRR receptormi hostiteľa"," baktérie sú schopné prejsť do stavu perzistencie"," pre baktérie je výhodnejšia biofilmová forma rastu"," dýchací reťazec majú baktérie lokalizovaný na cytoplazmatickej membráne"," proteosyntéza baktérií prebieha ináč než v eukaryotickej bunke"],
      options: [" v bunkovej stene väčšiny baktérií sa nachádza peptidoglykán"," bakteriálne ribozómy sú vždy umiestnené voľne v cytoplazme"," štruktúry bunkovej steny baktérií sú rozpoznávané PRR receptormi hostiteľa"," všetky baktérie sú schopné tvoriť vlastné molekuly ATP"," všetky baktérie sú kultivovateľné na kultivačných médiách"," baktérie sú schopné prejsť do stavu perzistencie"," pre baktérie je výhodnejšia biofilmová forma rastu"," dýchací reťazec majú baktérie lokalizovaný na cytoplazmatickej membráne"," väčšina baktérií môže vytvárať spóry"," proteosyntéza baktérií prebieha ináč než v eukaryotickej bunke"],
   },
   {
      numb: 3,
      question: "V cytoplazme baktérií sa nachádza",
      answer: [" bakteriálny chromozóm"," plazmidy"," ribozómy"," mRNA a tRNA"," zásobné granuly"],
      options: [" bakteriálny chromozóm"," plazmidy"," ribozómy"," mRNA a tRNA"," zásobné granuly"," lyzozómy"," mitochondrie"," fagocytárne vakuoly"," Golgiho komplex"," jadro s jadierkom"],
   },
   {
      numb: 4,
      question: "Cytoplazmatická membrána baktérií",
      answer: [" s výnimkou mykoplaziem a ureaplaziem neobsahuje cholesterol"," generuje sa na nej energia pre bičíky, transportné systémy a tvorbu ATP"," obsahuje efluxné systémy pre antibiotiká a iné toxické látky"," jej základ tvorí fosfolipidová dvojvrstva"," sú v nej ukotvené bičíky a fimbrie baktérií"," sú v nej ukotvené sekrečné systémy baktérií"],
      options: [" s výnimkou mykoplaziem a ureaplaziem neobsahuje cholesterol"," generuje sa na nej energia pre bičíky, transportné systémy a tvorbu ATP"," obsahuje efluxné systémy pre antibiotiká a iné toxické látky"," nie je spojená s ribozómami ani s bakteriálnym chromozómom"," jej základ tvorí fosfolipidová dvojvrstva"," podmieňuje tvar a osmotickú stabilitu bakteriálnej bunky"," antimikrobiálne liečivá ju nepoškodzujú"," pasívne cez ňu prechádzajú aj väčšie hydrofilné molekuly"," sú v nej ukotvené bičíky a fimbrie baktérií"," sú v nej ukotvené sekrečné systémy baktérií"],
   },
   {
      numb: 5,
      question: "Bunková stena baktérií",
      answer: [" rozhoduje o type farbiteľnosti podľa Grama"," poskytuje baktériám mechanickú a osmotickú stabilitu"," obsahuje antigény využiteľné v mikrobiologickej diagnostike"," chýba pri rodoch Mycoplasma a Ureaplasma"," je cieľovou štruktúrou pre beta-laktámové a glykopeptidové ATB"],
      options: [" baktérie po jej strate vždy lyzujú"," rozhoduje o type farbiteľnosti podľa Grama"," poskytuje baktériám mechanickú a osmotickú stabilitu"," prekrýva a maskuje dôležité adhezíny baktérií"," obsahuje antigény využiteľné v mikrobiologickej diagnostike"," chýba pri rodoch Mycoplasma a Ureaplasma"," je cieľovou štruktúrou pre beta-laktámové a glykopeptidové ATB"," na jej lýze sa zúčastňujú proteolytické enzýmy fagocytov"," je pravidelne rezistentná voči lyzozýmu"," L-formy baktérií majú bunkovú stenu významne zhrubnutú"],
   },
   {
      numb: 6,
      question: "Bunková stena grampozitívnych baktérií obsahuje/môže obsahovať",
      answer: [" hrubú vrstvu peptidoglykánu"," kyselinu teichoovú"," puzdro"," proteínové adhezíny"," proteíny viažuce penicilín (PBP)"],
      options: [" hrubú vrstvu peptidoglykánu"," proteíny vonkajšej membrány"," kyselinu teichoovú"," puzdro"," cholesterol"," poríny"," proteínové adhezíny"," proteíny viažuce penicilín (PBP)"," vonkajšiu fosfolipidovú membránu s lipopolysacharidom"," mykolové kyseliny"],
   },
   {
      numb: 7,
      question: "Bunková stena gramnegatívnych baktérií obsahuje",
      answer: [" lipopolysacharid"," proteíny vonkajšej membrány (OMP)"," tenšiu peptidoglykánovú vrstvu"," poríny"," periplazmatický priestor"],
      options: [" lyzozým"," kovalentne viazanú penicilinázu"," arabinogalaktan"," kyselinu teichoovú"," lipopolysacharid"," proteíny vonkajšej membrány (OMP)"," tenšiu peptidoglykánovú vrstvu"," vyššie nenasýtené mastné kyseliny"," poríny"," periplazmatický priestor"],
   },
   {
      numb: 8,
      question: "Vonkajšia membrána gramnegatívnych baktérií",
      answer: [" je tvorená asymetrickou lipidovou dvojvrstvou"," sú v nej včlenené molekuly lipopolysacharidu"," po jej rozpade sa uvoľní do prostredia veľké množstvo endotoxínu"," obsahuje proteíny vonkajšej membrány, exportné systémy a receptory"," sú do nej včlenené porínové proteíny regulujúce priechod veľkých molekúl"],
      options: [" je tvorená asymetrickou lipidovou dvojvrstvou"," sú v nej včlenené molekuly lipopolysacharidu"," po jej rozpade sa uvoľní do prostredia veľké množstvo endotoxínu"," obsahuje proteíny vonkajšej membrány, exportné systémy a receptory"," sú do nej včlenené porínové proteíny regulujúce priechod veľkých molekúl"," je rezistentná voči lytickému komplexu komplementu"," je stabilná aj v prostredí chelátotvorných látok"," je odolná voči pôsobeniu nepolárnych rozpúšťadiel"," poškodzuje ju pôsobenie lyzozýmu"," je priepustná pre všetky antibiotiká"],
   },
   {
      numb: 9,
      question: "Bunková stena acidorezistentných baktérií obsahuje",
      answer: [" peptidoglykán"," mykolové kyseliny"," arabinogalaktan"," lipoarabinomanan"," dimykolát trehalózy"],
      options: [" peptidoglykán"," mykolové kyseliny"," arabinogalaktan"," lipoarabinomanan"," dimykolát trehalózy"," cholesterol"," lipopolysacharid"," kyselinu lipoteichoovú"," poríny"," chitín"],
   },
   {
      numb: 10,
      question: "Bunková stena acidorezistentných baktérií je zodpovedná za",
      answer: [" hydrofóbnosť povrchu acidorezistentných baktérií"," rezistenciu voči vysušeniu"," citlivosť mykobaktérií na izoniazid, etionamid a etambutol"," rezistenciu voči degradácii baktérií komplementom a lyzozýmom"," pomalý rast acidorezistentných baktérií"," tvorbu granulómov a chronický priebeh infekcie"],
      options: [" hydrofóbnosť povrchu acidorezistentných baktérií"," extrémnu citlivosť na kyseliny, zásady a alkoholy"," rezistenciu voči vysušeniu"," dobrú farbiteľnosť podľa Grama"," citlivosť mykobaktérií na izoniazid, etionamid a etambutol"," rezistenciu voči degradácii baktérií komplementom a lyzozýmom"," zvýšenú citlivosť na dezinfekčné prostriedky"," akútny priebeh tuberkulózy a mykobakterióz"," pomalý rast acidorezistentných baktérií"," tvorbu granulómov a chronický priebeh infekcie"],
   },
   {
      numb: 11,
      question: "K priamej mikrobiologickej diagnostike patrí",
      answer: [" dôkaz prítomnosti mikrobiálnych antigénov vo vzorke"," mikroskopické vyšetrenie vzorky"," kultivačné vyšetrenie vzorky"," izolácia pôvodcu ochorenia zo vzorky"," dôkaz nukleovej kyseliny pôvodcu vo vzorke"," dôkaz toxínov pôvodcu vo vzorke"],
      options: [" dôkaz prítomnosti mikrobiálnych antigénov vo vzorke"," mikroskopické vyšetrenie vzorky"," kultivačné vyšetrenie vzorky"," izolácia pôvodcu ochorenia zo vzorky"," dôkaz nukleovej kyseliny pôvodcu vo vzorke"," dôkaz toxínov pôvodcu vo vzorke"," dôkaz a kvantifikácia špecifických protilátok vo vzorke"," dôkaz špecifickej bunkovej imunity kožnými testami"," dôkaz tvorby IFN-gama po špecifickom antigénovom stimule vo vzorke krvi"," IGRA-test na dôkaz špecifickej bunkovej imunity"],
   },
   {
      numb: 12,
      question: "Odber materiálu",
      answer: [" riadi sa klinickými príznakmi pacienta"," robí sa asepticky sterilnými odberovými pomôckami"," odber krvi na dôkaz protilátok sa robí ráno nalačno"," odobratý materiál sa musí hneď označiť údajmi pacienta"," nesmie ohroziť pacienta zavlečením mikróbov na fyziologicky sterilné miesta"],
      options: [" riadi sa klinickými príznakmi pacienta"," má sa vykonať až po prvej dávke antibiotika"," robí sa asepticky sterilnými odberovými pomôckami"," odber krvi na hemokultiváciu sa robí ráno nalačno"," odber krvi na dôkaz protilátok sa robí ráno nalačno"," moč na kultiváciu sa môže odobrať hocikedy a aj bez poučenia pacienta"," odobratý materiál sa musí hneď označiť údajmi pacienta"," nesmie ohroziť pacienta zavlečením mikróbov na fyziologicky sterilné miesta"," na sprievodný lístok nie je potrebné uviesť typ vzorky ani údaje o terapii"," si vždy môže urobiť aj sám pacient"],
   },
   {
      numb: 13,
      question: "Mikroskopický preparát z klinického materiálu poskytuje informácie o",
      answer: [" tvare, usporiadaní a farbiteľnosti mikroorganizmov"," množstve jednotlivých morfotypov mikroorganizmov v preparáte"," prítomnosti epitelových buniek, ich type a kvantite"," prítomnosti leukocytov, ich type a kvantite"," kontaminácii odobratého materiálu sprievodnou flórou"," prítomnosti puzdier a biofilmového matrixu"],
      options: [" tvare, usporiadaní a farbiteľnosti mikroorganizmov"," množstve jednotlivých morfotypov mikroorganizmov v preparáte"," prítomnosti epitelových buniek, ich type a kvantite"," prítomnosti leukocytov, ich type a kvantite"," citlivosti baktérií v preparáte na antibiotiká"," zastúpení živých a mŕtvych baktérií"," tvorbe toxínov mikroorganizmami v natívnom preparáte"," patogénnosti mikroorganizmu"," kontaminácii odobratého materiálu sprievodnou flórou"," prítomnosti puzdier a biofilmového matrixu"],
   },
   {
      numb: 14,
      question: "Medzi pravidelne mikroskopované materiály patrí",
      answer: [" likvor"," spútum"," materiály z fyziologicky sterilných miest organizmu"," stolica (určená na parazitologické vyšetrenie)"," výter cervixu, vagíny a uretry"," hemokultúra (po signalizácii pozitivity)"],
      options: [" likvor"," spútum"," materiály z fyziologicky sterilných miest organizmu"," výter tonzíl a nazofaryngu"," výter rekta"," stolica (určená na parazitologické vyšetrenie)"," stolica (určená na bakteriologické vyšetrenie)"," výter cervixu, vagíny a uretry"," krv bezprostredne po odbere"," hemokultúra (po signalizácii pozitivity)"],
   },
   {
      numb: 15,
      question: "Natívny preparát sa používa pri",
      answer: [" dôkaze puzdra (Neufeldova reakcia)"," dôkaze pohybu baktérií"," dôkaze bičíkov"," diagnostike infekcií vyvolaných spirochétami"," diagnostike pôvodcu tvrdého vredu"," pri diagnostike návratnej horúčky"],
      options: [" dôkaze puzdra (Neufeldova reakcia)"," dôkaze pohybu baktérií"," dôkaze bičíkov"," diagnostike infekcií vyvolaných spirochétami"," diagnostike streptokokovej angíny"," diagnostike pôvodcu tvrdého vredu"," diagnostike pôvodcu mäkkého vredu"," diagnostike kvapavky"," pri diagnostike návratnej horúčky"," diagnostike malárie"],
   },
   {
      numb: 16,
      question: "Mikroskopický preparát možno fixovať",
      answer: [" teplom"," teplom alebo fixačnými látkami"," metylalkoholom"," metylalkoholom alebo teplom"],
      options: [" teplom"," zmrazovaním a následným pomalým rozmrazovaním"," teplom alebo fixačnými látkami"," metylalkoholom"," metylalkoholom alebo teplom"," sušením pri laboratórnej teplote"," silným zahrievaním nad plameňom použitím fixačných látok"," 10% KOH"," lyofilizáciou"," tušom"],
   },
   {
      numb: 17,
      question: "Orientačné farbenie môže pozostávať z",
      answer: [" fixácie a monochromatického farbenia"," fixácie a farbenia metylénovou modrou"," fixácie a farbenia karbolfuchsínom"," fixácie a farbenia jedným farbivom"],
      options: [" fixácie a monochromatického farbenia"," farbenia natívneho preparátu bez fixácie bázickým farbivom"," fixácie a mikroskopického vyhodnotenia bez farbenia"," fixácie a polychromatického farbenia"," fixácie a farbenia metylénovou modrou"," fixácie a farbenia karbolfuchsínom"," fixácie a farbenia Burriho metódou"," fixácie a farbenia jedným farbivom"," aplikácie enzýmom značených protilátok na preparát"," využitia fluorescenčnej in-situ hybridizácie"],
   },
   {
      numb: 18,
      question: "Medzi zložky postupu Gramovho farbenia patria",
      answer: [" fixovanie preparátu"," farbenie kryštálovou violeťou"," morenie pomocou Lugolovho roztoku"," odfarbovanie acetónom"," oplachovanie vodou"," dofarbovanie zriedeným karbolfuchsínom"],
      options: [" fixovanie preparátu"," farbenie koncentrovaným karbolfuchsínom"," zahrievanie preparátu s farbivom"," farbenie kryštálovou violeťou"," morenie pomocou Lugolovho roztoku"," odfarbovanie acetónom"," odfarbovanie kyslým alkoholom"," oplachovanie vodou"," dofarbovanie metylénovou modrou"," dofarbovanie zriedeným karbolfuchsínom"],
   },
   {
      numb: 19,
      question: "Označte baktérie, ktoré sa nedajú vidieť po farbení podľa Grama",
      answer: [" mykoplazmy a ureaplazmy"," riketsie"," mykobaktérie"," chlamýdie"," väčšina spirochét"],
      options: [" mykoplazmy a ureaplazmy"," nokardie"," riketsie"," bordetely"," mykobaktérie"," legionely"," vibriá"," chlamýdie"," listérie"," väčšina spirochét"],
   },
   {
      numb: 20,
      question: "Súčasťou farbenia podľa Ziehla-Neelsena je",
      answer: [" fixácia preparátu teplom"," farbenie koncentrovaným karbolfuchsínom"," zahrievanie preparátu pri farbení až do výstupu pár"," odfarbovanie kyslým alkoholom"," farbenie malachitovou zeleňou"],
      options: [" fixácia preparátu teplom"," fixácia alkalickým činidlom"," farbenie koncentrovaným karbolfuchsínom"," farbenie koncentrovanou kryštálovou violeťou"," zahrievanie preparátu pri farbení až do výstupu pár"," morenie Lugolovým roztokom"," odfarbovanie acetónom"," odfarbovanie kyslým alkoholom"," farbenie malachitovou zeleňou"," dofarbovanie zriedeným karbolfuchsínom"],
   },
   {
      numb: 21,
      question: "Pri Ziehlovom-Neelsenovom farbení sa používa",
      answer: [" koncentrovaný karbolfuchsín"," kyslý alkohol na odfarbovanie"," voda na oplachovanie"," metylénová modrá na dofarbovanie"," koncentrované farbivo za tepla"," malachitová zeleň na kontrastné farbenie"],
      options: [" Lugolov roztok"," koncentrovaný karbolfuchsín"," acetón na odfarbovanie"," kyslý alkohol na odfarbovanie"," voda na oplachovanie"," metylénová modrá na dofarbovanie"," koncentrované farbivo za tepla"," suspenziu tušu na zvýraznenie pozadia"," malachitová zeleň na kontrastné farbenie"," KOH na zvýraznenie baktérií"],
   },
   {
      numb: 22,
      question: "Koncentrovaná malachitová zeleň za horúca sa používa na",
      answer: [" farbenie spór rodu Bacillus"," farbenie spór rodu Clostridium"," štúdium baktérií tvoriacich spóry"],
      options: [" farbenie bakteriálnych puzdier"," znázornenie intracelulárnych baktérií"," farbenie spór rodu Bacillus"," farbenie spór rodu Clostridium"," dôkaz acidorezistentných baktérií"," dôkaz bičíkov"," štúdium baktérií tvoriacich puzdrá"," štúdium baktérií tvoriacich spóry"," farbenie mykobaktérií"," kontrastné farbenie pozadia mykobaktérií"],
   },
   {
      numb: 23,
      question: "Burriho metóda",
      answer: [" môže sa kombinovať s monochromatickým farbením bakteriálnych buniek"," zviditeľňuje bakteriálne puzdrá vo fixovanom preparáte"," jeho modifikáciou je natívny tušový preparát"," využíva tušový roztok na tmavé pozadia pre opuzdrené mikroorganizmy"," slúži na dôkaz kryptokokov v likvore"],
      options: [" sa využíva na farbenie acidorezistentných baktérií"," môže sa kombinovať s monochromatickým farbením bakteriálnych buniek"," je fixovanie náterov Burriho roztokom"," zvýrazňuje bakteriálne spóry v preparáte"," slúži na štúdium bakteriálnych granúl"," zviditeľňuje bakteriálne puzdrá vo fixovanom preparáte"," jeho modifikáciou je natívny tušový preparát"," využíva tušový roztok na tmavé pozadia pre opuzdrené mikroorganizmy"," sa používa na dôkaz legionel v spúte"," slúži na dôkaz kryptokokov v likvore"],
   },
   {
      numb: 24,
      question: "Na dôkaz puzdra baktérií sa používa",
      answer: [" sérologická reakcia so špecifickými protilátkami"," Burriho metóda"," test napučiavania puzdra (Neufeldova reakcia)"," tušový preparát kombinovaný monochromatickým farbením"," natívny tušový preparát"],
      options: [" sérologická reakcia so špecifickými protilátkami"," Ziehlovo-Neelsenovo farbenie"," Burriho metóda"," Wrightovo farbenie"," Giemsovo farbenie"," farbenie metylénovou modrou"," farbenie koncentrovanými farbivami za horúca"," test napučiavania puzdra (Neufeldova reakcia)"," tušový preparát kombinovaný monochromatickým farbením"," natívny tušový preparát"],
   },
   {
      numb: 25,
      question: "Pohyblivosť baktérií sa zisťuje",
      answer: [" pozorovaním natívneho preparátu v tmavom poli"," kultiváciou baktérie v polotekutom médiu"," pozorovaním natívneho preparátu v mikroskope"," mikroskopiou natívneho preparátu pod fázovým kontrastom"," špeciálnym farbením bičíkov baktérií"],
      options: [" metódou podľa Giemsu"," pozorovaním natívneho preparátu v tmavom poli"," kultiváciou baktérie v polotekutom médiu"," metódou podľa Grama"," Burriho metódou"," pozorovaním natívneho preparátu v mikroskope"," mikroskopiou natívneho preparátu pod fázovým kontrastom"," špeciálnym farbením bičíkov baktérií"," dôkazom génov pre tvorbu bičíkov"," pozorovaním fixovaného preparátu pod fázovým kontrastom"],
   },
   {
      numb: 26,
      question: "Giemsovo farbenie sa môže využiť pri dôkaze",
      answer: [" protozoálnych parazitóz"," vnútrobunkovo umiestnených baktérií"," morúl pri ehrlichióze"," anaplaziem v granulocytoch"," retikulárnych teliesok chlamýdií"],
      options: [" puzdra"," protozoálnych parazitóz"," chitínovej bunkovej steny húb"," špirálovitých baktérií"," acidorezistentných baktérií"," vnútrobunkovo umiestnených baktérií"," morúl pri ehrlichióze"," peptidoglykánu baktérií"," anaplaziem v granulocytoch"," retikulárnych teliesok chlamýdií"],
   },
];
